[[aurads-create]]
= Creating an AuraDS instance
:description: This page describes how to create a Neo4j AuraDS instance.

. Navigate to the https://console.neo4j.io/?product=aura-ds[Neo4j Aura Console^].
. Select *Create an instance* to open the *Create an instance* page.
. Set the *Instance details*:
* *Instance Name* - The name to give to the instance. A descriptive name makes it easier to find a specific instance among many.
* *Number of nodes/relationships* - The estimated number of nodes and relationships that the instance should support.
. Select one or more algorithm categories from the *Which algorithms are you going to use?* section (or the *I'm not sure yet* option) to help estimate the most appropriate instance size. An overview of each algorithm category can be found https://neo4j.com/docs/graph-data-science/current/algorithms/[here^].
. Select *Calculate Estimate* to get an estimate of the resources needed to run the graph (memory, CPU, storage) along with the expected price.
. Select *Create Instance* to proceed.
. Copy and store the *Username* and *Generated password* credentials to access the instance just created.
+
WARNING: *Warning*: Make sure that the username and password are stored safely before continuing. Credentials cannot be recovered afterwards.
+
. Tick the *I have stored these credentials safely to use later* checkbox and select *Continue*.

[NOTE]
====
Multi-database is not supported within Neo4j AuraDS.
====

The process will take a few minutes to complete. Upon completion, you will be able to xref:aurads/getting-started/access.adoc[access the instance].
