[[aurads]]
= Neo4j AuraDS overview
:description: This section introduces Neo4j AuraDS.
:check-mark: icon:check[]
:table-caption!:

AuraDS is the fully managed version of Neo4j Graph Data Science. 

AuraDS instances:

* are automatically upgraded and patched;
* can be seamlessly scaled up or down;
* can be paused to reduce costs.

== Plans

AuraDS offers the *AuraDS Professional* and *AuraDS Enterprise* subscription plans.
The full list of features for each plan is available on the link:https://neo4j.com/pricing/#graph-data-science[Neo4j Pricing page].

For information on the different levels of support offered in each plan, see the xref:aurads/support.adoc[support page].

== Updates and upgrades

AuraDS updates and upgrades are handled by the platform, and as such do not require user intervention. Security patches and new versions of GDS and Neo4j are installed within short time windows during which the affected instances are unavailable.

The operations are non-destructive, so graph projections, models, and data present on an instance are not affected. No operation is applied until all the running GDS algorithms have completed.
