[[aurads-support]]
= Support
:description: This page describes the levels of support offered by Neo4j Aura.
:check-mark: icon:check[]

The following support levels are available:

[cols="49a,^17a,^17a",options="header"]
|===
|
| label:AuraDS-Professional[]
| label:AuraDS-Enterprise[]

| https://aura.support.neo4j.com/[Support Portal]
| {check-mark}
| {check-mark}

| https://aura.feedback.neo4j.com/[Feedback Portal + Changelog]
| {check-mark}
| {check-mark}

| Ticket-based support
| No SLA
| {check-mark}

| Premium ticket-based support, via the Support Portal
|
| {check-mark}
|===

== Operational status

All users can access the https://status.neo4j.io/[Aura Status page] to check the operational status, and to subscribe to updates.

== Response times and office hours

Local business hours are 8:00am to 6:00pm, Monday through Friday, excluding major holidays as detailed below.

Enterprise Premium Support::
Neo4j Support Engineers provide a 24 x 7 x 365 support for Severity 1 issues for Enterprise customers, regardless of weekday, weekend footnote:[Weekends are defined as Saturday and Sunday.], or holiday:

* Severity 1: < 1 hour
* Severity 2: < 4 business hours
* Severity 3: < 8 business hours
* Severity 4: < 8 business hours

+
Any Severity 2, 3 and 4 submitted on a weekend or holiday will be responded to on the next business day.

All tickets submitted on a weekend or holiday (except for the _Enterprise_ level) will be responded to on the next business day.

include::partial$holiday-table.adoc[]