[[aura-reference-security]]
= Encryption
:description: Aura is encrypted using intra-cluster encryption, and is CMK compatible.

All data stored in Neo4j Aura is encrypted using intra-cluster encryption between the various nodes comprising your instance and encrypted at rest using the underlying cloud provider's encryption mechanism.

By default, each cloud provider encrypts all backup buckets (including the objects stored inside) using either link:https://cloud.google.com/storage/docs/encryption/default-keys[Google-managed encryption], link:https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingServerSideEncryption.html[AWS SSE-S3 encryption], or link:https://learn.microsoft.com/en-us/azure/storage/common/storage-service-encryption[Azure Storage encryption].

== Supported TLS cipher suites

For additional security, client communications are carried via TLS v1.2 and TLS v1.3.

AuraDB has a restricted list of cipher suites accepted during the TLS handshake, and does not accept all of the available cipher suites.
The following list conforms to safety recommendations from IANA, the OpenSSL, and GnuTLS library.

TLS v1.3:

* `TLS_CHACHA20_POLY1305_SHA256 (RFC8446)`
* `TLS_AES_128_GCM_SHA256 (RFC8446)`
* `TLS_AES_256_GCM_SHA384 (RFC8446)`

TLS v1.2:

* `TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (RFC5288)`
* `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (RFC5289)`
* `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (RFC5289)`
* `TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (RFC7905)`
* `TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (RFC5288)`





