[[aura-reference-security]]
= Single Sign-On (SSO)
:description: SSO allows you to log in to the Aura Console using their company IdP credentials.

label:AuraDB-Enterprise[]
label:AuraDS-Enterprise[]

== SSO levels

Aura admins can configure organization and tenant level SSO:

. *Organization level SSO*: This configuration applies to all tenants and new database instances created within your organization.

. *Tenant level SSO*:  SSO configured at the tenant level affects all new database instances created within that tenant. It ensures users logging in with SSO have access to the authorized database instances within the tenant.

== Login methods

Admins can configure a combination of one or more of the following login methods:

* Email/password
* Microsoft Entra ID
* Okta
* Microsoft Entra ID
* Google Sign-in

An organization's admin can add Aura as a login from a tile in an organization's Apps Dashboard.

== Setup requirements

Accessing Aura with SSO requires:
 
* Authorization Code Flow
* A publicly accessible Identity Provider (IdP) server

To configure SSO, go to *Aura Console > Settings > SSO Configuration.*

To create a SSO Configuration either a Discovery URI or a combination of Issuer, Authorization Endpoint, Token Endpoint and JWKS URI is required.

== Configurations available from Support

* Microsoft Entra ID
* Okta
* Keycloak
* Google Authentication

Support can assist with:

* Role mapping specific to a database
* Custom groups claim besides `groups`
* Updating SSO on already running instances

If you would like support assistance, please https://support.neo4j.com/[raise a support ticket] including the following information:

. The _Tenant ID_ of the tenant(s) you want to use SSO. See xref:platform/user-management.adoc#_tenants[Tenants] for more information on how to find your __Tenant ID__.
. The name of your IdP.