[[aura-reference-security]]
= Single Sign-On (SSO)
:description: SSO allows you to log in to the Aura Console using their company IdP credentials.

label:AuraDB-Enterprise[]
label:AuraDS-Enterprise[]

== Introduction to SSO

Aura Enterprise supports Single Sign-On (SSO) at the organization, project, and instance level.

Aura Admins can configure organization and project level SSO. Aura Support can configure instance level SSO. 

SSO allows for both keeping data safe and providing authorized users safe access to the data.
This section describes how to set up Aura SSO with Role-Based Access Control (RBAC) for centrally controlled privileges as well as data access.

== Requirements

Accessing Aura with SSO requires:
 
* Authorization Code Flow with PKCE (Proof Key for Code Exchange).
* A publicly accessible Identity Provider (IdP) server.

== Configuring SSO 

Users can configure a combination of one or more of the following login methods:

* Email/password
* Okta
* Microsoft Entra ID (previously Azure Active Directory)

An organization's admin can add Aura as a log in from a tile in an organization's Apps Dashboard.

== Home Realm Discovery 

Home Realm Discovery (HRD) is when a user enters their email on the login form, an Auth0 connection that is configured with a domain that matches the email domain will redirect the user to the Auth0 connection IdP.

Users that have HRD enabled are redirected to a view where they can select from a list of their IdPs, if the customer has configured more than one IdP.

== SSO setup requirements 

To configure SSO from the Aura side, go to the *Aura Console > Settings > SSO Configuration.*

The set-up form requires the following info:

* SSO config ID - you decide a name for this
* IdP type (e.g. Okta / Microsoft Entra ID)
* Channel
* Client ID 
* Client Secret
* Discovery URI
* Issuer
* Authorization Endpoint

== Organization SSO

Organization SSO allows log in to the Aura Console using organization IdP credentials.

To facilitate organization SSO login, an Auth0 organization will need to be created and all users will need to be added to the auth0 organization. Tenants/projects will need to have an organization associated with them, and users will be added to the organization when they are invited and join.

== Mapping an organization

When you map an organization to your IdP, Aura grants users who authenticate through the IdP membership in the selected organization.

You can give these users a default role in the selected organization. There can be multiple organizations.

Organization mapping lets you configure a single IdP to grant users access to multiple organizations within the Neo4j Aura Console. 

.Organization roles
[cols="25m,75v"]
|===
| Role | Permissions

| Organization Owner
| • Full access to read/write organization

• Full access to list/read/write tenants

• Given to self serve users during registration instead of a tenant role

• Can create/edit/delete SSO [Enterprise Only]

• Can invite to any role up to owner

| Organization Admin
| • Full access to read/write org details

• Full access to list/create tenants

• Can create/edit/delete SSO [Enterprise Only]

• Can invite to any role up to admin

| Organization Member (Default when added to tenant)
| • Full access to read organization

• Full access to list tenants

• Default role for users given access to a single tenant via invite/marketplace

|===

== Console SSO

Console SSO allows log in to the Aura Console using company IdP credentials and grants link:{neo4j-docs-base-uri}/cypher-manual/current/administration/access-control/built-in-roles#access-control-built-in-roles-public[Public Access privileges] to all instances in the tenant.

The following OpenID Connect (OIDC) certified Identity Providers (IdPs) are currently supported for Console-level Authentication:

* Microsoft Azure Active Directory (AAD)
* Okta

== Instance SSO

Instance SSO allows you to directly map groups of users (as defined in your IdP) to DBMS RBAC roles when launching Workspace, Bloom and Browser clients from an Aura instance.

The following OIDC certified IdPs are currently supported for instance-level Authentication:

* Microsoft Azure Active Directory (AAD)
* Okta
* Keycloak
* Google Authentication

To add SSO for Workspace, Bloom, and Browser to your Aura Enterprise instances, please https://support.neo4j.com/[raise a support ticket] including the following information:

. The *Connection URI* of the instance(s) you want to use SSO.
. Whether or not you want Workspace, Bloom, Browser, or a combination of them enabled.
. The name of your IdP.

[NOTE]
====
If you have to specify an application type when configuring your client, Neo4j is a Single-page application.
For more information on configuring your client, see link:{neo4j-docs-base-uri}/operations-manual/current/tutorial/tutorial-sso-configuration/[Neo4j Single Sign-On (SSO) Configuration].
====