[[aura-reference-security]]
= Single Sign-On (SSO)
:description: SSO allows you to log in to the Aura Console using their company IdP credentials.

label:AuraDB-Enterprise[]
label:AuraDS-Enterprise[]
label:AuraDB-Business-Critical[]

Aura Enterprise and Aura Business Critical supports Single Sign-On (SSO) at both the Console level and for accessing Workspace, Bloom and Browser clients directly at the instance level.

[NOTE]
====
Accessing Aura with SSO requires:
 
* Authorization Code Flow with PKCE.
* A publicly accessible Identity Provider (IdP) server.
====

== Console SSO

Console SSO allows you to log in to the Aura Console using company IdP credentials and grants link:{neo4j-docs-base-uri}/cypher-manual/current/administration/access-control/built-in-roles#access-control-built-in-roles-public[Public Access privileges] to all instances in the tenant.

The following OpenID connect (OIDC) certified Identity Providers (IdPs) are currently supported for Console-level Authentication with Aura Enterprise and Aura Business Critical:

* Microsoft Entra ID
* Okta

To enable Console SSO on your tenant(s), please https://support.neo4j.com/[raise a support ticket] including the following information:

. The _Tenant ID_ of the tenant(s) you want to use SSO. See xref:platform/user-management.adoc#_tenants[Tenants] for more information on how to find your __Tenant ID__.
. The name of your IdP.

== Instance SSO

Instance SSO allows you to directly map groups of users (as defined in your IdP) to DBMS RBAC roles when launching Workspace, Bloom and Browser clients from an Aura instance.

The following OIDC certified IdPs are currently supported for instance-level Authentication:

* Microsoft Entra ID
* Okta
* Keycloak
* Google Authentication

To add SSO for Workspace, Bloom, and Browser to your Aura Enterprise instances, please https://support.neo4j.com/[raise a support ticket] including the following information:

. The *Connection URI* of the instance(s) you want to use SSO.
. Whether or not you want Workspace, Bloom, Browser, or a combination of them enabled.
. The name of your IdP.

[NOTE]
====
If you have to specify an application type when configuring your client, Neo4j is a Single-page application.
For more information on configuring your client, see link:{neo4j-docs-base-uri}/operations-manual/current/tutorial/tutorial-sso-configuration/[Neo4j Single Sign-On (SSO) Configuration].
====
