[[aurads-load-csv]]
= Loading CSV data
:description: This page describes how to load CSV data into a Neo4j AuraDS instance.

WARNING: Review pending changes to the UI

WARNING: Add short Python tutorial here

You can load data from a *_.csv_* file into an AuraDS instance with the https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/[`LOAD CSV`] Cypher statement within Neo4j Browser.
For instructions on how to open an AuraDS instance with Neo4j Browser, see xref:aurads/connecting/neo4j-applications.adoc[].

TIP: When using MERGE or MATCH with LOAD CSV, make sure you have an index or a unique constraint on the property that you are merging on. This will ensure that the query executes in a performant way. For more information, check out the https://neo4j.com/docs/getting-started/current/cypher-intro/load-csv/#_prepare_the_database[Import data] tutorial in the Cypher documentation.

There are some limitations to consider when loading a *_.csv_* file into an AuraDS instance:

* For security reasons, you must host your *_.csv_* file on a publicly accessible HTTP or HTTPS server. Examples of such servers include GitHub, Google Drive, and Dropbox.

* The `LOAD CSV` command is built to handle small to medium-sized data sets, such as anything up to 10 million nodes and relationships. You should avoid using this command for any data sets exceeding this limit.
