[[aura-cloud-providers]]
= Aura with cloud provider marketplaces
:description: This page proved information about Neo4j Aura with cloud marketplaces.
:page-aliases: platform/cloud-providers.adoc

== AuraDB Virtual Dedicated Cloud, AuraDS Enterprise, and AuraDB Business Critical

label:AuraDB-Virtual-Dedicated-Cloud[]
label:AuraDS-Enterprise[]
label:AuraDB-Business-Critical[]

You can purchase AuraDB Virtual Dedicated Cloud, AuraDS Enterprise, and AuraDB Business Critical via private offer through the following cloud provider marketplaces:

* Amazon Web Services (AWS)
* Microsoft Azure (Azure)
* Google Cloud Platform (GCP)

mailto:marketplace-sales@neo4j.com[Contact us] to discuss private offers.

== Aura Professional

label:AuraDB-Professional[]
label:AuraDS-Professional[]

You can purchase Neo4j Aura Professional on a pay-as-you-go basis through the following cloud provider marketplaces:

* Amazon Web Services (AWS)
* Microsoft Azure (Azure)
* Google Cloud Platform (GCP)

[NOTE]
====
Credits from cloud marketplace providers cannot be used for payment towards Neo4j Aura.
====

Purchasing Neo4j Aura Professional through a cloud provider marketplace gives you access to integrated billing and usage reporting in your chosen cloud provider's console.

=== AWS

[discrete]
==== 1. Purchase the service

To get started, visit the link:https://aws.amazon.com/marketplace/pp/prodview-2t3o7mnw5ypee?trk=176b570f-20dd-4b84-aa7e-cae53990fe91&sc_channel=el&source=neo4j[Neo4j Aura Professional AWS Marketplace page] and select *View Purchase options*.

From here you need to select the *Neo4j Aura Professional* Contract option, decide if you would like to auto-renew your contract when it ends, and then select *Create contract* and *Pay now*.


Note that while you are shown a $0 yearly contract option, pricing is pay-as-you-go based on usage and not a fixed subscription service.


[discrete]
==== 2. Set up your account

To start using Neo4j Aura, select *Click here to set up your account* to be directed to the Aura Console.

If you are not already logged in to the Aura Console, you will be taken to the Neo4j Aura login/sign-up page.
From here you can either log in with an existing Neo4j Aura account or create a new one.

You do not need to use the same email address for your Neo4j Aura account as your AWS account.

If you are creating a Neo4j Aura account for the first time, you will need to confirm your email address and accept the Neo4j Aura Terms of Service before you can access the Aura Console.

Once logged in to the Aura Console, the AWS Marketplace order will be confirmed, and your account will automatically default to the AWS Marketplace tenant.

=== GCP

[discrete]
==== 1. Purchase the service

To get started, visit the https://console.cloud.google.com/marketplace/product/endpoints/prod.n4gcp.neo4j.io[Neo4j Aura GCP Marketplace page] and click *Purchase*.

Note that pricing is pay-as-you-go based on usage and you won't be billed until you create an instance.

[NOTE]
====
Purchasing from the GCP Marketplace requires the `Billing Account Administrator (roles/billing.admin)` role as highlighted in the https://cloud.google.com/billing/docs/how-to/billing-access[Overview of Cloud Billing access control] Google Cloud documentation.
====

[discrete]
==== 2. Choose a project

If you purchase the service at the top level of your GCP account, you'll need to choose a target project.
You will only need to _purchase_ Neo4j Aura for GCP once, as you can then enable it on a project-by-project basis.
However, you still need to choose a target project when you first purchase the service.

[discrete]
==== 3. Enable the service

Once you have purchased the service and switched to a target project, select *Enable* to activate Neo4j Aura for GCP on your project.

[NOTE]
====
Enabling a service through GCP requires the `roles/serviceusage.serviceUsageAdmin` role as highlighted in the https://cloud.google.com/service-usage/docs/access-control#roles[Access Control with IAM] Google Cloud documentation.
====

Once you have enabled the service, you will be directed to the *Neo4j Aura for GCP API* page.
This page displays your service details and billing information.
When this is first set up, you should have no billing history.

[discrete]
==== 4. Complete the set up

pass:[<!-- vale Vale.Terms = NO -->]
pass:[<!-- vale Neo4j.ParaNewLine = NO -->]

To start using Neo4j Aura, select *MANAGE VIA NEO4J, INC.* to be directed to the Aura Console.

[NOTE]
====
When you click "MANAGE VIA NEO4J, INC.", you will be alerted that "You're leaving Google".
When you click *Confirm*, if the Aura Console fails to open you may need to address any popup blockers in your browser and try again.
====

pass:[<!-- vale Vale.Terms = YES -->]
pass:[<!-- vale Neo4j.ParaNewLine = YES -->]

For security purposes, Neo4j and GCP do not share your login credentials.
You will need to log in to the Neo4j Console with the same Google account you have used on GCP.

Once logged in, you'll be asked to accept the Neo4j Aura Terms of Service, before being directed to the Neo4j Console and placed within your GCP Marketplace tenant.

From here, you are ready to create a Neo4j Aura instance hosted on GCP and usage will be billed directly to your GCP billing account.

=== Azure

[discrete]
==== 1. Purchase the service

To get started, visit the https://azuremarketplace.microsoft.com/en-us/marketplace/apps/neo4j.neo4j_aura_professional?tab=overview[Neo4j Aura Professional Azure Marketplace page] and select *Get It Now*.

[discrete]
==== 2. Sign in to your Microsoft Azure Marketplace account

[discrete]
==== 3. Subscribe to Neo4j Aura Professional

* Select the resource group that the Aura Professional subscription will apply to.
Then, create a name for the SaaS subscription so you can easily identify it later.
* Your billing term will be a 1-month subscription at $0 cost.
Aura Professional has a consumption based pricing model, so you will only be charged for the amount you consume in Gigabyte hours (Gb/h)
* Set recurring billing to *On*
* Click *Review + subscribe*

[NOTE]
====
* Ensure your Azure account is upgraded before continuing.
* Enable *marketplace purchases* in Azure.
See more info on the https://learn.microsoft.com/en-us/azure/cost-management-billing/manage/enable-marketplace-purchases[Azure website]
====
