[[aura-cloud-providers]]
= Aura with cloud provider marketplaces
:description: This page proved information about Neo4j Aura with cloud marketplaces.
:page-aliases: platform/cloud-providers.adoc

// label:AuraDB-Virtual-Dedicated-Cloud[]
// label:AuraDS-Enterprise[]
// label:AuraDB-Business-Critical[]

You can subscribe to Neo4j Aura from cloud provider marketplaces.
Your subscription gets billed together with other services that you're already using, and can contribute towards your spend commitment with cloud providers.
The following marketplaces are available:

* Amazon Web Services (AWS)
* Microsoft Azure (Azure)
* Google Cloud Platform (GCP)

mailto:marketplace-sales@neo4j.com[Contact us] to discuss private offers.


[NOTE]
====
Credits from cloud marketplace providers cannot be used for payment towards Neo4j Aura.
====


label:AuraDB-Professional[]

== AWS Marketplace

=== Pay-as-you-go

You can subscribe to Neo4j Aura via the link:https://aws.amazon.com/marketplace/pp/prodview-2t3o7mnw5ypee?trk=176b570f-20dd-4b84-aa7e-cae53990fe91&sc_channel=el&source=neo4j[AWS marketplace].
Currently this marketplace subscription only provides access to AuraDB Professional.
Support for additional Neo4j products such as AuraDB Business Critical, Aura Graph Analytics, and more will be added.

. *Subscribe to Neo4j Aura*
+
To get started, visit link:https://aws.amazon.com/marketplace/pp/prodview-2t3o7mnw5ypee?trk=176b570f-20dd-4b84-aa7e-cae53990fe91&sc_channel=el&source=neo4j[Neo4j Aura on the AWS Marketplace] and select *View purchase options*.
+
From here, ensure auto-renewal is set to automatic to avoid service disruptions.
Then select *Create contract* and *Pay now* to continue.
Note that while you are shown a $0 yearly contract option, pricing is *pay-as-you-go* based on usage and not a fixed subscription service.

. *Set up your Neo4j Aura account*
+
To start using Neo4j Aura, select *Set up your account* to be directed to the Aura Console.
From here you can either log in with an existing Neo4j Aura account or create a new one.
+
Once logged in to the Aura Console, the AWS Marketplace order is confirmed, and your account automatically defaults to the AWS Marketplace tenant.
+
[NOTE]
====
After signing up to Neo4j Aura, two organizations are provisioned for you: a marketplace organization and a personal organization.
You need to ensure that the marketplace organization is selected before you start to deploy Neo4j.
====

=== Prepaid commitment

mailto:marketplace-sales@neo4j.com[Contact us] to discuss private offers.


label:AuraDB-Professional[]

== Azure Marketplace

=== Pay-as-you-go

You can subscribe to Neo4j Aura via the link:https://portal.azure.com/#view/Microsoft_Azure_Marketplace/GalleryItemDetailsBladeNopdl/id/neo4j.neo4j_aura_professional[Azure Marketplace].
Currently this marketplace subscription only provides access to AuraDB Professional.
Support for additional Neo4j products such as AuraDB Business Critical, Aura Graph Analytics, and more will be added.

. *Subscribe to Neo4j Aura*
+
To get started, visit link:https://portal.azure.com/#view/Microsoft_Azure_Marketplace/GalleryItemDetailsBladeNopdl/id/neo4j.neo4j_aura_professional[Neo4j Aura on the Azure Marketplace] and select *Subscribe*.
+
From here, ensure auto-renewal is set to automatic to avoid service disruptions.

. *Set up your Neo4j Aura account*
+
While you're waiting for the marketplace subscription to get created, select *Configure account* now tol be directed to the Aura Console.
From here you can either log in with an existing Neo4j Aura account or create a new one.
+
Once logged in to the Aura Console, the Azure Marketplace order is confirmed, and you can begin to use Neo4j Aura.
+
[NOTE]
====
After signing up to Neo4j Aura, two organizations are provisioned for you: a marketplace organization and a personal organization.
You need to ensure that the marketplace organization is selected before you start to deploy Neo4j.
====

=== Prepaid commitment

mailto:marketplace-sales@neo4j.com[Contact us] to discuss private offers.

label:AuraDB-Professional[]
label:AuraDB-Business-Critical[]

== Google Cloud Marketplace

=== Pay-as-you-go

You can subscribe to Neo4j Aura via the link:https://console.cloud.google.com/marketplace/product/neo4j-mp-public/neo4j-aura[Google Cloud marketplace].

. *Subscribe to Neo4j Aura*
+
To get started, visit link:https://console.cloud.google.com/marketplace/product/neo4j-mp-public/neo4j-aura[Neo4j Aura on the Google Cloud Marketplace] and select *Subscribe* and continue with the subscription process.
+
Purchasing from the Google Cloud Marketplace requires the `Billing Account Administrator (roles/billing.admin)` role as highlighted in the link:https://cloud.google.com/billing/docs/how-to/billing-access[Overview of Cloud Billing access control].

. *Set up your Neo4j Aura account*
+
After creating the marketplace subscription, select *Sign up with Neo4j* to be directed to the Aura Console.
From here you can either log in with an existing Neo4j Aura account or create a new one.
+
Once logged in to the Aura Console, the Google Cloud Marketplace order will be confirmed, and you can begin to consume Neo4j Aura.
+
[NOTE]
====
After signing up to Neo4j Aura, two organizations are provisioned for you: a marketplace organization and a personal organization.
You need to ensure that the marketplace organization is selected before you start to deploy Neo4j.
====

label:AuraDB-Professional[]
[[legacy-subscription]]
=== Legacy pay-as-you-go subscriptions

If you subscribed to Neo4j Aura on the Google Cloud marketplace prior to September 19, 2025, you are running on a legacy marketplace subscription.
Legacy marketplace subscriptions only have Neo4j AuraDB Professional.
AuraDB Business Critical, Aura Graph Analytics, and other features are unavailable until you subscribe to the new listing.

You can still log into the link:https://console.neo4j.io[Neo4j Aura console] directly and connect to your GCP marketplace organization.
Note that new users need to be added from the xref:user-management.adoc[User Management] settings within Aura console, and cannot be added directly with a punch-out from the legacy GCP marketplace listing.

label:AuraDB-Professional[]
[[update-legacy]]
=== Update your legacy subscriptions

. Subscribe to the new link:https://console.cloud.google.com/marketplace/product/neo4j-mp-public/neo4j-aura[Neo4j Aura marketplace listing on Google Cloud]
+
Purchasing from the Google Cloud Marketplace requires the `Billing Account Administrator (roles/billing.admin)` role as highlighted in the link:https://cloud.google.com/billing/docs/how-to/billing-access[Overview of Cloud Billing access control].

. Set up your Neo4j Aura account
+
After creating the marketplace subscription, select *Sign up with Neo4j* to be directed to the Aura Console.
From here you can either log in with an existing Neo4j Aura account or create a new one.
+
Once logged in to the Aura Console, the Google Cloud Marketplace order will be confirmed, and you can begin to consume Neo4j Aura.
+
[NOTE]
====
After signing up to Neo4j Aura, two organizations are provisioned for you: a marketplace organization and a personal organization.
You need to ensure that the marketplace organization is selected before you start to deploy Neo4j.
====

. Move legacy instances
+
Move instances from your legacy Neo4j marketplace organization into your new Neo4j marketplace organization.
+
Any instances still running in your legacy Neo4j marketplace organization should be moved to your new Neo4j marketplace organization that was newly created as part of Step 2. Instructions on how to move instances to a new organization are available xref:managing-instances/backup-restore-export.adoc[here].

== Troubleshooting

If you experience any issues setting up Neo4j Aura on cloud provider marketplaces, visit link:https://support.neo4j.com[Customer Support] for assistance.