[[aura-cloud-providers]]
= Aura with cloud provider marketplaces
:description: This page proved information about Neo4j Aura with cloud marketplaces.
:page-aliases: platform/cloud-providers.adoc
// :page-role: aura-db-dedicated aura-ds-enterprise aura-db-business-critical


You can subscribe to Neo4j Aura from cloud provider marketplaces.
Your subscription gets billed together with other services that you're already using, and can contribute towards your spend commitment with cloud providers.
The following marketplaces are available:

* Amazon Web Services (AWS)
* Microsoft Azure (Azure)
* Google Cloud Platform (GCP)

mailto:marketplace-sales@neo4j.com[Contact us] to discuss private offers.


[NOTE]
====
Credits from cloud marketplace providers cannot be used for payment towards Neo4j Aura.
====


[role=label--aura-db-professional label--aura-db-business-critical]
== AWS Marketplace

=== Pay-as-you-go

You can subscribe to Neo4j Aura via the link:https://aws.amazon.com/marketplace/pp/prodview-xd42uzj2v7dae[AWS marketplace].
Currently this marketplace subscription only provides access to AuraDB Professional.
Support for additional Neo4j products such as AuraDB Business Critical, Aura Graph Analytics, and more will be added.

. *Subscribe to Neo4j Aura*
+
To get started, visit link:https://aws.amazon.com/marketplace/pp/prodview-xd42uzj2v7dae[Neo4j Aura on the AWS Marketplace] and select *View purchase options*.
+
From here, ensure *auto-renewal* is set to automatic to avoid service disruptions.
Then select *Create contract* and *Pay now* to continue.
Note that while you are shown a $0 yearly contract option, pricing is *pay-as-you-go* based on usage and not a fixed subscription service.

. *Set up your Neo4j Aura account*
+
To start using Neo4j Aura, select *Set up your account* to be directed to the Aura Console.
From here you can either log in with an existing Neo4j Aura account or create a new one.
+
Once logged in to the Aura Console, the AWS Marketplace order is confirmed, and your account automatically defaults to the AWS Marketplace tenant.
+
[NOTE]
====
After signing up to Neo4j Aura, two organizations are provisioned for you: a marketplace organization and a personal organization.
You need to ensure that the marketplace organization is selected before you start to deploy Neo4j.
====

[[legacy-subscription-aws]]
[role=label--aura-db-professional]
=== Legacy pay-as-you-go subscriptions

If you subscribed to Neo4j Aura on the AWS marketplace prior to November 17th, 2025, you are running on a legacy marketplace subscription.
Legacy marketplace subscriptions only have Neo4j AuraDB Professional.
AuraDB Business Critical, Aura Graph Analytics, and other features are unavailable until you subscribe to the new listing.

[IMPORTANT]
====
Legacy marketplace subscriptions will be deprecated on September 19, 2026.
To avoid service disruption, make sure to update your legacy subscriptions, as described below.
This process takes a few minutes and does *not* require any data movement or new instance creation, and does *not* result in any downtime.
====

[[update-legacy-aws]]
==== Update your legacy subscriptions

You must be an organization admin or owner to perform the migration.

. *Subscribe to the new Neo4j Aura marketplace listing on AWS*
+
Visit link:https://aws.amazon.com/marketplace/pp/prodview-xd42uzj2v7dae[Neo4j Aura marketplace listing on AWS]

. *Log in to your Neo4j Aura account*
+
After creating the marketplace subscription, select *Sign up with Neo4j* and you will be directed to the Aura Console.
From here you can log in with your existing Neo4j Aura account.

. *Update your legacy Neo4j projects*
+
After logging in to Neo4j Aura, you will be prompted to update your legacy Neo4j Aura projects.
Select your legacy projects to continue.
+
You are now updated to the new marketplace listing.

. *Unsubscribe from the legacy marketplace listing*
+
When you have confirmed that your project is billed through the new subscription, you can cancel your legacy subscription from AWS.
This should be done *after* your project is migrated to the new subscription, otherwise it results in the suspension of your Aura instances.

=== Prepaid commitment

mailto:marketplace-sales@neo4j.com[Contact us] to discuss private offers.


[role=label--aura-db-professional]
== Azure Marketplace

=== Pay-as-you-go

You can subscribe to Neo4j Aura via the link:https://portal.azure.com/#view/Microsoft_Azure_Marketplace/GalleryItemDetailsBladeNopdl/id/neo4j.neo4j-aura[Azure Marketplace].

. *Subscribe to Neo4j Aura*
+
To get started, visit link:https://portal.azure.com/#view/Microsoft_Azure_Marketplace/GalleryItemDetailsBladeNopdl/id/neo4j.neo4j-aura[Neo4j Aura on the Azure Marketplace] and select *Subscribe*.
+
From here, ensure auto-renewal is set to automatic to avoid service disruptions.
Continue with the flow and confirm with *Review + subscribe* to continue.

. *Set up your Neo4j Aura account*
+
Once your marketplace subscription is created, select *Configure account* now to be directed to the Aura Console.
From here you can either log in with an existing Neo4j Aura account or create a new one.
+
Once logged in to the Aura Console, the Azure Marketplace order is confirmed, and you can begin to use Neo4j Aura.
+
[NOTE]
====
After signing up to Neo4j Aura, two organizations are provisioned for you: a marketplace organization and a personal organization.
You need to ensure that the marketplace organization is selected before you start to deploy Neo4j.
====

[[legacy-subscription-azure]]
[role=label--aura-db-professional]
=== Legacy pay-as-you-go

If you subscribed to Neo4j Aura on the Azure marketplace prior to January  13th, 2026, you are running on a legacy marketplace subscription.
Legacy marketplace subscriptions only have Neo4j AuraDB Professional. AuraDB Business Critical, Aura Graph Analytics, and other features are unavailable until you subscribe to the new listing.

You can still log into the link:https://console.neo4j.io[Neo4j Aura console] directly to access your existing Azure marketplace organization.

[IMPORTANT]
====
Legacy marketplace subscriptions will be deprecated on September 19, 2026.
To avoid service disruption, make sure to update your legacy subscriptions, as described below.
This process takes a few minutes and does *not* require any data movement or new instance creation, and does *not* result in any downtime.
====

[[update-legacy-azure]]
==== Update your legacy subscriptions

You must be an organization admin or owner to perform the migration.

. *Subscribe to the new Neo4j Aura listing on Azure*
+
Vist link:https://portal.azure.com/#view/Microsoft_Azure_Marketplace/GalleryItemDetailsBladeNopdl/id/neo4j.neo4j-aura[Neo4j Aura marketplace listing on Azure].

. *Log in to your Neo4j Aura account*
+
After creating the marketplace subscription, use *Configure account now* to be directed to the Aura Console.
From here you can log in with your existing Neo4j Aura account.
+

. *Move legacy instances*
+
After logging inn to Neo4j Aura, you will be prompted to update your legacy Neo4j Aura projects.
Select your legacy projects to continue.
+
You are now updated to the new marketplace listing.

. *Unsubscribe from the legacy marketplace listing*
+
When you have confirmed that your project is billed through the new subscription, you can cancel your legacy subscription from Azure.
This should be done *after* your project is migrated to the new subscription, otherwise it results in the suspension of your Aura instances.

=== Prepaid commitment

mailto:marketplace-sales@neo4j.com[Contact us] to discuss private offers.

[role=label--aura-db-professional label--aura-db-business-critical]
== Google Cloud Marketplace

=== Pay-as-you-go

You can subscribe to Neo4j Aura via the link:https://console.cloud.google.com/marketplace/product/neo4j-mp-public/neo4j-aura[Google Cloud marketplace].

. *Subscribe to Neo4j Aura*
+
To get started, visit link:https://console.cloud.google.com/marketplace/product/neo4j-mp-public/neo4j-aura[Neo4j Aura on the Google Cloud Marketplace] and select *Subscribe* and continue with the subscription process.
+
Purchasing from the Google Cloud Marketplace requires the `Billing Account Administrator (roles/billing.admin)` role as highlighted in the link:https://cloud.google.com/billing/docs/how-to/billing-access[Overview of Cloud Billing access control].

. *Set up your Neo4j Aura account*
+
After creating the marketplace subscription, select *Sign up with Neo4j* to be directed to the Aura Console.
From here you can either log in with an existing Neo4j Aura account or create a new one.
+
Once logged in to the Aura Console, the Google Cloud Marketplace order will be confirmed, and you can begin to consume Neo4j Aura.
+
[NOTE]
====
After signing up to Neo4j Aura, two organizations are provisioned for you: a marketplace organization and a personal organization.
You need to ensure that the marketplace organization is selected before you start to deploy Neo4j.
====

[[legacy-subscription-gcp]]
[role=label--aura-db-professional]
=== Legacy pay-as-you-go subscriptions

If you subscribed to Neo4j Aura on the Google Cloud marketplace prior to September 19, 2025, you are running on a legacy marketplace subscription.
Legacy marketplace subscriptions only have Neo4j AuraDB Professional.
AuraDB Business Critical, Aura Graph Analytics, and other features are unavailable until you subscribe to the new listing.

You can still log into the link:https://console.neo4j.io[Neo4j Aura console] directly to access your GCP marketplace organization.
Note that new users who need access to your existing Neo4j Aura GCP marketplace organization need to be added from the xref:user-management.adoc[User Management] settings within the Aura console.
New users *cannot* be added directly via _Manage on provider_ from the Google Cloud console from the legacy GCP marketplace listing.

[[update-legacy-gcp]]
==== Update your legacy subscriptions

You must be an organization admin or owner to perform the migration.

. *Subscribe to the new Neo4j Aura listing on Google Cloud*
+
Vist link:https://console.cloud.google.com/marketplace/product/neo4j-mp-public/neo4j-aura[Neo4j Aura marketplace listing on Google Cloud].
Purchasing from the Google Cloud Marketplace requires the `Billing Account Administrator (roles/billing.admin)` role as highlighted in the link:https://cloud.google.com/billing/docs/how-to/billing-access[Overview of Cloud Billing access control].

. *Log in to your Neo4j Aura account*
+
After creating the marketplace subscription, select *Sign up with Neo4j* to be directed to the Aura Console.
From here you can log in with your existing Neo4j Aura account.
+
Once logged in to the Aura Console, the Google Cloud Marketplace order will be confirmed, and you can begin to consume Neo4j Aura.

. *Update your legacy Neo4j projects*
+
After logging in to Neo4j Aura, you will be prompted to update your legacy Neo4j Aura projects.
Select your legacy projects to continue.
+
You are now updated to the new marketplace.

. *Unsubscribe from the legacy marketplace listing*
+
When you have confirmed that your project is billed through the new subscription, you can cancel your legacy subscription from Google Cloud Marketplace.
This should be done *after* your project is migrated to the new subscription, otherwise it results in the suspension of your Aura instances.

== Troubleshooting

If you experience any issues setting up Neo4j Aura on cloud provider marketplaces, visit link:https://support.neo4j.com[Customer Support] for assistance.