[[aura]]
= Aura overview
:description: Introduce the new Aura console experience.

Mic test 123

To get started with Neo4j Aura, log in at https://console-preview.neo4j.io/account/profile or simply click "Get Started Free" at the top of the page.

Neo4j Aura is a fast, scalable, always-on, fully automated graph platform available as a cloud service, designed for developers building intelligent applications. If you’ve used Aura before, you’ll find that the new Aura console experience is familiar yet enhanced. Our vision with the new console is to integrate many Neo4j tools into a single interface. Should you need to, you can temporarily roll back to the previous version of the Aura console.

For those new to Aura, you’re in for a treat with lightning-fast queries, real-time insights, built-in developer tools, data visualization, and support from the largest graph developer community. If you're just beginning with knowledge graphs, we recommend exploring Graph Academy to get started.

(C) {copyright}
License: link:{common-license-page-uri}[Creative Commons 4.0]

