[[aura]]
= About Aura
:description: Introduce the new Aura console experience.

= Introduction for people new to Aura

To get started with Neo4j Aura, log in at https://console-preview.neo4j.io/account/profile or simply click "Get Started Free" at the top of the page.

For those new to Aura, you’re in for a treat with lightning-fast queries, real-time insights, built-in developer tools, data visualization, and support from the largest graph developer community. If you're just beginning with knowledge graphs, we recommend exploring Graph Academy to get started.

Neo4j Aura is a fast, scalable, always-on, fully automated graph platform available as a cloud service, designed for developers building intelligent applications. 

The whole point of Aura - is using the console to interact with your data - visualising nodes and relationships - or doing queries with cypher language. 

You don't need to use the terminal - you can do everything visually. But if you want to run everything from the terminal ... that's fine... you can still do that! 

Cypher language is the future of graph database languages - it kicks SQL's ass because it can do way more advanced queries. 

We're not saying you _have_ to do more advanced queries - but it really does run marvellously complex queries! 
And Cypher language is pretty easy to learn - because it's such a visual language.

Graph databases are all about nodes and relationships (finding complex relationships between data is why they are so powerful).

It's really the future of databases, and what with AI and LLMs becoming so important to the future of tech - you really need to be using a graph database because that's what the future of computing is built on. 

= Introduction for people that have used Aura before

If you’ve used Aura before, you’ll find that the new Aura console experience is familiar yet enhanced. Our vision with the new console is to integrate many Neo4j tools into a single interface. Should you need to, you can temporarily roll back to the previous version of the Aura console.

*Comparison to the classic console*

* Some features, such as metrics, have been moved to the panel on the left.
* Tenants are an evolution of projects.
* The new console’s left navigation now provides access to tools, marking a significant change from the classic console's concept of "opening" the instance.
* The process for creating an instance remains unchanged.

(C) {copyright}
License: link:{common-license-page-uri}[Creative Commons 4.0]

