[[aura-guide]]
= Neo4j Aura
:description: This manual describes how to use Neo4j Aura.

Neo4j Aura is a fully managed cloud graph database service. 

Built to leverage relationships in data, Aura enables lightning-fast queries for real-time analytics and insights.
Aura is reliable, secure, and fully automated, enabling you to focus on building graph applications without worrying about database administration.

[discrete]
== Plans

Aura offers three subscription plans: Free, Professional, and Enterprise. 
Each plan offers different levels of functionality and support; for more information, see https://neo4j.com/cloud/aura/pricing/#pricing-table[Neo4j Aura Pricing].

[discrete]
== Upgrades

Patch releases (for example, 4.2.*5* -> 4.2.*6*) and minor-version releases (for example, 4.*1*.8 -> 4.*2*.0) for the Neo4j database are automatically applied to Aura deployments when they become available. 
Patching operations are non-disruptive, and you won't experience any downtime as a result.

(C) {copyright}
License: link:{common-license-page-uri}[Creative Commons 4.0]