[[aura]]
= About Aura
:description: Introduce the new Aura console experience.

To get started with Neo4j Aura, log in at https://console-preview.neo4j.io/account/profile, or click "Get Started Free" at the top of the page.

= Intro for people that have used Aura before

If you’ve used Aura before, you’ll find that the new Aura console experience is familiar yet enhanced. 
The vision of the new console is to integrate many Neo4j tools into a single interface. 
Should you need to, you can temporarily roll back to the previous version of the Aura console.

*Comparison to the classic console*

* Some features, such as metrics, have been moved to the panel on the left.
* Tenants are an evolution of projects.
* The new console’s left navigation now provides access to tools, marking a significant change from the classic console's concept of "opening" the instance.
* The process for creating an instance remains unchanged.

= Intro for people new to Aura

Use the Aura console to interact with your data — from visualizing nodes and relationships to executing queries with the Cypher language. 
Cypher is the future of graph database languages, outperforming SQL with its ability to handle far more advanced queries. 
While you don’t _have_ to delve into complex queries, Cypher truly shines in executing them, and its visual nature makes it surprisingly easy to learn.

This set of documentation will give you enough info to get comfortable with the console and get started.
If you need any additional information you can visit the link:https://neo4j.com/docs/[docs homepage].

This set of documentation delves into various aspects of using the Aura console, including data exploration, instance management, and utilizing the Explore tool for visualizing and interacting with graph data. 
It includes an overview of the console’s structure, covering, projects, users, instances, importing data, tools, metrics, and more. 

Graph databases excel at uncovering complex relationships within data, focusing on nodes and connections. 
This capability makes them incredibly powerful and crucial for the future of databases. 
As AI and large language models (LLMs) become increasingly central to the tech industry, using a graph database like Neo4j Aura is essential, as it forms the foundation of future computing.

(C) {copyright}
License: link:{common-license-page-uri}[Creative Commons 4.0]

