[[aura]]
= About Neo4j Aura Console
:description: Introduce the new Aura console experience.

The Neo4j Aura Console is a fully automated graph platform offered as a cloud service.
It brings together the capabilties of several tools, services, and operations from the Neo4j catalog.
To get started with Neo4j Aura, log in at link:https://console-preview.neo4j.io/account/profile[], or click "Get Started Free" at the top of the page.

The Neo4j Aura Console, or **Console** for short, is the new UI experience for Neo4j Aura users.
Use the Aura Console to import and interact with your data — from visualizing nodes and relationships to executing queries with the Cypher query language.
You can monitor your instances and databases via metrics and logs to get insight into various aspects, such as performance, resource usage, and overall system health.

The Aura environment starts with an organization which can contain multiple projects with multiple users associated.
Projects, users, and billing can all be managed directly from the same console.

If you have used Aura before, you will find the Console familiar but with a host of new features.
The classic Aura console is still available as the default experience, and will remain available until all available features have been integrated into the new Console.

*Comparison to the classic console*

* Some features, such as metrics, have been moved to the panel on the left.
* **Projects** are an evolution of **Tenants**.
* The new console's left navigation now provides access to tools, marking a significant change from the classic console's concept of "opening" the instance.
* The process for creating an instance remains unchanged.


(C) {copyright}
License: link:{common-license-page-uri}[Creative Commons 4.0]

