[[aura]]
= Neo4j Aura Documentation
:description: Introduce the new Aura console experience.
:page-aliases: auradb/index.adoc
:page-ogtitle: Neo4j Aura

Neo4j Aura is a fully automated graph platform offered as a cloud service.
It brings together the capabilties of several tools, services, and operations from the Neo4j catalog.
To get started with Neo4j Aura, log in at link:https://console.neo4j.io/account/profile[], or click "Get Started Free" at the top of the page.

The Neo4j Aura console, or **console** for short, is a UI experience for Neo4j Aura users.
Use the console to import and interact with your data — from visualizing nodes and relationships to executing queries with the Cypher query language.
You can monitor your instances and databases via metrics and logs to get insight into various aspects, such as performance, resource usage, and overall system health.

The Aura environment starts with an organization which can contain multiple projects with multiple users associated.
Projects, users, and billing can all be managed directly from the same console.

Aura includes AuraDB, a fully managed graph database, and AuraDS, a fully managed data science as a service solution for running graph analytics on Aura.
The documentation is based on AuraDB unless specified otherwise.
See xref:graph-analytics/index.adoc[] for more information about AuraDS and graph analytics.

== Products and tiers

Aura offers the following products and tiers:

*Products:*

** AuraDB
** AuraDS
** Aura Graph Analytics

*Tiers:*

** *AuraDB Free:* The free tier suitable for learning, prototyping, and small projects.
** *AuraDB Professional:* A scalable, pay-as-you-go tier for production-ready applications.
** *AuraDB Business Critical:* A highly available, multi-node cluster for mission-critical workloads.
** *AuraDB Virtual Dedicated Cloud:* A single-tenant, dedicated environment offering maximum security, isolation, and customizable configurations.

** AuraDS Professional
** AuraDS Enterprise

The full list of features available with each tier is available on the link:https://neo4j.com/pricing/[Neo4j Pricing page].



(C) {copyright}
License: link:{common-license-page-uri}[Creative Commons 4.0]

