[[aura]]
= Neo4j Aura overview
:description: This page introduces the Aura platform.

Neo4j Aura is a fast, scalable, always-on, fully automated graph platform offered as a cloud service.

Aura includes AuraDB, the graph database as a service for developers building intelligent applications, and AuraDS, the graph data science as a service for data scientists building predictive models and analytics workflows.

== Neo4j AuraDB
Neo4j AuraDB is the fully managed graph database as a service that helps build intelligent, context-driven applications faster with lightning-fast queries, real-time insights, built-in developer tools, data visualization, and integrations supported by the largest graph developer community.

For more information on AuraDB, see the xref:auradb/index.adoc[Neo4j AuraDB overview].

== Neo4j AuraDS
Neo4j AuraDS is the fully managed data science as a service solution for data scientists that unifies the machine learning (ML) surface and graph database into a single workspace, making it easy to uncover the connections in big data and answer business-critical questions.

For more information on AuraDS, see the xref:aurads/index.adoc[Neo4j AuraDS overview].

(C) {copyright}
License: link:{common-license-page-uri}[Creative Commons 4.0]

// Edit at: https://github.com/neo4j-graphacademy/courses/blob/main/asciidoc/courses/neo4j-fundamentals/promo.adoc
include::https://raw.githubusercontent.com/neo4j-graphacademy/courses/main/asciidoc/courses/neo4j-fundamentals/promo.adoc[]
