[[aura]]
= Aura overview
:description: Introduce the new Aura console experience.

Log in at https://console-preview.neo4j.io/account/profile
Or get started at the top of the page by clicking *Get Started Free*.

Neo4j Aura is a fast, scalable, always-on, fully automated graph platform offered as a cloud service, for developers building intelligent applications.

If you have used Aura before, it is likely that you are already familiar with much of the new Aura console experience. 

You will find the new experience familiar yet enhanced. 
The vision of the new Aura console is to combine many Neo4j tools in one interface.
If needed, you can roll back to the previous version of the Aura console for a limited time.

If you're new to the Aura experience, welcome to lightning-fast queries, real-time insights, built-in developer tools, data visualization, and integrations supported by the largest graph developer community.

If you’re just starting out with knowledge graphs, we recommend checking out Graph Academy.

(C) {copyright}
License: link:{common-license-page-uri}[Creative Commons 4.0]

