[[aura-query-logs]]
= Security log forwarding

label:AuraDB-Business-Critical[]
label:AuraDB-Virtual-Dedicated-Cloud[]
label:AuraDS-Enterprise[]

With security log forwarding, you can stream security logs directly to a cloud project owned by your organization, in real time.

To access *Log forwarding*:

. Navigate to *Settings* under the Project section in the sidebar.
. Click *Log forwarding*. If you cannot see this option, you may not have the necessary permissions.

This will display a list of currently configured log forwarding processes for the active project.

If no log forwarding process is set up, a button to do so is displayed in the center of the page.

== Set up log forwarding

[NOTE]
====
Aura Database and Analytics services are business critical for our users. We have requests to introduce more capabilities enabling access to logs and metrics to derive actionable insights using your choice of monitoring platform.

We have a strong roadmap of observability sharing features including security logs, query logs and other capabilities. Many of these logs can be of significant size hence *we will introduce in the future a new consumption based billing model including cloud egress costs*.

We believe security is of paramount importance hence we have decided to make security logs available for you initially at no extra charge.
====

The complete steps for setting up log forwarding depends on the chosen cloud provider.

Exhaustive instructions are provided in the wizard which appears by following the steps below.

. Navigate to the *Log forwarding* page as described above.
. Click *Configure log forwarding*.
. Select the scope for log forwarding.
* label:AuraDB-Virtual-Dedicated-Cloud[] All instances matching the selected product and region will have their logs forwarded.
* label:AuraDB-Business-Critical[] A specific instance will have its logs forwarded.
. Follow the instructions specific to your cloud provider.

== Output destination

Log forwarding can forward logs to the log service of the same cloud provider as the monitored instance is located in.

Cross-region log forwarding is supported.

If your instance is in:

* *Google Cloud Platform* - Forward logs to Google Cloud Logging in your own GCP project.
* *Amazon Web Services* - Forward logs to CloudWatch in your own AWS account.
* *Azure* - Forward logs to a Log Analytics workspace in your own Azure subscription.

Logs can be further forwarded into third party systems using the log routing capabilities provided by your cloud provider.
