= Import
:description: This is an introduction to the Import data service.
:page-aliases: auradb/importing/importing-data.adoc, aurads/importing-data/index.adoc

The Import tool lets you import data into your instance and is ideal to get started quickly with testing and prototyping.
It allows you to import data without using any code from:

* PostgreSQL
* MySQL
* SQL Server
* Oracle
* Big Query
* Databricks
* Snowflake
* AWS S3
* Azure Blobs & Data Lake Storage
* Google Cloud Storage
* .CSV

The Import tool creates indexes and constraints on the database it imports to.
Only `PROJECT_ADMIN` users have this capability and if you have the `PROJECT_MEMBER` role, the lack of privileges prevents you from using the Import tool to import data.
However, on *Business Critical* and *Virtual Dedicated Cloud* instances, it is possible to create a custom role and add necessary privileges and grant it to a user with the `PROJECT_MEMBER`.
See xref:import/appendix.adoc#create-custom-role[Create a custom import role] for more information.

This service is also available as a standalone tool for importing data into self-managed Neo4j instances.
The standalone importer is available at the following links, depending on whether you need support for unsecured connections:

** link:https://data-importer.neo4j.io/[] -- Secure only
** link:https://data-importer.graphapp.io/[] -- Both secure and unsecure


For more information, see the link:https://neo4j.com/docs/data-importer/current/[Data Importer documentation].

[NOTE]
====
Only CSV files can be imported in the standalone tool.
====

== Import via API

Additionally, import can also be achieved via API, as described in link:{neo4j-docs-base-uri}/aura/platform/api/specification/?urls.primaryName=Aura%20v2beta1#/import-jobs[Aura API specification].
Note that this is only available with v2beta1 of the Aura API.
