[[aura-cloud-providers]]
= Aura with cloud provider marketplaces

Using Neo4j Aura via a cloud provider marketplace enables you to provision and manage Neo4j Aura databases from your chosen cloud provider console, while taking advantage of any integrated billing.

The currently available cloud providers are:

* <<aura-getting-started-cloud-providers-GCP, Google Cloud Platform (GCP)>>
* <<aura-getting-started-cloud-providers-AWS, Amazon Web Services (AWS)>>
* <<aura-getting-started-cloud-providers-AZURE, Microsoft Azure (Azure)>>

[[aura-getting-started-cloud-providers-GCP]]
== Aura with GCP

label:AuraDB-Professional[]
label:AuraDS-Professional[]

[discrete]
=== 1. Purchase the service

To get started, visit the https://console.cloud.google.com/marketplace/product/endpoints/prod.n4gcp.neo4j.io[Neo4j Aura for GCP Marketplace page] and click *Purchase*.
Note that you won't be billed until you create a database, so purchasing Neo4j Aura on GCP just gets you started.

[NOTE]
====
Purchasing from the GCP marketplace requires the `Billing Account Administrator (roles/billing.admin)` role as highlighted in the https://cloud.google.com/billing/docs/how-to/billing-access[Overview of Cloud Billing access control] Google Cloud documentation.
====

[discrete]
=== 2. Choose a project

If you purchase the service at the top level of your GCP account, you'll need to choose a target project.
You will only need to _purchase_ Neo4j Aura for GCP once, as you can then enable it on a project-by-project basis. However, you still need to choose a target project when you first purchase the service.

[discrete]
=== 3. Enable the service

Once you have purchased the service and switched to a target project, you will get the option to _Enable_ the service for that project.
Click *Enable* to activate Neo4j Aura for GCP on your project.

[NOTE]
====
Enabling a service through GCP requires the `roles/serviceusage.serviceUsageAdmin` role as highlighted in the https://cloud.google.com/service-usage/docs/access-control#roles[Access Control with IAM] Google Cloud documentation.
====

Once you have enabled the service, you will be directed to the *Neo4j Aura for GCP API* page.
This page displays your service details and billing information.
When this is first set up, you should have no billing history.

[discrete]
=== 4. Completing the set up

To start a database, you can now get to the Neo4j Aura website by clicking *MANAGE VIA NEO4J, INC.*.

[NOTE]
====
When you click "MANAGE VIA NEO4J, INC.", you will be alerted that "You're leaving Google".
When you click *Confirm*, if the Neo4j Aura website fails to open you may need to address any popup blockers in your browser and try again.
====

For security purposes, Neo4j and GCP do not share your login credentials.
You will need to log in to the Neo4j Aura website with the Google account you have used on GCP.

Once logged-in, you'll be asked to accept the Neo4j Aura Terms of Service, before being directed to the Neo4j Aura dashboard.
From here, you are ready to create a Neo4j Aura database hosted on GCP.
Usage will be billed directly to your GCP billing account.

label:AuraDB-Enterprise[]
label:AuraDS-Enterprise[]

For private offers, please contact marketplace-sales@neo4j.com.

[[aura-getting-started-cloud-providers-AWS]]
== Aura with AWS

label:AuraDB-Enterprise[]
label:AuraDS-Enterprise[]

With Aura Enterprise, you can purchase Neo4j Aura databases through the AWS Marketplace.

For more information, visit the https://aws.amazon.com/marketplace/pp/B08X1N17NS[Neo4j Aura Enterprise AWS Marketplace page].

For private offers, please contact marketplace-sales@neo4j.com.


[[aura-getting-started-cloud-providers-AZURE]]
== Aura with Azure

label:AuraDB-Enterprise[]
label:AuraDS-Enterprise[]

With Aura Enterprise, you can purchase Neo4j Aura databases through the Azure Marketplace.

For more information, visit the https://azuremarketplace.microsoft.com/en-GB/marketplace/apps/neo4j.neo4j_aura?tab=overview[Neo4j Aura Azure Marketplace page].

For private offer, please contact marketplace-sales@neo4j.com.