[[aura-create-account]]
= Create an account
:description: This page describes how to create a Neo4j Aura account.

How to Create a Neo4j Aura Account
To create a Neo4j Aura account, follow these steps:

== Sign Up for Aura
. Navigate to the Neo4j Aura Console.
. Choose a sign-up method: Enter your email address and create a password, then select Register.
Or, choose Continue with Google to sign up using your Google account.
. You'll be presented with the Terms of Service and Privacy Policy. 

== Access the new Aura console (Optional)
. Once registered, you can use the Aura console.
. To use the latest version of the console, click the banner at the top that says "Early access: check out the new Aura console. Preview now."

== How to create a Free instance in Aura
. To create a graph, you'll need to create an instance. 
. In the Aura console, click the *new instance* button.
. Select your plan: Choose the Free instance option to start experimenting with a basic, free graph database.
You can upgrade to a paid plan later if you need more features or larger graphs.
. Save your credentials: Copy or download the instance’s credentials (password, etc.) as a .txt file. 
This will be required to access your instance later.

Note: You can only create one Free instance per account. To create more instances, upgrade to a paid plan or manage your existing instance.

*Neo4j Aura's free tier allows you to try out all core features of Neo4j without payment. If you need advanced features or want to connect your instance to an application, you can explore different pricing plans on the pricing page.*

