[[aura-create-account]]
= Create an account
:description: This page describes how to create a Neo4j Aura account and a new instance.

== Create an account

To access Neo4j Aura, you need to have an Aura account.
Navigate to link:https://console.neo4j.io[Neo4j Aura console] and follow the instructions for registration.
Once you have accepted the terms and conditions and verified your email address, you can start using the console.

== Access the new Aura console 
. Once registered, you can use the Aura console.
. To use the latest version of the console, click the banner at the top that says "Early access: check out the new Aura console. Preview now."

== How to create an instance in Aura
. To create a graph, you'll need to create an instance. 
In the Aura console, click the *new instance* button.
. Select your plan: Choose the Free instance option to start learning and experimenting. 
You can upgrade to a paid plan later if you need more features or larger graphs.
. Save your credentials: Copy or download the instance’s credentials (password, etc.) as a .txt file. 
This will be required to access your instance later.

Note: You can only create one Free instance per account. To create more instances, upgrade to a link:https://neo4j.com/pricing/[paid plan]. Neo4j Aura's free tier allows you to try out all core features of Neo4j without payment. If you need advanced features or want to connect your instance to an application, you can explore different pricing plans on the pricing page.

