[[aura-create-account]]
= Create an account
:description: This page describes how to create a Neo4j Aura account and a new instance.

== Create an account

To access Neo4j Aura, you need to have an Aura account.
Navigate to link:https://console.neo4j.io[Neo4j Aura console] and follow the instructions for registration.
Once you have accepted the terms and conditions and verified your email address, you can start using the console.

The console exists in two versions, the classic experience, and the early access new console, as mentioned in xref:index.adoc[About Neo4j Aura console].
You can toggle between the different versions, via the account dropdown in the top right corner. 

== Create an instance 
The first step is to select the plan that best suits your needs.
You can upgrade your plane later if your needs change.

Once you've selected a plan, your instance is created.
A password is generated for the instance, ensure to either copy or download it, as it will **not** be recoverable after.
The password is required to access your instance later.

[NOTE]
====
You can only create **one Free instance** per account.
To create more instances, you need to upgrade your plan.
See link:https://neo4j.com/pricing/[Neo4j Pricing] for more information on the different plans.
====

