[[aura-create-account]]
= Create an account
:description: This page describes how to create a Neo4j Aura account and a new instance.

== Create an account

To access Neo4j Aura, you need to have an Aura account.
Navigate to link:https://console.neo4j.io[Neo4j Aura console] and follow the instructions for registration.
Once you have accepted the terms and conditions and verified your email address, you can start using the console.

The console exists in two versions, the classic experience, and the early access new console, as mentioned in xref:index.adoc[About Neo4j Aura console].
You can toggle between the different versions, via the account dropdown in the top right corner. 

== Create an instance 
. To create a graph, you'll need to create an instance. 
In the Aura console, click the *new instance* button.
. Select your plan: Choose the Free instance option to start learning and experimenting. 
You can upgrade to a paid plan later if you need more features or larger graphs.
. Save your credentials: Copy or download the instance’s credentials (password, etc.) as a .txt file. 
This will be required to access your instance later.

[NOTE]
====
You can only create **one Free instance** per account.
To create more instances, you need to upgrade your plan.
See link:https://neo4j.com/pricing/[Neo4j Pricing] for more information on the different plans.
====

