= Overview of Editions

== Feature / Edition Matrix

The following tables provide a list of the major features and services included with each edition.

:check-mark: icon:check[]

.Roles
[opts="header",cols="4,1,1,1,1"]
|===
| Capability | Free | Pro | MTE | Enterprise
| Price Gb/h | Free | 9c | N/a | 25c
| Instance size | Node & Relationship Limit
 | 1GB-64GB RAM | 2GB-512GB+ RAM | 2GB-512GB+ RAM
| Additional RAM:Storage ratios | No | No | Yes, by exception | Yes, by exception
| Cloud Provider | GCP | GCP, AWS, Azure | GCP, AWS, Azure | GCP, AWS, Azure
| Cloud Region | Fixed (Neo4j Assigned) | Many | Many | Many 
| Different Regions | No | Yes (add-on beyond 2) | Yes (add-on beyond 2) | Yes (add-on beyond 2) 
| Single Sign-On | Limited (Google) | Yes (Okta, etc via OIDC) | Console 2 IdP & DB SSO - 4 IdP | Console 2 IdP & DB SSO - 4 IdP
| User Access Control | n/a | RW/RO User | Granular RBAC | Granular RBAC
| Tenant Isolation | Shared | Shared | Shared | Dedicated
| VPC Link & IP filtering | No | No | No | Yes
| Encryption Key Mgmt. | Neo4j managed | Neo4j managed | No | No
| View and edit billing information | {check-mark} | | add
|===

== AuraDB Free

For small development projects, learning, experimentation, and prototyping.

== AuraDB Professional

For medium-scale applications in advanced development or production environments.

== AuraDB MTE

* The architecture for MTE positions private low level infrastructure (Kubernetes Pods) on a shared compute resource (Kubernetes Node) to achieve multi-tenancy. 
* The Kubernetes Pods have a private persistent volume attached to them in a 1:1 relationship. 
* This relationship provides a layer of security as the data residing on the volume can only be accessed from a specific Kubernetes Pod. 

=== MTE is for:



=== MTE is not for:

* Organisations with strict data segregation requirements that mandate physical isolation to preserve data integrity, or that require compliance with FedRAMP.  
* Organisations that need to use highly customised features that are not suited to a multi-tenant environment, such as custom procedures.


== AuraDB Enterprise

* Where a customer is guaranteed resource isolation. 
* Orchestras are expensive to run, especially so in a single tenant architecture, therefore AuraDB Enterprise has premium pricing.


=== AuraDB Enterprise is for:

* For large-scale, mission-critical applications that require advanced security and 24x7 support.
* Organisations that require the highest level of uptime SLA.