= Overview of tiers

[NOTE]
====
You can request a time limited trial of any tier to experience it in full.
====

Neo4j offers multiple tiers to choose from, ensuring that your usage fits your organization’s specific requirements. 
Each successive edition builds on the previous edition through the addition of tier-specific features and/or higher levels of service. 
As your organization’s needs change and grow, changing tiers is easy.

The Aura tier that your organization chooses determines the unit costs for the credits and the data storage you use. 

* On Demand: Usage-based pricing with no long-term licensing requirements.
* Capacity: Discounted pricing based on an upfront Capacity commitment.

For pricing details, see the link:https://neo4j.com/pricing/[pricing page] (on the Neo4j website).

== Feature / Edition Matrix

In June 2024, Aura introduced a new MTE tier.
This tier will have Versions 1, 1.1 and 1.2.
Not all Enterprise features are available in MTE 1.
See the tables to see the differences.

[NOTE]
====
As it is a new release as of June 2024, not all Enterprise features are available in MTE 1.0 yet.
====

The primary differentiating factors between MTE and Professional will be as follows. A full, suite-wide review of the features available for each tier can be found here. 🗺️ MTE - Route to 2.0

Note - not all of these features will be available at launch. Features unavailable at launch are indicated with an asterisk. 
 
* Highly available cluster split across 3 availability zones in a region
* Advanced security features	
* Granular RBAC
* Private Link*
* Customer Managed Keys*
* Advanced configuration options
* Log forwarding*
* Metric forwarding*
* Console SSO 
* 3 node advanced metrics
* 24/7 support with SLA
* 99.9% uptime SLA

The following tables provide a list of the major features and services included with each tier.

=== Instance / Database Configuration

[.tabbed-example]
====
[.include-with-MTE-v1]
=====

[opts="header",cols="4,1,1,1,1"]
|===
| Capability | Free | Professional | MTE | Enterprise
| Instance Size | Node & Relationship Limit
 | 1GB-64GB RAM | 2GB-512GB+ RAM | 2GB-512GB+ RAM
| Additional RAM:Storage ratios | No | No | Yes, by exception | Yes, by exception
| Cloud Provider | GCP | GCP, AWS, Azure | GCP, AWS, Azure | GCP, AWS, Azure
| Cloud Region | Fixed (Neo4j Assigned) | Many | Many | Many 
| Different Regions | No | Yes (add-on beyond 2) | Yes (add-on beyond 2) | Yes (add-on beyond 2) 
|===

=====
[.include-with-MTE-v2]
=====

[opts="header",cols="4,1,1,1,1"]
|===
| Capability | Free | Professional | MTE | Enterprise
| Instance Size | Node & Relationship Limit
 | 1GB-64GB RAM | 2GB-512GB+ RAM | 2GB-512GB+ RAM
| Additional RAM:Storage ratios | No | No | Yes, by exception | Yes, by exception
| Cloud Provider | GCP | GCP, AWS, Azure | GCP, AWS, Azure | GCP, AWS, Azure
| Cloud Region | Fixed (Neo4j Assigned) | Many | Many | Many 
| Different Regions | No | Yes (add-on beyond 2) | Yes (add-on beyond 2) | Yes (add-on beyond 2) 
|===


=====
[.include-with-MTE-v3]
=====

[opts="header",cols="4,1,1,1,1"]
|===
| Capability | Free | Professional | MTE | Enterprise
| Instance Size | Node & Relationship Limit
 | 1GB-64GB RAM | 2GB-512GB+ RAM | 2GB-512GB+ RAM
| Additional RAM:Storage ratios | No | No | Yes, by exception | Yes, by exception
| Cloud Provider | GCP | GCP, AWS, Azure | GCP, AWS, Azure | GCP, AWS, Azure
| Cloud Region | Fixed (Neo4j Assigned) | Many | Many | Many 
| Different Regions | No | Yes (add-on beyond 2) | Yes (add-on beyond 2) | Yes (add-on beyond 2) 
|===

=====
====



.Security & Compliance
[opts="header",cols="4,1,1,1,1"]
|===
| Capability | Free | Professional | MTE | Enterprise
| Single Sign-On | Limited (Google) | Yes (Okta, etc via OIDC) | Console 2 IdP & DB SSO - 4 IdP | Console 2 IdP & DB SSO - 4 IdP
| User Access Control | n/a | RW/RO User | Granular RBAC | Granular RBAC
| Tenant Isolation | Shared | Shared | Shared | Dedicated
| VPC Link & IP filtering | No | No | No | Yes
| Encryption Key Management | Neo4j managed | Neo4j managed | No | No
| View and edit billing information | {check-mark} | | add
|===

== AuraDB Free

AuraDB Free is our introductory level offering, providing full, unlimited access to all of Aura’s standard features. 
It provides a strong balance between features, level of support, and cost.
For small development projects, learning, experimentation, and prototyping.

== AuraDB Professional

For medium-scale applications in advanced development or production environments.

== AuraDB MTE

* The architecture for MTE positions private low level infrastructure (Kubernetes Pods) on a shared compute resource (Kubernetes Node) to achieve multi-tenancy. 
* The Kubernetes Pods have a private persistent volume attached to them in a 1:1 relationship. 
* This relationship provides a layer of security as the data residing on the volume can only be accessed from a specific Kubernetes Pod. 

=== MTE is for:



=== MTE is not for:

* Organisations with strict data segregation requirements that mandate physical isolation to preserve data integrity, or that require compliance with FedRAMP.  
* Organisations that need to use highly customised features that are not suited to a multi-tenant environment, such as custom procedures.


== AuraDB Enterprise

* Where a customer is guaranteed resource isolation. 
* Orchestras are expensive to run, especially so in a single tenant architecture, therefore AuraDB Enterprise has premium pricing.


=== AuraDB Enterprise is for:

* For large-scale, mission-critical applications that require advanced security and 24x7 support.
* Organisations that require the highest level of uptime SLA.