[[aura-user-management]]
= User management
:description: This page describes how to manage users in Neo4j Aura.

label:AuraDB-Enterprise[] label:AuraDS-Enterprise[]

User management is a feature within Aura that allows you to invite users and set their roles within an isolated environment.

== Tenants

Tenants are the primary mechanism for granting users access to an Aura environment.

The tenant you're currently viewing is displayed in the header of the Console. 
You can select the tenant name to open the tenant dropdown menu, allowing you to view all the tenants that you have access to and switch between them.

Additionally, you can perform the following actions from the tenant dropdown menu:

* Copy the _Tenant ID_ of any tenant in the list by selecting the clipboard icon that appears when you hover over the tenant.
* Edit the name of the tenant you are currently viewing by selecting the pencil icon next to the tenant. This action requires you to be an _Admin_ of the tenant.

== Team members

Each tenant consists of a single team that allows multiple users with individual accounts to access the same environment.

The team and its members can be viewed and managed from the **Team Members** page. 
You can access the **Team Members** page by selecting **Team Members** from the sidebar menu of the Console.

=== Roles

Users within a team can be assigned one of the following roles:

* _Admin_
* _Member_
* _Viewer_

:check-mark: icon:check[]

.Roles
[opts="header",cols="3,1,1,1"]
|===
| Capability | Admin | Member | Viewer
| View team members and their roles | {check-mark} | {check-mark} | {check-mark}
| View and open instances | {check-mark} | {check-mark} | {check-mark}
| Perform all actions on instances footnote:[Actions include creating, deleting, pausing, resuming, and editing instances.] | {check-mark} | {check-mark} |
| Clone data to new and existing instances | {check-mark} | {check-mark} |
| Take on-demand snapshots | {check-mark} | {check-mark} |
| Restore from snapshots | {check-mark} | {check-mark} |
| Edit the tenant name | {check-mark} | |
| Invite new users to the team | {check-mark} | |
| Edit existing team members' roles | {check-mark} | |
| Delete existing team members from the team | {check-mark} | |
| View and edit billing information | {check-mark} | |
|===

[NOTE]
====
Each team must have at least one _Admin_, but it is also possible for teams to have multiple _Admins_.
====

=== Inviting team members

As an _Admin_, to invite a new team member:

. Select **Invite member** from the **Team Members** page.
. Enter the **Email** address of the person you want to invite.
. Select the team member's **Role**.
. Select **Invite**.

The new team member will appear within the list of team members on the **Team Members** page with the _Pending invite_ **Status** until they accept the invite.

An email will be sent to the team member with a link to accept the invite.

=== Editing team members

As an _Admin_, to edit an existing team member's role:

. Select the **Edit member** pencil icon next to the team member's name from the **Team Members** page.
. Select the team member's new **Role**.
. Select **Save changes**.

=== Deleting team members

As an _Admin_, to delete an existing team member from the team:

. Select the **Delete member** trash can icon next to the team member's name from the **Team Members** page.
. Select **Delete**.

[NOTE]
====
It is also possible to delete a team member whose **Status** is _Pending invite_.

Select the **Delete member** trash can icon next to the team member's name, and then select **Revoke**.
====

=== Accepting an invite

When invited to a team, you will receive an email with a link to accept the invite. 
This link will direct you to the Aura Console, where a **Tenant invitation** modal will appear.
You can select the tenant(s) you have been invited to and choose to accept or decline the invite(s). 

You can also close the **Tenant invitation** modal without accepting or declining the invite(s) and later manually re-open the modal by selecting the **Pending invites** envelope icon in the Console header.

[TIP]
====
User management within the Aura Console does not replace built-in roles or fine-grained RBAC at the database level. 
====
