[[aura-user-management]]
= User management
:description: This page describes how to manage users in Neo4j Aura.
:page-aliases: user-management.adoc

User management is a feature within Aura that allows you to invite users and set their roles within an isolated environment.

== Projects

Projects are the primary mechanism for granting users access to an Aura environment.

The project you're currently viewing is displayed in the header of the Console.
You can select the project name to open the project dropdown menu, allowing you to view all the projects that you have access to and switch between them.

Additionally, you can perform the following actions from the project dropdown menu:

* Copy the _Project ID_ of any project in the list by selecting the clipboard icon that appears when you hover over the project.
* Edit the name of the project you are currently viewing by selecting the pencil icon next to the project.
This action requires you to be an _Admin_ of the project.

== Users

Each project can have multiple users with individual accounts allowing access to the same environment.

The users with access to a project can be viewed and managed from the **User Management** page.
You can access the **User Management** page by selecting **User Management** from the sidebar menu of the Console.

=== Roles

Users within a project can be assigned one of the following roles:

* _Admin_
* _Member_
* _Viewer_

:check-mark: icon:check[]

.Roles
[opts="header",cols="3,1,1,1"]
|===
| Capability | Admin | Member | Viewer
| View users and their roles | {check-mark} | {check-mark} | {check-mark}
| View and open instances | {check-mark} | {check-mark} | {check-mark}
| Access the Neo4j Customer Support Portal | {check-mark} | {check-mark} | {check-mark}
| Perform all actions on instances footnote:[Actions include creating, deleting, pausing, resuming, and editing instances.] | {check-mark} | {check-mark} |
| Clone data to new and existing instances | {check-mark} | {check-mark} |
| Take on-demand snapshots | {check-mark} | {check-mark} |
| Restore from snapshots | {check-mark} | {check-mark} |
| Edit the project name | {check-mark} | |
| Invite new users to the project | {check-mark} | |
| Edit existing users' roles | {check-mark} | |
| Delete existing users from the project | {check-mark} | |
| View and edit billing information | {check-mark} | |
|===

[NOTE]
====
Each project must have at least one _Admin_, but it is also possible for projects to have multiple _Admins_.
====

=== Inviting users

As an _Admin_, to invite a new user:

. Select **Invite user** from the **User Management** page.
. Enter the **Email** address of the person you want to invite.
. Select the user's **Role**.
. Select **Invite**.

The new user will appear within the list of users on the **User Management** page with the _Pending invite_ **Status** until they accept the invite.

An email will be sent to the user with a link to accept the invite.

=== Editing users

As an _Admin_, to edit an existing user's role:

. Select the pencil icon next to the user's name from the **User Management** page.
. Select the user's new **Role**.
. Select **Save changes**.

=== Deleting users

As an _Admin_, to delete an existing user:

. Select the trash can icon next to the user's name from the **User Management** page.
. Select **Delete**.

[NOTE]
====
It is also possible to delete a user whose **Status** is _Pending invite_.

Select the trash can icon next to the user's name, and then select **Revoke**.
====

=== Accepting an invite

When invited to a project, you receive an email with a link to accept the invite.
This link directs you to the Aura Console, where a **Project invitation** modal will appear.
You can select the projects you have been invited to and accept or decline the invites.

You can also close the **Project invitation** modal without accepting or declining the invites and later manually re-open the modal by selecting the **Pending invites** envelope icon in the Console header.

[TIP]
====
User management within the Aura Console does not replace built-in roles or fine-grained RBAC at the database level.
====
