= Security
:description: This section covers important security aspects in Neo4j.

This section of documentation describes how to ensure security according to industry best practices.

Neo4j Aura is available on multiple commercial cloud service
providers and in multiple regions.
As with any modern cloud service, Neo4j Aura, the provider and customers share responsibility for using the service securely.

* The foundational layer is the cloud infrastructure that the service runs on. 
By utilizing cloud infrastructure providers, Neo4j Aura can rely on uptime and reliability in the building blocks that make up the infrastructure.
* The middle layer is the Neo4j Aura service itself, delivering graph database services to customers around the world. 
* The top layer is the customer, including user interaction and configuration. 

Authentication and authorization are designed to ensure the principle of least privilege at every stage of hosting and maintaining Neo4j Aura.

For more information, visit https://trust.neo4j.com to learn about Neo4j Aura's security posture and request access to additional security documentation.