= Multi-Factor Authentication 

Multi-Factor Authentication (MFA) adds an extra layer of security to your Neo4j Aura account by requiring a one-time passcode (OTP) in addition to your password.

There's two scenarios for MFA:

* Individual users can enable MFA for their own accounts (e.g. if you have a personal Neo4j Aura account)
* Organization administrators can enable MFA for an entire organization, then it's mandatory for all members to go through the MFA setup

Use any of the following apps to generate one-time codes:

* Authy
* Google Authenticator
* Auth0 Guardian
* Microsoft Authenticator

== Enable MFA as a user via account settings 

[IMPORTANT]
====
To enable MFA, you must log in using email and password, not Google login or SSO.
====

. Log in to the Aura Console using your email/password.
. Go to *Account > Settings > Preferences > Security*.
. In the *Multi-Factor Authentication (MFA)* section toggle *MFA ON*.
. You will be logged out automatically.
. Log back in with your email and password.
. A setup modal appears with a QR code.
. Open your authenticator app and *scan the QR code*.
. Enter the *one-time code* from the app to verify.
. *Save your recovery code* somewhere secure.

==  Enable MFA for your organization (Admins)

* `Organization Owners` or `Organization Admins` can enable MFA that applies to all members of the organization.
* Members must log in using email and password. MFA setup is not supported for accounts authenticated through SSO or Google OAuth.

=== To require MFA for all organization members:

. Go to *Account > Settings > Preferences > Security*.
. In the *Multi-Factor Authentication (MFA)* section toggle *Enable*.

==== Member steps to complete MFA setup:

. Organization members will see the message, "_Your organization has required Multi Factor Authentication (MFA). Clicking enable MFA below will log you out and you will then need to login using your email and password to configure MFA._"
. They need to click on"Enable" to be logged out and on login will be presented with:
. A setup modal appears with a QR code.
. Open their authenticator app and scan the QR code.
. Enter the one-time code from the app to verify.
. Save their recovery code somewhere secure.














