= Private links on VDC (cloud-agnostic)

label:AuraDB-Virtual-Dedicated-Cloud[]

This private link section is cloud-agnostic and therefore applicable to all clouds.
A private link provides secure network connectivity between your application and AuraDB without exposing traffic to the public internet.

The term “private link” refers to:

* Private Service Connect = Google Cloud platform
* PrivateLink = AWS
* Private Link = Azure

The following steps explain the process of establishing a private link connection to securely connect your application to an AuraDB Virtual Dedicated Cloud environment.

[NOTE]
======
The dbid: abcd1234 and orch-id: 0000 are used in this example.
These are different in your AuraDB Virtual Dedicated Cloud environment.
======

. The application initializes a driver connection to neo4j+s://abcd1234.production-orch-0000.neo4j.io.
. The network layer then queries the DNS server to resolve the fully qualified domain name (FQDN) (in this case, abcd1234.production-orch-0000.neo4j.io) to its corresponding IP address.
. The Cloud Virtual Network private DNS is queried, and it resolves the FQDN to 10.10.10.10, based on the wildcard DNS A record created: *.production-orch-0000.neo4j.io -> 10.10.10.10
. The application's connection is directed to 10.10.10.10, which is the private link endpoint.
From there, the private link endpoint forwards the network connection to the private ingress through the private link.
. The private ingress extracts the dbid from the FQDN and directs the connection to the appropriate Aura instance (dbid: abcd1234).
. The Aura instance responds by sending the Neo4j cluster routing table back to the application, which contains information about the instances and their roles.
. Based on the type of transaction (read or write) the driver selects an appropriate instance to execute a read or write transaction. The code has the ability to direct the transaction to the appropriate instances this way.
. Similar to before, the Cloud Virtual Network private DNS is queried and resolves the FQDN to 10.10.10.10. The application's connection is sent to the private link endpoint (10.10.10.10), which forwards the network connection to the private ingress through the private link.
The private ingress then directs the connection to the Aura instance with dbid: abcd1234.
. Finally, the write transaction is received and executed within the Aura instance with dbid: abcd1234.

.Available instances and their roles
[cols="1,1"]
|===
|abcd1234.production-orch-0000.neo4j.io
|role: write

|abcd1234.production-orch-0000.neo4j.io
|role: read

|abcd1234.production-orch-0000.neo4j.io
|role: read
|===

=== Custom endpoints with private link

In addition to the production-orch-<orch>.neo4j.io DNS records configured for your private link databases, you must add the following records in order for a Custom Endpoint assigned to a Private Link database to work.
When configuring a custom endpoint with a URI like `my-endpoint-abcdef-123456.endpoints.neo4j.io`, you must add the following DNS records for the custom endpoint to function properly:

[source,bash]
----
my-endpoint-abcdef-123456.endpoints.neo4j.io IN A <ip-address-of-your-endpoint>
a-my-endpoint-abcdef-123456.endpoints.neo4j.io IN A <ip-address-of-your-endpoint>
b-my-endpoint-abcdef-123456.endpoints.neo4j.io IN A <ip-address-of-your-endpoint>
c-my-endpoint-abcdef-123456.endpoints.neo4j.io IN A <ip-address-of-your-endpoint>
d-my-endpoint-abcdef-123456.endpoints.neo4j.io IN A <ip-address-of-your-endpoint>
----

*Alternative wildcard approach*

Instead of adding individual records for a custom endpoint, it is possible to use a wildcard:

[source,bash]
----
*.endpoints.neo4j.io IN A <ip-address-of-your-endpoint>
----

This would automatically cover any custom endpoint created for that region.
Note that similarly to the individual records, this wildcard record must also be added in addition to the `production-orch-<orch>.neo4j.io` DNS records as mentioned above.

[IMPORTANT]
====
If users have regions with different private link endpoints, but have linked those endpoints to one client VPC , then the wildcard record would direct all traffic for custom endpoints to only one region—whichever is associated with the IP address used in the DNS records.
This breaks routing for custom endpoints located in the other regions, and therefore, if you do not have a simple private link setup, it is recommended to use the individual custom endpoint records, rather than the wildcard.
====


== Test connectivity through the private endpoint

Use the `nslookup` command to confirm whether the Fully Qualified Domain Names (FQDNs) of your Aura instances are directed to the IP address of the PrivateLink endpoint (usually represented by an internal IP address, such as 10.0.0.0).

[source,bash]
----
nslookup <dbid>.production-orch-<orchestra>.neo4j.io
----

Use cURL from a VM instance or a container located in the related VPC network.

[source,bash]
----
curl  https://<dbid>.production-orch-<orchestra>.neo4j.io
----

Use nc commands on one of your VM instances or container located in the related GCP Project VPC network, and make sure you get a successful response for all commands

[source,bash]
----
nc -vz <dbid>.production-orch-<orchestra>.neo4j.io 443
nc -vz <dbid>.production-orch-<orchestra>.neo4j.io 7687
nc -vz <dbid>.production-orch-<orchestra>.neo4j.io 7474
# if you are using AuraDS
nc -vz <dbid>.production-orch-<orchestra>.neo4j.io 8491
----

On Windows, you can get https://nmap.org/download.html[Netcat] or use PowerShell

[source,bash]
----
Test-NetConnection <dbid>.production-orch-<orchestra>.neo4j.io -Port 7687
Test-NetConnection <dbid>.production-orch-<orchestra>.neo4j.io -Port 7474
Test-NetConnection <dbid>.production-orch-<orchestra>.neo4j.io -Port 443
# if you are using AuraDS
Test-NetConnection <dbid>.production-orch-<orchestra>.neo4j.io -Port 8491
----
