[[aura-backup-restore-export]]
= Backup, export and restore
:description: This page describes how to backup, export and restore your data from a snapshot.

The data in your AuraDB instance can be backed up, exported, and restored using snapshots.

A snapshot is a copy of the data in an instance at a specific point in time.

The *Snapshots* tab within an AuraDB instance shows a list of available snapshots.

To access the *Snapshots* tab:

. Navigate to the https://console.neo4j.io/?product=aura-db[Neo4j Aura Console] in your browser.
. Select the instance you want to access.
. Select the *Snapshots* tab.

[NOTE]
====
Only the latest snapshot is available for Free instances.
Snapshots are available for 7 days for Professional instances, 30 days for Business Critical instances, and 60 days for AuraDB Virtual Dedicated Cloud instances.
====

== Snapshot types

=== Scheduled

label:AuraDB-Professional[]
label:AuraDB-Business-Critical[]
label:AuraDB-Virtual-Dedicated-Cloud[]

A *Scheduled* snapshot is a snapshot that is automatically triggered when you first create an instance, when changes to the underlying system occur (for example, a new patch release), and at a cadence depending on your plan type.

Scheduled snapshots are run automatically once a day for Professional instances and once an hour for Business Critical and Enterprise instances.

[NOTE]
====
For AuraDB Virtual Dedicated Cloud database instances running Neo4j v4.x, from day 0 to 7 scheduled snapshots run automatically once every 6 hours.
From day 8 to 60, snapshots run once a day.
====

=== On demand

An *On Demand* snapshot is a snapshot that you manually trigger by selecting *Take snapshot* from the *Snapshots* tab of an instance.

== Snapshot actions

=== Restore

[CAUTION]
====
Restoring a snapshot overwrites the data in your instance, replacing it with the data contained in the snapshot.
====

You can restore data in your instance to a previous snapshot by selecting *Restore* next to the snapshot you want to restore.

Restoring a snapshot requires you to confirm the action by typing RESTORE and selecting *Restore*.

=== Export and create

The ellipses (*...*) button next to an existing snapshot, allows you to:

* *Export* - Download the instance as *_.backup_* file, allowing you to store a local copy and work on your data offline.
(This applies to AuraDB v5 databases, for v4, the instances can be downloaded as *_.dump_* files.)
* *Create instance from snapshot* - Create a new AuraDB instance using the data from the snapshot.

[NOTE]
====
The ability to Export or Create an instance from a Scheduled Virtual Dedicated Cloud snapshot is limited to 14 days.

Additionally, for Virtual Dedicated Cloud instances running Neo4j version 5, the ability to export or create an instance from a Scheduled snapshot is limited to the first full snapshot, taken once per day.

Use the toggle **Show exportable only** on top of the list of snapshots to filter by whether a snapshot is exportable or not.
====

=== Security of backups and exported data

Neo4j Aura Enterprise automatically creates backups of each database at regular intervals.
Aura stores the data securely in encrypted and dedicated cloud storage buckets.
Backups are stored in the same Cloud Service Provider and region as the instance they are associated with.
Users access backups through the Aura console.

In the console, it's possible to:

* See a list of previous backups
* Choose to restore a backup
* Download a backup (which serves as the export mechanism)

== Retention periods

I AM ANGRY
UPDATE: 17:22 november 7 - it works
[cols="^,^,^,^,^,^"]
|===
| Tier | Aura version | Frequency of snapshots 2+| Scheduled snapshots| On-demand snapshot restorable and exportable days

| X | X | X | Restorable days | Exportable days | X

| AuraDB Free
| 4, 5
| N/A
| N/A
| N/A
| 30

| AuraDB Professional
| 4, 5
| Daily
| 30
| 7
| 30

| AuraDB Business Critical
| 5
| Hourly snapshots with one daily full snapshot *Note 1
| 30
| 7 (Daily snapshot only) *Note 3
| 30

| AuraDB Virtual Dedicated Cloud
| 4
| Every six hours
| 60 (Once per day; long retention)
| 14 (Once per day; long retention)
| 90

| | | | 7 (Other snapshots; short retention) *Note 2 | 7 (Other snapshots; short retention) *Note 2 | 

| BLLLL
| 5
| Hourly snapshots with one daily full snapshot *Note 1
| 60
| 14 (Daily snapshot only) *Note 3
| 90
|===

WORKING EXPLANATION

[cols="^,^,^,^,^,^"] /THIS WILL CENTER EVERY CELL
|===
| Tier | Aura version | Frequency of snapshots 2+| Scheduled snapshots| On-demand snapshot restorable and exportable days /THATS HOW YOU SPAN TWO CELLS

| X | X | X | Restorable days | Exportable days | X /THE REST MUST BE CLEAR

| AuraDB Free
| 4, 5
| N/A
| N/A
| N/A
| 30

| AuraDB Professional
| 4, 5
| Daily
| 30
| 7
| 30

| AuraDB Business Critical
| 5
| Hourly snapshots with one daily full snapshot *Note 1
| 30
| 7 (Daily snapshot only) *Note 3
| 30

| AuraDB Virtual Dedicated Cloud
| 4
| Every six hours
| 60 (Once per day; long retention)
| 14 (Once per day; long retention)
| 90

| | | | 7 (Other snapshots; short retention) *Note 2 | 7 (Other snapshots; short retention) *Note 2 | 

| BLLLL
| 5
| Hourly snapshots with one daily full snapshot *Note 1
| 60
| 14 (Daily snapshot only) *Note 3
| 90
|===