[[aura-backup-restore-export]]
= Backup, export and restore
:description: This page describes how to backup, export and restore your data from a snapshot.

The data in your AuraDB instance can be backed up, exported, and restored using snapshots.

A snapshot is a copy of the data in an instance at a specific point in time.

The *Snapshots* tab within an AuraDB instance shows a list of available snapshots.

To access the *Snapshots* tab:

. Navigate to the https://console.neo4j.io/?product=aura-db[Neo4j Aura Console] in your browser.
. Select the instance you want to access.
. Select the *Snapshots* tab.

[NOTE]
====
Only the latest snapshot is available for Free instances.
Snapshots are available for 7 days for Professional instances, 30 days for Business Critical instances, and 60 days for AuraDB Virtual Dedicated Cloud instances.
====

== Snapshot types

=== Scheduled

label:AuraDB-Professional[]
label:AuraDB-Business-Critical[]
label:AuraDB-Virtual-Dedicated-Cloud[]

A *Scheduled* snapshot is a snapshot that is automatically triggered when you first create an instance, when changes to the underlying system occur (for example, a new patch release), and at a cadence depending on your plan type.

Scheduled snapshots are run automatically once a day for Professional instances and once an hour for Business Critical and Enterprise instances.

[NOTE]
====
For AuraDB Virtual Dedicated Cloud database instances running Neo4j v4.x, from day 0 to 7 scheduled snapshots run automatically once every 6 hours.
From day 8 to 60, snapshots run once a day.
====

=== On demand

An *On Demand* snapshot is a snapshot that you manually trigger by selecting *Take snapshot* from the *Snapshots* tab of an instance.

== Snapshot actions

=== Restore

[CAUTION]
====
Restoring a snapshot overwrites the data in your instance, replacing it with the data contained in the snapshot.
====

You can restore data in your instance to a previous snapshot by selecting *Restore* next to the snapshot you want to restore.

Restoring a snapshot requires you to confirm the action by typing RESTORE and selecting *Restore*.

=== Export and create

The ellipses (*...*) button next to an existing snapshot, allows you to:

* *Export* - Download the instance as *_.backup_* file, allowing you to store a local copy and work on your data offline.
(This applies to AuraDB v5 databases, for v4, the instances can be downloaded as *_.dump_* files.)
* *Create instance from snapshot* - Create a new AuraDB instance using the data from the snapshot.

[NOTE]
====
The ability to Export or Create an instance from a Scheduled Virtual Dedicated Cloud snapshot is limited to 14 days.

Additionally, for Virtual Dedicated Cloud instances running Neo4j version 5, the ability to export or create an instance from a Scheduled snapshot is limited to the first full snapshot, taken once per day.

Use the toggle **Show exportable only** on top of the list of snapshots to filter by whether a snapshot is exportable or not.
====

=== Security of backups and exported data

Neo4j Aura Enterprise automatically creates backups of each database at regular intervals.
Aura stores the data securely in encrypted and dedicated cloud storage buckets.
Users access backups through the Aura console.
In the console, it's possible to:

* See a list of previous backups
* Choose to restore a backup
* Download a backup (which serves as the export mechanism)

== Retention periods

Add intro paragraph here!

Combine the Scheduled Snapshot columns?

.The current Neo4j Aura Snapshot retention periods by tier
[cols="1,1,1,1,1", options="header"]
|===
|Tier |Aura version |Scheduled Snapshots per day |Scheduled Snapshot restorable days
(exportable days) |On-Demand Snapshot restorable days
(exportable days)

| AuraDB Free
| 4, 5
| N/A
| N/A
| 30 days (30 days)

| AuraDB Professional
| 4, 5
| Full retention: 1
| 30 days (7 days)
| 30 days (30 days)

| AuraDB Business Critical
| 5
| Full: 1, Differential: 23 footnote:differential[Differential backups contain new data since the last backup. They are not exportable, but they are restorable for the full duration.]
| 30 days (7 days)
| 30 days (30 days)

.2+| AuraDB Virtual Dedicated Cloud
| 4
| Full retention: 1,
Short retention: 3 footnote:shortretention[Short retentions backups are the same as full backups, only with a shorter lifespan. (only 1 of the six-hourly snapshot for VDC v4 DBs are available for 60 days (exportable for 14 days), the rest are only available and exportable for 7 days.)] 
| Full retention: 60 (14), Short retention: 7 (7) footnote:shortretention[]
| 90 days (90 days)

| 5
| Full: 1, Diferential: 23 footnote:differential[]
| Full: 60 (14), Differential: 60 (N/A)
| 90 days (90 days)

| 5
| Full: 1
| Full: 16 days (7 days)
| 180 days (180 days)
|===

== Retention periods

The following table outlines the snapshot retention periods for different tiers of Neo4j Aura. Snapshots are automated backups that can be used to restore databases to a specific point in time, offering a safety net against data loss. Depending on the AuraDB tier and version, the frequency of snapshots and the duration for which they are retained and exportable vary. This guide provides details on how long snapshots remain restorable and exportable, helping you choose the best plan for your data recovery needs.


.The current Neo4j Aura Snapshot retention periods by tier
[cols="1,1,1,1", options="header"]
|===
| Tier | Aura version | Snapshot frequency | Restorable days (Exportable days)

| AuraDB Free
| 4, 5
| N/A
| 30 days (30 days)

| AuraDB Professional
| 4, 5
| Daily: 1
| 30 days (7 days)

| AuraDB Business Critical
| 5
| Daily: 1, Differential: 23 footnote:differential[Differential backups contain new data since the last backup. They are not exportable, but they are restorable for the full duration.]
| 30 days (7 days)

.2+| AuraDB Virtual Dedicated Cloud
| 4
| Daily: 1, Six-hourly: 3 footnote:sixhourly[Only 1 of the six-hourly snapshots is available for 60 days (exportable for 14 days), while the remaining snapshots are available and exportable for 7 days.]
| 60 days (14 days), 7 days (7 days)

| 5
| Daily: 1, Differential: 23 footnote:differential[]
| 60 days (14 days), Differential: 60 days (N/A)

| 5
| Daily: 1
| 16 days (7 days)
| 180 days (180 days)
|===




= Push to cloud

The `neo4j-admin push-to-cloud` command uploads a database or a dump into a Neo4j Aura instance. +

[NOTE]
====
To upload a 4.3 database in Aura, first upgrade it to 4.4 and then use the `neo4j-admin push-to-cloud command`.
====

The following table shows the compatibility between the dump version that you want to upload and the version of the Neo4j Aura instance.
