[[aura-db-actions]]
= Instance actions
:description: This page describes the following instance actions - rename, resest, upgrade, resize, pause, resume, clone to a new database, clone to an existing database, or delete and instance.

You can perform several instance actions from an AuraDB instance card on the https://console.neo4j.io/?product=aura-db[Neo4j Aura Console] homepage.

== Rename an instance

You can change the name of an existing instance using the *Rename* action.

To rename an instance:

. Select the ellipsis (*...*) button on the instance you want to rename.
. Select *Rename* from the resulting menu.
. Enter a new name for the instance.
. Select *Rename*.

== Reset an instance

label:AuraDB-Free[]
label:AuraDB-Professional[]

You can clear all data in an instance using the *Reset to blank* action.

To reset an instance:

. Select the ellipsis (*...*) button on the instance you want to reset.
. Select *Reset to blank* from the resulting menu.
. Select *Reset*.

== Upgrade an instance

=== Upgrade from Free to Professional

You can upgrade an AuraDB Free instance to an AuraDB Professional instance using the *Upgrade to Professional* action.

Upgrading your instance clones your Free instance data to a new Professional instance, leaving your existing Free instance untouched.

To upgrade a Free instance:

. Select the ellipsis (*...*) button on the free instance you want to upgrade.
. Select *Upgrade to Professional* from the resulting menu.
. Set your desired settings for the new instance. For more information on AuraDB instance creation settings, see xref:auradb/getting-started/create-database.adoc[].
. Tick the *I understand* checkbox and select *Upgrade Instance*.

=== Upgrade from Professional to Business Critical

You can upgrade an AuraDB Professional instance to an AuraDB Business Critical instance using the *Upgrade to Business Critical* action.

Upgrading your instance clones your Professional instance data to a new Business Critical instance, leaving your existing Professional instance untouched.

To upgrade a Business Critical instance:

. Select the ellipsis (*...*) button on the free instance you want to upgrade.
. Select *Upgrade to Business Critical* from the resulting menu.
. Set your desired settings for the new instance. For more information on AuraDB instance creation settings, see xref:auradb/getting-started/create-database.adoc[].
. Tick the *I understand* checkbox and select *Upgrade Instance*.

== Resize an instance

label:AuraDB-Professional[]
label:AuraDB-Enterprise[]
label:AuraDB-Business-Critical[]

You can change the size of an existing instance using the *Resize* action.

To resize an instance:

. Select the ellipsis (*...*) button on the instance you want to resize.
. Select *Resize* from the resulting menu.
. Select the new size you want your instance to be.
. Tick the *I understand* checkbox and select *Upgrade instance*.

An instance remains available during the resize operation.

== Pause an instance

label:AuraDB-Professional[]
label:AuraDB-Enterprise[]
label:AuraDB-Business-Critical[]

[NOTE]
====
You cannot manually pause an AuraDB Free instance; they are paused automatically after 72 hours of inactivity. footnote:[Inactivity is when you perform no queries on the instance.]
====

You can pause an instance when not needed and resume it at any time.

To pause an instance:

. Select the pause button on the instance you want to pause.
. Tick the *I understand* checkbox and select *Pause* to confirm.

After confirming, the instance begins pausing, and a play button replaces the pause button.

[NOTE]
====
Paused instances run at a discounted rate compared to standard consumption, as outlined in the confirmation window.
You can pause an instance for up to 30 days, after which point AuraDB automatically resumes the instance.
====

=== Resume a paused instance

To resume an instance:

. Select the play button on the instance you want to pause.
. Tick the *I understand* checkbox and select *Resume* to confirm.

After confirming, the instance begins resuming, which may take a few minutes.

[WARNING]
====
AuraDB Free instances do not automatically resume after 30 days. If an AuraDB Free instance remains paused for more than 30 days, Aura deletes the instance, and all information is lost.
====

== Clone an instance

You can clone an existing instance to create a new instance with the same data.
You can clone across regions, from AuraDB to AuraDS and vice versa, and from Neo4j version 4 to Neo4j version 5.

There are four options to clone an instance:

* Clone to a new AuraDB instance
* Clone to an existing AuraDB instance
* Clone to a new AuraDS database
* Clone to an existing AuraDS database

You can access all the cloning options from the ellipsis (*...*) button on the AuraDB instance.

[NOTE]
====
You cannot clone from a Neo4j version 5 instance to a Neo4j version 4 instance.
====

=== Clone to a new AuraDB instance

. Select the ellipsis (*...*) button on the instance you want to clone.
. Select *Clone To New* and then *AuraDB Professional/Business Critical/Enterprise* from the contextual menu.
. Set your desired settings for the new database. For more information on AuraDB database creation, see xref:auradb/getting-started/create-database.adoc[].
. Check the *I understand* box and select *Clone Database*.
+
[WARNING]
====
Make sure that the username and password are stored safely before continuing.
Credentials cannot be recovered afterwards.
====

=== Clone to an existing AuraDB instance

When you clone an instance to an existing instance, the database connection URI stays the same, but the data is replaced with the data from the cloned instance.

[WARNING]
====
Cloning into an existing instance will replace all existing data.
If you want to keep the current data, take a snapshot and export it.
====

. Select the ellipsis (*...*) button on the instance you want to clone.
. Select *Clone To Existing* and then *AuraDB* from the contextual menu.
. If necessary, change the database name.
. Select the existing AuraDB database to clone to from the dropdown menu.
+
[NOTE]
====
Existing instances that are not large enough to clone into will not be available for selection.
In the dropdown menu, they will be grayed out and have the string `(Instance is not large enough to clone into)` appended to their name.
====
+
. Check the *I understand* box and select *Clone*.

=== Clone to a new AuraDS instance

. Select the ellipsis (*...*) button on the instance you want to clone.
. Select *Clone To New* and then *AuraDS* from the contextual menu.
. Set the desired name for the new instance.
. Check the *I understand* box and select *Clone Instance*.
+
[WARNING]
====
Make sure that the username and password are stored safely before continuing.
Credentials cannot be recovered afterwards.
====

=== Clone to an existing AuraDS instance

When you clone an instance to an existing instance, the database connection URI stays the same, but the data is replaced with the data from the cloned instance.

[WARNING]
====
Cloning into an existing instance will replace all existing data.
If you want to keep the current data, take a snapshot and export it.
====

. Select the ellipsis (*...*) button on the instance you want to clone.
. Select *Clone To Existing* and then *AuraDS* from the contextual menu.
. If necessary, change the instance name.
. Select the existing AuraDS instance to clone to from the dropdown menu.
+
[NOTE]
====
Existing instances that are not large enough to clone into will not be available for selection.
In the dropdown menu, they are grayed out and have the string `(Instance is not large enough to clone into)` appended to their name.
====
+
. Tick the *I understand* checkbox and select *Clone*.


== Delete an instance

You can delete an instance if you no longer want to be billed for it.

To delete an instance:

. Select the red trashcan icon on the instance you want to delete.
. Type the exact name of the instance (as instructed) to confirm your decision, and select *Destroy*.

[WARNING]
====
There is no way to recover data from a deleted AuraDB instance.
====
