[[aura-read-only-secondaries]]
= Read-only secondaries

label:EAP[]

Available for all clouds (AWS, Azure & GCP)

Read-only secondaries serve those with a need for high READ queries (e.g. for analytics companies making recommendations that are giving people recommendations, and using less WRITE actions than READ actions).

Read-only secondaries make it speedy to read from the database, if a system is using READ & WRITE, if there’s lots of READ queries, using read-only secondaries means that in high read projects there's no bottlenecks, and companies can do more reads batch processing.

The introduction of secondaries in Aura expands Neo4j's capabilities by enabling additional read-only database instances for horizontal scaling (adding additional machines to an infrastructure, to adapt to increased demand) and enhanced cluster resilience. 

With secondaries, users can scale the READ capacity of their clusters, paving the way for improved support for READ-intensive use cases. 
These secondary instances configurable via the Aura console and API, where they can be launched, managed, or terminated.

* Up to 15 static Read-Only Secondaries can be added per AuraDB Enterprise database instance.
* Single region only. 
* Read-only secondaries available in same region as their Primary database.

== Routing policy

The following routing policy will apply when at least one secondary is available: 

Route READ to secondaries + non-leader primaries. This policy extends the READ payload to the primaries that are not currently serving in an elected leader role. It allows to further balance the READ and improve scalability

We will not support use cases for isolated workloads (customer routing) or multi region replication.

//

Secondaries are orchestrated to maintain availability and balanced distribution across availability zones, ensuring optimal performance and cost efficiency. 

== Console UI - Create Secondaries

Once this feature is enabled for your tenant you will see Secondary count set to Zero, and the ability to Edit secondaries in UI of the DB Overview and Details tile. * change grammar tense *

== Aura Provisioning API - simple request 

Once enabled for the user’s tenant a GET instance details call will show secondary count

[source]
----

GET/instances/{instanceId]{
  "data": {
    "cloud_provider": "azure",
    "connection_url": "neo4j+s://xxxxxx.databases.neo4j.io",
    "id": "xxxxxx",
    "memory": "2GB",
    "name": "Neo4j",
    "region": "uk south",
    "secondaries_count": 0,
    "status": "running",
    "storage": "4GB",
    "tenant_id": "XXXXXXXXXXXXXXXXXXXX",
    "type": "enterprise-db"
  }
}

----

PATCH/instances/{instanceId]
{
  "secondaries_count": 2
}'


[source]
----

A simple Secondaries count patch request will request update {
  "data": {
    "cloud_provider": "azure",
    "connection_url": "neo4j+s://xxxxxx.databases.neo4j.io",
    "id": "xxxxxx",
    "memory": "2GB",
    "name": "Neo4j",
    "region": "uk south",
    "secondaries_count": 2,
    "status": "running",
    "storage": "4GB",
    "tenant_id": "XXXXXXXXXXXXXXXXXXXXX",
    "type": "enterprise-db"
  }
}



