= Working with AuraDB tenants
:description: Work with AuraDB tenants in the Neo4j Aura command line interface.

[NOTE]
====
The Aura CLI makes heavy use of console commands containing the keyword "tenant".
To be consistent with that, all Aura CLI documentation pages use the term "tenant", which other parts of the documentation refer to as "project" instead.
====

Aura CLI allows you to list the Aura tenants you can access and then obtain the available AuraDB instance for each one.
To list the tenants:

[source, shell]
----
aura-cli tenant list
----

To get available AuraDB instances for an individual tenant, change `TENANT-ID` to the one you are interested in.
The output is substantial as all available AuraDB instance configurations are returned.
Consider filtering the output, for example by using the link:https://jqlang.org/[jq] utility.

[source, shell]
----
aura-cli tenant get TENANT-ID 
----

If you have a single tenant or one that you use most frequently, it is recommended that you set it as the default to avoid repetition with other Aura CLI commands.
Do this with:

[source, shell]
----
aura-cli config set default-tenant TENANT-ID 
----