= Aura CLI
:description: A guide to the Neo4j Aura command line interface.

[NOTE]
====
The Aura CLI makes heavy use of console commands containing the keyword `tenant`.
To be consistent with that, all Aura CLI documentation pages use the term "tenant", which other parts of the documentation refer to as "project" instead, which is the xref:new-console.adoc#_topology[topological evolution] of "tenant".
====

The Neo4j Aura Command Line Interface (CLI) is a powerful tool designed to simplify and streamline the management of your Neo4j Aura resources from the command line.
Neo4j Aura CLI can be used to provision new databases as well as scaling existing ones.
It offers flexibility, speed, and efficiency, and is suitable for both developers and operations teams.
Built with ease of use in mind, this CLI bridges the gap between automation and hands-on control, enabling you to integrate Neo4j Aura seamlessly into your workflows.


== Feedback

Report feedback via link:https://github.com/neo4j/aura-cli/issues[GitHub issues].
This covers requested enhancements, defects that you may encounter and general feedback.