= Initial configuration
:description: First configuration of the Neo4j Aura command line interface.

[NOTE]
====
The Aura CLI makes heavy use of console commands containing the keyword `tenant`.
To be consistent with that, all Aura CLI documentation pages use the term "tenant", which other parts of the documentation refer to as "project" instead, which is the topological evolution of "tenant".
====

== Obtain an Aura API Key

Follow the steps in xref:api/authentication.adoc#_creating_credentials[Creating Credentials]

[NOTE]
====
You must have payment information in your account to access this functionality.
This also applies to Aura Free.
====

== Configure the Aura CLI with an Aura API key

Configure the Aura CLI with the Aura API client ID and client secret you obtained earlier.
The Aura CLI refers to these as "credentials".
You can have several sets of credentials and select which one to use.

. At the command prompt, enter the following, using your own values:
+
[source, shell]
----
aura-cli credential add --name YOUR\_LABEL --client-id YOUR\_CLIENT\_ID --client-secret YOUR\_CLIENT\_SECRET
----
+
. To confirm the credentials are working, list your Aura instances:
+
[source, shell]
----
aura-cli instance list --output table
----