[[aura-monitoring]]
= Advanced metrics

label:AuraDS-Enterprise[]

Advanced metrics is a feature that enables access to a broad range of different instance and database metrics.

To access *Advanced metrics*:

. Navigate to the https://console.neo4j.io/?product=aura-db[Neo4j Aura Console] in your browser.
. Select the instance you want to access.
. Select the *Metrics* tab.
. Select the *Advanced metrics* button.

The presented metrics will be laid out across three tabs according to their category:

* *Resources* - Overall system resources, such as CPU, RAM and disk usage.
* *Instance* - Information about the Neo4j instance(s) running the database.
* *Database* - Metrics concerning the database itself, such as usage statistics and entity counts.

When viewing metrics, you can select from the following time intervals:

* 30 minutes
* 6 hours
* 24 hours
* 3 days
* 7 days
* 14 days
* 30 days

== Chart interactions

[NOTE]
====
Memory and storage charts can be toggled between absolute and relative values using the *%* toggle.
====

=== Zoom

To zoom in to a narrower time interval, select and drag inside any chart to select your desired time interval. The data will automatically update to match the increased resolution.

To reset zoom, double-click anywhere inside the chart or use the option in the context menu.

=== Expand

Any chart can be expanded to take up all the available screen estate by clicking the *expand* button (shown as two opposing arrows). To exit this mode, click the *x* button on the expanded view.

=== Context menu

To access the chart context menu, select the *...* button on any chart.

* *More info* - Selecting *More info* brings up an explanation of the particular metric. For some metrics it also provides hints about possible actions to take if that metric falls outside the expected range.

* *Reset zoom* - If the zoom level has been altered by selecting and dragging across a chart, *Reset zoom* resets the zoom back to the selected interval.
