[[aurads-backup-restore-export]]
= Backup, export, and restore
:description: This page describes how to backup, export and restore your data from a snapshot.

The data in your AuraDS instance can be backed up, exported, and restored using _snapshots_.
A snapshot is a copy of the data in an instance at a specific point in time.

The *Snapshots* tab within an AuraDS instance shows a list of available snapshots.
To access the *Snapshots* tab:

. Navigate to the https://console.neo4j.io/?product=aura-ds[Neo4j Aura Console^] in your browser.
. Select the instance you want to access.
. Select the *Snapshots* tab.

== Snapshot types

There are two different types of snapshot:

* *Scheduled* - Runs when you first create an instance, when changes to the underlying system occur (for example, a new patch release), and automatically once a day.
* *On-demand* - Runs when you select *Take snapshot* from the *Snapshots* tab of an instance.

== Snapshot actions

=== Take a snapshot

You can manually trigger an *On-demand* snapshot by selecting *Take snapshot* in the *Snapshots* tab.
The snapshot status is shown as `In progress` until the snapshot has been created; then, the `Status` becomes `Completed`.

=== Restore

You can restore data in your instance to a previous snapshot by selecting *Restore* next to the snapshot you want to restore.

Restoring a snapshot requires you to confirm the action by typing RESTORE and selecting *Restore*. 

[CAUTION]
====
Restoring a snapshot overwrites the data in your instance, replacing it with the data contained in the snapshot.
====

=== Backup and export

By selecting the ellipses (...) button next to a snapshot, you can:

* *Export* - Download the database as a compressed file, allowing you to store a local copy and work on your data offline.
The compressed archive contains a *_.dump_* file that can be imported directly or pushed to the cloud.
* *Create instance from snapshot* - Create a new AuraDS instance using the data from the snapshot.
This opens a window where you can assign a name to the instance that will be created.

== AuraDS retention periods

.The current Neo4j AuraDS Snapshot retention periods by tier
[cols="1,1,1,1,1", options="header"]
|===
|Tier |Aura version |Scheduled Snapshots per day |Scheduled Snapshot restorable days
(exportable days) |On-Demand Snapshot restorable days
(exportable days)

| AuraDS Professional
| 4, 5
| Full retention: 1
| 9 days (7 days)
| 180 days (180 days)

| AuraDS Enterprise
| 4, 5
| Full retention: 1
| Full retention: 16 days (7 days)
| 180 days (180 days)
|===
