[[aurads-backup-restore-export]]
= Backup, export and restore
:description: This page describes how to backup, export and restore your data from a snapshot.

The data in your AuraDS instance can be backed up, exported, and restored using _snapshots_.
A snapshot is a copy of the data in an instance at a specific point in time.

The *Snapshots* tab within an AuraDS instance shows a list of available snapshots.
To access the *Snapshots* tab:

. Navigate to the https://console.neo4j.io/?product=aura-ds[Neo4j Aura Console^] in your browser.
. Select the instance you want to access.
. Select the *Snapshots* tab.

== Snapshot types

There are two different types of snapshot:

* *Scheduled* - Runs when you first create an instance, when changes to the underlying system occur (for example, a new patch release), and automatically at a cadence depending on your plan type. 
Scheduled snapshots are run automatically once a day for Professional instances and once an hour for Enterprise instances.
* *On-demand* - Runs when you select *Take snapshot* from the *Snapshots* tab of an instance.

[NOTE]
====
_Scheduled_ daily snapshots are kept for 7 days for Professional instances and 14 days for Enterprise instances.
_On-demand_ snapshots are kept in the system for 180 days for all instances.
====

== Snapshot actions

=== Take a snapshot

You can manually trigger an *On-demand* snapshot by selecting *Take snapshot* in the *Snapshots* tab.
The snapshot status is shown as `In progress` until the snapshot has been created; then, the `Status` becomes `Completed`.

=== Backup and Export

By selecting the ellipses (...) button next to a snapshot, you can:

* *Export* - Download the database as a compressed file, allowing you to store a local copy and work on your data offline. The compressed archive contains a *_.dump_* file that can be imported directly or pushed to the cloud.
* *Create instance from snapshot* - Create a new AuraDS instance using the data from the snapshot. This opens a window where you can assign a name to the instance that will be created.

=== Restore

You can restore data in your instance to a previous snapshot by selecting *Restore* next to the snapshot you want to restore.

Restoring a snapshot requires you to confirm the action by typing RESTORE and selecting *Restore*. 

[CAUTION]
====
Restoring a snapshot overwrites the data in your instance, replacing it with the data contained in the snapshot.
====


