[[aurads-instance-actions]]
= Instance actions
:description: This page describes the available actions for an AuraDS instance.

You can perform several actions from an AuraDB instance card on the https://console.neo4j.io/[Neo4j Aura Console^] homepage.

== Renaming an instance

You can change the name of an existing instance by using the *Rename* action.

To rename an instance:

* Select the ellipsis (*...*) button on the database you want to rename.
* Select *Rename* from the resulting menu.
* Enter a new name for the instance.
* Select *Rename*.

== Resizing an instance

You can change the size of an existing instance by using the *Resize* action.

To resize an instance:

. Select the ellipsis (...) on the instance you want to resize.
. Select *Resize* from the resulting menu.
. Select the new size you want your instance to be.
. Tick the *I understand* checkbox and select *Submit*.

An instance becomes unavailable for a short period of time during the resize operation.

== Pausing an instance

You can pause an instance during periods where you don't need it and resume at any time.

To pause an instance:

. Navigate to the *SETTINGS* tab of the instance you want to pause.
. Select *Pause* below *Pause Instance*.
. Tick the *I understand* checkbox and select *Pause* to confirm.

After confirming, the instance will begin pausing, and a *Resume* button will replace the *Pause* button.

[NOTE]
====
Paused instances run at a discounted rate compared to standard consumption, as outlined in the confirmation window.
You can pause an instance for up to 30 days, after which point AuraDS automatically resumes the instance.
====

== Resuming an instance

[WARNING]
======
If an AuraDS instance remains paused for more than 90 days, it will be automatically resumed.
======

To resume an instance: 

. Navigate to the *SETTINGS* tab of the instance you want to resume.
. Select *Resume* below *Pause Instance*.
. Tick the *I understand* checkbox and select *Resume* to confirm.

After confirming, the instance will begin resuming, which may take a few minutes.

Alternatively, you can select the *Resume* button on the instance you want to resume directly from the https://console.neo4j.io/[Neo4j Aura Console].

== Cloning an instance

You can clone an existing instance into a new one using the *Clone* option.

To clone an instance:

. Navigate to the *SETTINGS* tab of the instance you want to clone.
. Select *Clone*.
. Set your desired name for the new instance.
. Tick the *I understand* checkbox and select *Clone Instance*.

== Deleting an instance

You can delete an instance if you no longer want to be billed for it.

To delete an instance:

. Navigate to the *SETTINGS* tab of the instance you want to remove.
. Select *Delete* below *Delete Instance*.
. Type the exact name of the instance (as instructed) to confirm your decision, and select *Destroy*.

[WARNING]
====
*Warning:*
There is no way to recover data from a deleted AuraDS instance.
====
