== Setup

[.tabbed-example]
====
[.include-with-GDS-client]
=====
For more information on how to get started using Python, refer to the xref:aurads/connecting/python.adoc[] tutorial.

[source, shell]
----
pip install graphdatascience
----

[source, python]
----
# Import the client
from graphdatascience import GraphDataScience

# Replace with the actual URI, username, and password
AURA_CONNECTION_URI = "neo4j+s://xxxxxxxx.databases.neo4j.io"
AURA_USERNAME = "neo4j"
AURA_PASSWORD = ""

# Configure the client with AuraDS-recommended settings
gds = GraphDataScience(
    AURA_CONNECTION_URI,
    auth=(AURA_USERNAME, AURA_PASSWORD),
    aura_ds=True
)
----

In the following code examples we use the `print` function to print Pandas `DataFrame` and `Series` objects. You can try different ways to print a Pandas object, for instance via the `to_string` and `to_json` methods; if you use a JSON representation, in some cases you may need to include a xref:aurads/connecting/python.adoc#_serializing_neo4j_datetime_in_json_dumps[default handler] to handle Neo4j `DateTime` objects. Check the xref:aurads/connecting/python.adoc#_running_a_query[Python connection] section for some examples.
=====

[.include-with-Cypher]
=====
For more information on how to get started using the Cypher Shell, refer to the xref:aurads/connecting/neo4j-applications.adoc#_neo4j_cypher_shell[Neo4j Cypher Shell] tutorial.

TIP: Run the following commands from the directory where the Cypher shell is installed.

[source, shell, subs=attributes+]
----
export AURA_CONNECTION_URI="neo4j+s://xxxxxxxx.databases.neo4j.io"
export AURA_USERNAME="neo4j"
export AURA_PASSWORD=""

./cypher-shell -a $AURA_CONNECTION_URI -u $AURA_USERNAME -p $AURA_PASSWORD
----
=====

[.include-with-python-driver]
=====
For more information on how to get started using Python, refer to the xref:aurads/connecting/python.adoc[] tutorial.

[source, shell]
----
pip install neo4j
----

[source, python]
----
# Import the driver
from neo4j import GraphDatabase

# Replace with the actual URI, username, and password
AURA_CONNECTION_URI = "neo4j+s://xxxxxxxx.databases.neo4j.io"
AURA_USERNAME = "neo4j"
AURA_PASSWORD = ""

# Instantiate the driver
driver = GraphDatabase.driver(
    AURA_CONNECTION_URI, 
    auth=(AURA_USERNAME, AURA_PASSWORD)
)
----

[source, python]
----
# Import to prettify results
import json

# Import for the JSON helper function
from neo4j.time import DateTime

# Helper function for serializing Neo4j DateTime in JSON dumps
def default(o):
    if isinstance(o, (DateTime)):
        return o.isoformat()
----
=====
====
