[[aura-connecting-overview]]
= Connecting applications
:description: This section covers how to use drivers and libraries to connect your application to AuraDB.
:page-aliases: connecting-applications/overview.adoc

You can use the official link:{neo4j-docs-base-uri}/create-applications/[drivers and libraries] provided by Neo4j to connect your application to AuraDB using a variety of programming languages.

Regardless of what language you use, you will need to provide the following information to connect to an AuraDB instance:

* `uri` - The *Connection URI* for your AuraDB instance.
You can copy this from the instance card or details page in the Console.
* `username` and `password` - The *Username* and *Password* for your AuraDB instance.
You can copy or download these during the instance creation process.

== Change data capture

Change Data Capture (CDC) allows you to capture and track changes to your database in real-time, enabling you to keep your other data sources up to date with Neo4j. 
With CDC, you can identify and respond to changes (create, update, and delete) on nodes and relationships as they happen, and integrate these changes into other systems and applications.

See link:{neo4j-docs-base-uri}/cdc/enablecdc/aura[] for more information about setting up CDC, configuring it to capture the changes, and querying those changes for further processing, such as replicating to another system.