[[aurads-access-database]]
= Accessing a database
:description: This page describes how to access a database using Neo4j AuraDS.

With a database created, the next step is to access it.

There are a few different methods of accessing a database in Neo4j AuraDS:

* <<_neo4j_browser>> - A browser-based interface for querying and viewing data in a database with rudimentary visualization.
* <<_jupyter_notebook>> - The well-known https://jupyter.org/[web application] for interactive development.

[TIP]
====
*Tip:* For first-time users, we recommend using Neo4j Browser.
====

== Neo4j Browser

To open a database with Neo4j Browser:

. Navigate to the https://console.neo4j.io/[Neo4j Aura Console] in your browser.
. Select the *Open with* dropdown menu on the database you want to open.
. Select *Neo4j Browser* from the dropdown menu.
. Enter the *Username* and *Password* credentials in the Neo4j Browser window that opens. 
These are the same credentials you stored when xref:aurads/setup/create-database.adoc[creating the database].
. Select *Connect*.

Once you have successfully connected, there are built-in guides you can complete to familiarize yourself with Neo4j Browser.

For more information on using Neo4j Browser, please see the https://neo4j.com/docs/browser-manual/current/[Browser manual].

== Jupyter Notebook
