[[aura-importing-database]]
= Importing an existing database
:description: This page describes how to import an existing Neo4j database into an AuraDB instance.

[NOTE]
====
The process of importing or loading data requires you to xref:auradb/getting-started/create-database.adoc[create an AuraDB instance] beforehand.
====

There are two ways you can import data from an existing Neo4j database into an AuraDB instance.

The easiest way is to export a Neo4j database as a *_.dump_* file and use the <<_import_database>> process.
This process, however, only works for *_.dump_* files under 4GB.

If the size of the *_.dump_* file exported from a database is greater than 4GB, you must use the <<_neo4j_admin_database_upload>> method.

== Import database

To import a *_.dump_* file under 4GB:

. Navigate to the https://console.neo4j.io/?product=aura-db[Neo4j Aura Console] in your browser.
. Select the instance you want to import the data.
. Select the *Import Database* tab.
. Drag and drop your *_.dump_* file into the provided window or select *Select a .dump file* and select your file.
. Select *Upload*.

When the upload is complete, the instance goes into a 'Loading' state as the dump is applied.
Once this has finished, the instance returns to its 'Running' state; and the data is ready.

== Neo4j Admin `database upload`

include::partial$database-upload.adoc[]
