[[aura-importing-data]]
= Importing data
:description: This page describes how to get data into a Neo4j AuraDB instance.
:page-aliases: import/introduction.adoc

[NOTE]
====
The process of importing or loading data requires you to xref:auradb/getting-started/create-database.adoc[create an AuraDB instance] beforehand.
====

There are two ways you can import data from a CSV file into an AuraDB instance:

* <<_load_csv>> - A Cypher statement that you run from Neo4j Browser or Neo4j Cypher Shell.
* <<_neo4j_data_importer>> - A visual application that you launch from the Console.

== Load CSV

The link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/load-csv/[`LOAD CSV`] Cypher statement can be used from within Neo4j Browser and Cypher Shell.
For instructions on how to open an AuraDB instance with Browser or Cypher Shell, see xref:auradb/getting-started/connect-database.adoc[].

There are some limitations to consider when using this method to load a CSV file into an AuraDB instance:

* For security reasons, you must host your CSV file on a publicly accessible HTTP or HTTPS server.
Examples of such servers include AWS signed URLs, GitHub, Google Drive, and Dropbox.

* The `LOAD CSV` command is built to handle small to medium-sized data sets, such as anything up to 10 million nodes and relationships.
You should avoid using this command for any data sets exceeding this limit.

== Neo4j Data Importer

Neo4j Data Importer is a UI-based tool for importing data that lets you:

. Load data from flat files (`.csv` and `.tsv`).
. Define a graph model and map data to it.
. Import the data into an AuraDB instance.

To load data with Neo4j Data Importer:

. Navigate to the https://console.neo4j.io/?product=aura-db[Neo4j Aura Console^] in your browser.
. Select the *Import* button on the instance you want to open.

Alternatively, you can access Data Importer from the *Import* tab of xref:auradb/getting-started/connect-database#_neo4j_workspace[Neo4j Workspace].

For more information on Neo4j Data Importer, see the link:{neo4j-docs-base-uri}/data-importer/current/[Neo4j Data Importer documentation].

[NOTE]
====
You must provide your AuraDB instance password before importing from the Neo4j Data Importer.
====

== RDFlib 

RDFLib is a link:https://neo4j.com/labs/[Neo4j Labs] project that enables the import of RDF data, including JSON-LD, to Aura via a Python library.
(Please note: This is a labs project, not fully supported by Neo4j engineering, and may become outdated over time.)

The library is available at link:https://github.com/neo4j-labs/rdflib-neo4j[GitHub - neo4j-labs/rdflib-neo4j: RDFLib Store backed by neo4j + n10s]

Read more about it in the blog post: link:https://medium.com/neo4j/rdflib-neo4j-a-new-era-in-rdf-integration-for-neo4j-dac9fbf93cee[Rdflib-Neo4j: A New Era in RDF Integration for Neo4j]
