[[aura-importing-database]]
= Importing an existing database
:description: This page describes how to import an existing Neo4j database into an AuraDB database.

[NOTE]
====
The process of importing or loading data requires you to xref:auradb/getting-started/create-database.adoc[create an AuraDB database] beforehand. 
====

There are two ways you can import data from an existing Neo4j database into an AuraDB database.

The easiest way is to export a Neo4j database as a *_.dump_* file and use the <<_import_database>> process.
This process, however, only works for *_.dump_* files under 4GB. 

If the size of the *_.dump_* file exported from a database is greater than 4GB, you must use the <<_push_to_cloud>> method.

== Import database

To import a *_.dump_* file under 4GB:

. Navigate to the https://console.neo4j.io/?product=aura-db[Neo4j Aura Console] in your browser.
. Select the database you want to import the data.
. Select the *Import Database* tab.
. Drag and drop your *_.dump_* file into the provided window or select *Select a .dump file* and select your file.
. Select *Upload*.

When the upload is complete, the database goes into a 'Loading' state as the dump is applied. 
Once this has finished, the database returns to its 'Running' state; and the data is ready.

== Push-to-cloud

`Push-to-cloud` is a Neo4j Admin command that you can run to upload the contents of a Neo4j database into an AuraDB database, regardless of the database's size.

Details on how to use the command, along with a full list of options, can be found in the https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin/push-to-cloud/[Neo4j Admin push-to-cloud documentation].