[[aura-importing-data]]
= Importing data
:description: This page describes how to get data into a Neo4j AuraDB instance.
:page-aliases: import/introduction.adoc

[NOTE]
====
The process of importing or loading data requires you to xref:auradb/getting-started/create-database.adoc[create an AuraDB instance] beforehand.
====

There are two ways you can import data from a *_.csv_* file into an AuraDB instance:

* <<_load_csv>> - A Cypher statement that you run from Neo4j Browser or Neo4j Cypher Shell.
* <<_neo4j_data_importer>> - A visual application that you launch from the Console.

== Load CSV

The link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/load-csv/[`LOAD CSV`] Cypher statement can be used from within Neo4j Browser and Cypher Shell.
For instructions on how to open an AuraDB instance with Browser or Cypher Shell, see xref:auradb/getting-started/connect-database.adoc[].

There are some limitations to consider when using this method to load a *_.csv_* file into an AuraDB instance:

* For security reasons, you must host your *_.csv_* file on a publicly accessible HTTP or HTTPS server.
Examples of such servers include AWS signed URLs, GitHub, Google Drive, and Dropbox.

* The `LOAD CSV` command is built to handle small to medium-sized data sets, such as anything up to 10 million nodes and relationships.
You should avoid using this command for any data sets exceeding this limit.

== Neo4j Data Importer

Neo4j Data Importer is a UI-based tool for importing data that lets you:

. Load data from flat files (`.csv` and `.tsv`).
. Define a graph model and map data to it.
. Import the data into an AuraDB instance.

To load data with Neo4j Data Importer:

. Navigate to the https://console.neo4j.io/?product=aura-db[Neo4j Aura Console^] in your browser.
. Select the *Import* button on the instance you want to open.

Alternatively, you can access Data Importer from the *Import* tab of xref:auradb/getting-started/connect-database#_neo4j_workspace[Neo4j Workspace].

For more information on Neo4j Data Importer, see the link:{neo4j-docs-base-uri}/data-importer/current/[Neo4j Data Importer documentation].

[NOTE]
====
You must provide your AuraDB instance password before importing from the Neo4j Data Importer.
====