[[import-others]]
:description: This section describes other ways of importing data into Neo4j.
= Other ways of importing data into Neo4j

Using Data Importer to import data into a Neo4j database is not the only way and may not always be the best way to meet your importing requirements.
There are other ways to load data that may be more suitable, depending on what your needs are.

== `LOAD CSV`

If you are comfortable writing your own Cypher load scripts, this option lets you take advantage of the full capabilities of Cypher.
See link:https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/[Cypher Manual -> LOAD CSV] for more information.


== Neo4j-admin import

To load large amounts of CSV data into an _offline_ database, using the Neo4j-admin tool to import is convenient.
See link:https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin/neo4j-admin-import/[Operations Manual - Neo4j-admin] for more informartion.

== Neo4j connectors

Neo4j offers to capability of using different connectors to connect data from various sourced into Neo4j.
See link:https://neo4j.com/docs/getting-started/languages-guides/integration-tools/integration/[Getting started -> Neo4j Connectors] for a list of available integrations.

== APOC Load procedures

If your data is not in a CSV format, using APOC Load procedures allows you to ingest data from formats including json, xml and arrow.
APOC is a library of user-defined procedures and functions that extends the use of Cypher.
See link:https://neo4j.com/docs/apoc/current/overview/apoc.load/[APOC user guide -> apoc.load] for more information about the load procedure.

// Edit at: https://github.com/neo4j-graphacademy/courses/blob/main/asciidoc/courses/importing-fundamentals/promo.adoc
include::https://raw.githubusercontent.com/neo4j-graphacademy/courses/main/asciidoc/courses/importing-fundamentals/promo.adoc[]