[[aura-instance-resources]]
= Instance resources
:description: Interesting description goes here

Metrics about the resources that are crucial for maintaining the performance and stability of your database instances. 
Monitoring these metrics helps you assess resource usage, anticipate potential issues, and make informed decisions about scaling your infrastructure.

To view additional metrics, simply tab "See all metrics" from the instance card, or "Metrics" from the left hand panel.

== CPU Usage

CPU usage (cores). CPU is used for planning and serving queries. 
If this metric is constantly spiking or at its limits, select `resize` on the instance card, to increase the size of your instance.

== Storage

Amount of disk space reserved to store user database data, in bytes. 
Ideally, the database should all fit into memory (page cache) for the best performance. 
Keep an eye on this metric to make sure you have enough storage for today and for future growth. 
Check this metric with page cache usage to see if the data is too large for the memory and consider increasing the size of your instance in this case.

*Storage is flexible, 
* add the link here about flexible storage (and one line of text)

== Query Executions

The total number of Out of Memory Errors for the instance. 
Consider increasing the size of the instance if any OOM errors.