[[aura-instance-resources]]
= Instance resources
:description: Interesting description goes here

Metrics about the resources that are crucial for maintaining the performance and stability of your database instances. 
Monitoring these metrics helps you assess resource usage, anticipate potential issues, and make informed decisions about scaling your infrastructure.

To view additional metrics, simply tab "See all metrics" from the instance card, or "Metrics" from the left hand panel.

== CPU Usage

CPU usage (cores). CPU is used for planning and serving queries. 
If this metric is constantly spiking or at its limits, select `resize` on the instance card, to increase the size of your instance.

== Storage

Amount of disk space reserved to store data, in gigabytes (GB). 
Ideally, the database should all fit into memory (page cache) for the best performance. 
Keep an eye on storage metrics to make sure you have enough storage for future growth. 
The graph is available in *Metrics > Resources > Storage*.
Check this metric with page cache usage to see if the data is too large for the memory and consider increasing the size of your instance in this case.

Storage is adjustable independent of memory for AuraDB pre-paid plans on Google Cloud Platform (GCP), version 5.x. See xref:managing-instances/instance-actions.adoc#_flexible_storage[Flexible storage] for more information.

== Query Executions

The total number of Out of Memory Errors for the instance. 
Consider increasing the size of the instance if any OOM errors.