[[connecting-spark]]
= Neo4j Connector for Apache Spark
:description: This page describes how to connect to Aura using Spark.

[TIP]
====
Tutorial: xref:tutorials/spark.adoc[Using the Apache Spark Connector with Aura]
====

The Neo4j Connector for Apache Spark is intended to make integrating graphs with Spark easy.
There are two ways to use the connector:

* As a link:{neo4j-docs-base-uri}/spark/current/reading/[data source^]: read any set of nodes or relationships as a `DataFrame` in Spark
* As a link:{neo4j-docs-base-uri}/spark/current/writing/[sink^]: write any `DataFrame` to Neo4j as a collection of nodes or relationships, or use a Cypher statement to process records contained in a `DataFrame` into the graph pattern of your choice

Connecting to Aura only requires to make a few changes to the link:{neo4j-docs-base-uri}/spark/current/configuration/[Neo4j driver configuration^]:

. Replace the `bolt` URI (the value of the `neo4j.server.uri` configuration parameter) with the `neo4j+s://` connection URI from the Aura instance detail page
. Update the username and password configuration parameters as appropriate

For more information check the link:{neo4j-docs-base-uri}/spark/[Neo4j Apache Spark Connector^] page.