= Migrating your Neo4j AuraDB Free instance to another AuraDB plan
:description: This section describes migrating your Neo4j AuraDB Free Instance to another AuraDB plan 
:page-aliases:platform/tutorials/migration-free.adoc

== AuraDB Professional or AuraDB Virtual Dedicated Cloud

Upgrading your plan to AuraDB Professional or AuraDB Virtual Dedicated Cloud gives you access to additional resources and functionalities to support production workloads and applications with demanding storage and processing needs.

*Migration options*

* Upgrade to AuraDB Professional 
* Clone to new (Works for AuraDB Professional and AuraDS Professional) 
* Manual process

== Upgrade to AuraDB Professional

You can upgrade an instance to the Professional plan directly from the console.

On the instance card, click the button that says *Upgrade*. 

Verify that the cloud provider and region are correct and select the instance size you need, add the extra details and select *Create*.

== Clone (Works for AuraDB Professional and AuraDS)

The other way is to _clone_ your existing instance to the Professional plan. 

* Click the three dots (*...*) on an instance card
* Select either: *Clone to new instance* or create a new *Clone to existing instance* (the current content will be overwritten)

== Manual process

In your existing instance:

. (Optional but recommended) Capture existing index and constraint definitions:
.. Run the following Cypher statement:
+
[source,cypher]
----
SHOW CONSTRAINTS YIELD createStatement
----
+
Save result to a file, to use later in the process.
.. Run the following Cypher statement:
+
[source,cypher]
----
SHOW INDEXES YIELD createStatement
----
+
Save result to a file, to use later in the process.

. (Optional but recommended) Drop the indexes and constraints.
.. Run the following Cypher statement to generate the commands to drop existing constraints:
+
[source,cypher]
----
SHOW CONSTRAINTS YIELD name
RETURN 'DROP CONSTRAINT ' + name + ';'
----
.. Execute the generated commands to drop existing constraints.
.. Run the following Cypher statement to generate the commands to drop existing indexes:
+
[source,cypher]
----
SHOW INDEX YIELD name
RETURN 'DROP INDEX ' + name + ';'
----
.. Execute the generated commands to drop existing indexes.
+
For more information about indexes and constrains, see link:{neo4j-docs-base-uri}/cypher-manual/current/indexes/[Cypher Manual -> Indexes] and link:{neo4j-docs-base-uri}/cypher-manual/current/constraints/[Cypher Manual -> Constraints].
+
. In the console of your existing instance (AuraDB Free), do the following:

.. Download snapshot/Dump locally (the daily automatic snapshot)
.. In the Aura Console select the AuraDB instance
.. Go to the *Snapshots* tab
.. Click the *three dots*, and select *Export*
.. Save the dump file locally (preserve the .backup extension)
+
. Then create a new AuraDB instance in AuraDB Professional or AuraDB Virtual Dedicated Cloud with the right resource sizing.
From your new instance, do the following:

.. Go to the instance card
.. Select *Backup & Restore*
.. Upload your .backup file
+
. In the newly created AuraDB Professional or AuraDB Virtual Dedicated Cloud instance
+
(Optional) Once the AuraDB instance is loaded and started, you can recreate the indexes and constraints, using the information captured earlier in the process.