= Migrate from self-managed Neo4j to Aura
:description: This section describes how to migrate from a self-managed Neo4j instance to Aura.
:database: neo4j
:dump-folder: /dumps/neo4j
:aura-uri: neo4j+s://xxxxxxxx.databases.neo4j.io

This tutorial describes how to migrate from a self-managed Neo4j instance to Aura.

[CAUTION]
====
In case you are migrating from self-managed Neo4j 4 to Neo4j 5 on Aura, make sure you take the necessary preparation steps as detailed in the xref:tutorials/upgrade.adoc#_preparation[Upgrade tutorial].

If your local Neo4j version is older than 4.3, you need to upgrade to Neo4j 4.4 first as explained in link:https://neo4j.com/docs/upgrade-migration-guide/current/version-4/[Upgrade and Migration Guide -> Neo4j 4 upgrades and migration].
====

== Preparing for the migration

.Aura database size
Before starting, make sure your new Aura database is sized correctly to support the migration. 
The new database you will create must be at least as large as your self-managed cluster to accommodate the data. 
The Aura RAM-to-storage ratio is 1:2, which means, for example, that a 32 GB Aura database will provide 64 GB of storage.

.APOC compatibility
If you are using any APOC procedures and functions, make sure they are all available in Aura by checking the link:https://neo4j.com/docs/aura/platform/apoc/[APOC Core library].
See the link:https://neo4j.com/docs/apoc/5/[APOC documentation] for further details.

== Creating and uploading a database dump

[NOTE]
====
This process requires a short downtime for your self-managed instance.
====

All the following admin commands must be invoked with the same user as your self-managed Neo4j instance runs as. This guarantees that Neo4j will have full rights to start and work with the database files you use.

. Stop your Neo4j instance.

. Make sure the target directory where to store the database dumps into (for instance `{dump-folder}`) exists. If it does not, create it.

. Create the dump for your database (for instance `{database}`):

+
[.tabbed-example]
====
[.include-with-From-Neo4j-4]
=====
Use the link:https://neo4j.com/docs/operations-manual/4.4/backup-restore/offline-backup/[`neo4j-admin dump`] command.

[source,shell,subs=attributes+]
----
bin/neo4j-admin dump --database={database} --to={dump-folder}
----
=====

[.include-with-From-Neo4j-5]
=====
Use the link:https://neo4j.com/docs/operations-manual/current/backup-restore/offline-backup/[`neo4j-admin database dump`] command.

[source,shell,subs=attributes+]
----
bin/neo4j-admin database dump {database} --to-path={dump-folder}
----
=====
====
+

. Restart your Neo4j instance (if needed).

. Upload the database dump to Aura.

+
[.tabbed-example]
====
[.include-with-From-Neo4j-4]
=====

Use the link:https://neo4j.com/docs/operations-manual/4.4/tools/neo4j-admin/push-to-cloud/[`neo4j-admin push-to-cloud`] command.

[IMPORTANT]
You should use the `--overwrite` option to overwrite the target database. Otherwise, the command aborts and throws an error.

[source,shell,subs=attributes+]
----
bin/neo4j-admin push-to-cloud --dump={dump-folder}/file.dump --bolt-uri={aura-uri} --overwrite
----
=====

[.include-with-From-Neo4j-5]
=====
Use the link:https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin/upload-to-aura/[`neo4j-admin database upload`] command.

[IMPORTANT]
You should use the `--overwrite-destination=true` option to overwrite the target database. Otherwise, the command aborts and throws an error.

[source,shell,subs=attributes+]
----
bin/neo4j-admin database upload {database} --from-path={dump-folder} --to-uri={aura-uri} --overwrite-destination=true
----
=====
====
+


== Validate the uploaded database

Once the above steps are complete, validate the data (for example, by checking that the number of nodes and relationships is the same).