= Migrating your Neo4j AuraDB Free Instance to another AuraDB plan (Pro or Enterprise)
:description: This section describes migrating your Neo4j AuraDB Free Instance to another AuraDB plan (Pro or Enterprise)

Upgrading your plan to Professional or Enterprise gives you access to additional resources and functionalities to support production workloads and applications with demanding storage and processing needs.

*Migration options*

* Upgrade to Professional (Works for AuraDB)
* Clone to New (Works for Aura Professional and AuraDS) 
* Manual Process

== Upgrade to Professional (Works for AuraDB)

You can upgrade an instance to the Professional plan directly from the console.

Click the *three dots* on an instance card > *Upgrade to Professional*

Verify that the cloud provider and region are correct and select the instance size you need.
Note that the default version of Neo4j is 5.
Once you are satisfied, click ***Upgrade***.

== Clone (Works for Aura Professional and AuraDS)

The other way is to clone your existing free tier AuraDB Instance to the Professional tier. 

* Click the *three dots* on an instance 
* Select either: *Clone to new* or *Clone to existing* (the content will be replaced)
* Select the type: *AuraDB* or *AuraDS*

== Manual process

In the Free AuraDB Instance:

* (Optional but recommended) Capture existing index and constraint definitions:
** Run the cypher statement `SHOW CONSTRAINTS YIELD createStatement` and save result to a file, to use later in the process.
** Run the cypher statement `SHOW INDEXES YIELD createStatement` and save result to a file to use later in the process.

* (Optional but recommended) Drop the indexes and constraints.
** Run the cypher statement `SHOW CONSTRAINTS YIELD name RETURN 'DROP CONSTRAINT ' + name + ';'` in order to generate the commands to drop existing constraints. 
** Execute the generate commands to drop existing constraints.
** Run the cypher statement `SHOW INDEXES YIELD name RETURN 'DROP INDEX ' + name +';'` in order to generate the commands to drop existing indexes. 
* Then execute the generate commands to drop existing indexes.
* For more detail regarding the capture and recreating of indexes and constrains, please refer to the link:https://support.neo4j.com/s/article/4416090515219-Indexes-Capture-Drop-Recreate-existing[Indexes - Capture / Drop / Recreate] knowledge base article.

=== In the console (Activities on AuraDB Free)

* Download snapshot/Dump locally (the daily automatic snapshot)
* In the Aura Console select the AuraDB Instance
* Go to the *Snapshots* tab
* Click the *three dots*, and select *Export*
* Save locally the Dump file (preserve the .dump extension)

=== In the console (Activities on AuraDB Professional or AuraDB Enterprise)

* Create a new AuraDB Instance in AuraDB Professional or AuraDB Enterprise with the right resource sizing.
* Upload via Console drag and drop or push-to-cloud
* From the Aura Console: link:https://neo4j.com/docs/aura/auradb/importing/importing-data/#_import_database[Drag and drop]
* Using the command line: `neo4j-admin push-to-cloud`

=== In the newly created AuraDB Professional or Enterprise Instance

(Optional) Once the AuraDB Instance is loaded and started, you can now recreate the indexes and constraints, using the information captured earlier in the process or refer to link:https://support.neo4j.com/s/article/4416090515219-Indexes-Capture-Drop-Recreate-existing[Indexes - Capture / Drop / Recreate] knowledge base article.

