= Migrate from self-managed Neo4j to Aura
:description: This section describes how to migrate from a self-managed Neo4j database to Aura.
:database: neo4j
:dump-folder: /dumps/neo4j
:aura-uri: neo4j+s://xxxxxxxx.databases.neo4j.io

This tutorial describes how to migrate from a self-managed Neo4j database to Aura.

[CAUTION]
====
The minimum version of self-managed to upload to Aura is v5 LTS (5.26.7)
====

The Aura console only supports `neo4j-admin database upload` from versions 5.26.7 and later, 2025.04 and later.
If your self-managed database is of an earlier version, you need to first update or migrate to at least 5.26.7.
== Preparation

// === Migrating to Neo4j latest

// If you are migrating from self-managed Neo4j 4.3 or 4.4 to Neo4j latest on Aura, carefully read the xref:tutorials/upgrade.adoc#_preparation[Preparation section in the Upgrade tutorial] to ensure you are well prepared for the migration.

=== Aura instance size

Before starting, verify that the Aura instance you are migrating to is sized accordingly.
The instance must be at least as large as your self-managed database to accommodate the data.
// The Aura RAM-to-storage ratio is 1:2, which means, for example, that a 32 GB Aura instance provides 64 GB of storage.

=== APOC compatibility

Aura contains most but not all functions and procedures contained in the link:{neo4j-docs-base-uri}/apoc/current[APOC Core] library.
If you are using any APOC procedures and functions, make sure they are all available in Aura by checking the link:https://neo4j.com/docs/aura/platform/apoc/[APOC support page].

== Creating and uploading a database dump

In order to move data from your self-managed database to Aura, you need to create a dump of the existing database.

[NOTE]
====
This process requires a short downtime for your self-managed database.
====

The following admin commands must be invoked with the same user as your self-managed Neo4j database.
This guarantees that Neo4j has full rights to start and work with the database files you use.

. Stop your self-managed Neo4j database.
Stop the database you want to create a dump of, using the command `STOP DATABASE {database}` in Cypher Shell or Browser.

. Ensure the target directory to store the database dumps (for instance `{dump-folder}`) exists.

. Depending on your self-managed Neo4j version, create a dump of your database (e.g. `{database}`) using the link:https://neo4j.com/docs/operations-manual/current/backup-restore/offline-backup/[`neo4j-admin database dump`] command:
+
[source,shell,subs=attributes+]
----
bin/neo4j-admin database dump {database} --to-path={dump-folder}
----
+
If your self-managed database is of version 4.4, you need to migrate to a later version before uploading to Aura.
See the migration guide: link:https://neo4j.com/docs/upgrade-migration-guide/current/version-5/migration/[Migrate databases from 4.4 LTS (EOL)] for more information.
+
. Depending on your self-managed Neo4j version, upload the database dump (e.g. `{database}`) to your Aura instance (the Aura instance does *not* need to be stopped) using the link:https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin/upload-to-aura/[`neo4j-admin database upload`] command.
+
[source,shell,subs=attributes+]
----
bin/neo4j-admin database upload {database} --from-path={dump-folder} --to-uri={aura-uri} --overwrite-destination=true
----