= Migrate from self-managed Neo4j to Aura
:description: This section describes how to migrate from a self-managed Neo4j instance to Aura.

This tutorial describes how to migrate from a self-managed Neo4j instance to Aura.

[WARNING]
====
Before starting, make sure your new Aura database is sized correctly to support the migration. 
The new database you will create must be at least as large as your self-managed cluster to accommodate the data. 
The Aura RAM-to-storage ratio is 1:2, which means, for example, that a 32 GB Aura database will provide 64 GB of storage.
====

== Preparation

[NOTE]
====
In case you are migrating from self-managed Neo4j 4 to Neo4j 5 on Aura, make sure you take the necessary preparation steps as detailed in the xref:tutorials/upgrade.adoc#_preparation[Upgrade tutorial].

If your local Neo4j version is older than 4.3, you need to upgrade to Neo4j 4.4 first as explained in link:https://neo4j.com/docs/upgrade-migration-guide/current/version-4/[Upgrade and Migration Guide -> Neo4j 4 upgrades and migration].
====

=== APOC compatibility

If you are using any APOC procedures and functions, make sure they are all available in Aura by checking the link:https://neo4j.com/docs/aura/platform/apoc/[APOC Core library].
See the link:https://neo4j.com/docs/apoc/5/[APOC documentation] for further details.

== Creating a database dump

[NOTE]
====
This process requires a short downtime for the existing cluster.
====

All admin commands must be invoked with the same user as Neo4j runs as. This guarantees that Neo4j will have full rights to start and work with the database files you use.

. Stop your Neo4j instance.

. Create the database dump using the following command:

```
./neo4j-admin database dump neo4j --to-path=/path/to/data/dumps
```

. Restart your Neo4j instance (if needed).

== Upload a database dump to Aura

* If your instance uses Neo4j 5, use the link:https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin/upload-to-aura/[`neo4j-admin database upload`] command.
* If your instance uses Neo4j 4.4 or 4.3, use the link:https://neo4j.com/docs/operations-manual/4.4/tools/neo4j-admin/push-to-cloud/[`neo4j-admin push-to-cloud`] command.

```
./neo4j-admin database upload neo4j --from-path=/path/to/data/dumps/ --to-uri=neo4j+s://xxxxxxxx.databases.neo4j.io --overwrite-destination=true
```

.. Once the above steps are complete, validate the data.
One quick way to do this is to open a browser window for both the original and new databases, and run this Cypher query against them, comparing the output: +
+
[source, cypher]
----
MATCH (n)
RETURN DISTINCT labels(n) as Labels, count(labels(n)) as NumberOfNodes
----
+
[NOTE]
====
The number of labels should be the same as in the original database. If they are not, contact support.
====