= Using the Apache Spark Connector
:product: Aura

This tutorial shows how to use the Neo4j Connector for Apache Spark to write to and read data from an Aura instance.

== Setup

. Download link:https://spark.apache.org/downloads.html[Apache Spark^].
+
_Example: Spark 3.4.1, pre-built for Apache Hadoop 3.3 and later with Scala 2.12._

. Download the link:https://github.com/neo4j-contrib/neo4j-spark-connector/releases[Neo4j Connector JAR file^], making sure to match both the Spark version and the Scala version.
+
_Example: Neo4j Connector 5.1.0, built for Spark 3.x with Scala 2.12._

. Decompress the Spark file and launch the Spark shell as in the following example:
+
[source, shell]
----
$ spark-3.4.1-bin-hadoop3/bin/spark-shell --jars neo4j-connector-apache-spark_2.12-5.1.0_for_spark_3.jar
----

== Running code in Spark

[TIP]
====
You can copy-paste Scala code in the Spark shell by activating the `paste` mode with the `:paste` command.
====

Create a Spark session and set the Aura connection credentials:

[source, scala]
----
import org.apache.spark.sql.{SaveMode, SparkSession}

val spark = SparkSession.builder().getOrCreate()

// Replace with the actual connection URI and credentials
val url = "neo4j+s://xxxxxxxx.databases.neo4j.io"
val username = "neo4j"
val password = ""
----

Then, create the `Person` class and a Spark `Dataset` with some example data:

[source, scala]
----
case class Person(name: String, surname: String, age: Int)

// Create example Dataset
val ds = Seq(
    Person("John", "Doe", 42),
    Person("Jane", "Doe", 40)
).toDS()
----

Write the data to Aura:

[source, scala]
----
// Write to Neo4j
ds.write.format("org.neo4j.spark.DataSource")
    .mode(SaveMode.Overwrite)
    .option("url", url)
    .option("authentication.basic.username", username)
    .option("authentication.basic.password", password)
    .option("labels", ":Person")
    .option("node.keys", "name,surname")
    .save()
----

You can then query and visualize the data using the Neo4j Browser.

You can also read the data back from Aura:

[source, scala]
----
// Read from Neo4j
val data = spark.read.format("org.neo4j.spark.DataSource")
    .option("url", url)
    .option("authentication.basic.username", username)
    .option("authentication.basic.password", password)
    .option("labels", "Person")
    .load()

// Visualize the data as a table
data.show()
----

For further information on how to use the connector, read the link:{neo4j-docs-base-uri}/spark/[Neo4j Spark Connector docs].