= Upgrade your AuraDB Professional instance to AuraDB Business Critical
:description: This section describes upgrading AuraDB Professional instance to AuraDB Business Critical

Upgrading your plan to AuraDB Business Critical,

* without downtime
* 


== Manual process

In your existing instance:

. (Optional but recommended) Capture existing index and constraint definitions:
.. Run the following Cypher statement:
+
[source,cypher]
----
SHOW CONSTRAINTS YIELD createStatement
----
+
Save result to a file, to use later in the process.
.. Run the following Cypher statement:
+
[source,cypher]
----
SHOW INDEXES YIELD createStatement
----
+
Save result to a file, to use later in the process.

. (Optional but recommended) Drop the indexes and constraints.
.. Run the following Cypher statement to generate the commands to drop existing constraints:
+
[source,cypher]
----
SHOW CONSTRAINTS YIELD name
RETURN 'DROP CONSTRAINT ' + name + ';'
----
.. Execute the generated commands to drop existing constraints.
.. Run the following Cypher statement to generate the commands to drop existing indexes:
+
[source,cypher]
----
SHOW INDEX YIELD name
RETURN 'DROP INDEX ' + name + ';'
----
.. Execute the generated commands to drop existing indexes.
+
For more information about indexes and constrains, see link:{neo4j-docs-base-uri}/cypher-manual/current/indexes/[Cypher Manual -> Indexes] and link:{neo4j-docs-base-uri}/cypher-manual/current/constraints/[Cypher Manual -> Constraints].
+
. In the console of your existing instance (AuraDB Free), do the following:

.. Download snapshot/Dump locally (the daily automatic snapshot)
.. In the Aura Console select the AuraDB instance
.. Go to the *Snapshots* tab
.. Click the *three dots*, and select *Export*
.. Save the dump file locally (preserve the .backup extension)
+
. Then create a new AuraDB instance in AuraDB Professional or AuraDB Virtual Dedicated Cloud with the right resource sizing.
From your new instance, do the following:

.. Go to the instance card
.. Select *Backup & Restore*
.. Upload your .backup file
+
. In the newly created AuraDB Professional or AuraDB Virtual Dedicated Cloud instance
+
(Optional) Once the AuraDB instance is loaded and started, you can recreate the indexes and constraints, using the information captured earlier in the process.