[[change-data-capture-overview]]
= Change Data Capture (CDC)
:description: This section covers changing transaction log enrichment mode using the Aura Console.

Change Data Capture (CDC) tracks changes to your data, which allows you to keep your other data sources up-to-date and accurate. For more information see the link:https://neo4j.com/docs/cdc/current/[Neo4j DBMS CDC documentation]. 

CDC enrichment mode can be set to OFF, DIFF, or FULL. See the link:https://neo4j.com/docs/cdc/current/getting-started/enrichment-mode/[Enrichment mode] documentation for more information. Choosing OFF, DIFF, or FULL does not affect the cost of an instance.

If an instance is paused or resumed, the CDC enrichment mode does not change.

== Edit CDC enrichment mode from within the Aura Console

View an instance's current CDC enrichment mode by clicking on an instance’s card in the Aura Console dashboard. Enrichment mode is set to OFF by default. 

Only Admins can change the CDC status. If an Admin changes the CDC enrichment mode from DIFF or FULL to OFF they will see a message within the Aura Console that says, "Please note, applications dependent on CDC will stop working. See link:https://neo4j.com/docs/cdc/current/getting-started/enrichment-mode/#_disabling_log_enrichment[Disabling Log Enrichment] for more info”.

