[[change-data-capture-overview]]
= Change Data Capture (CDC)
:description: This section covers changing transaction log enrichment mode using the Aura Console.

label:AuraDB-Professional[] 
label:AuraDB-Enterprise[]

Change Data Capture tracks changes to your data by querying the transaction logs for Creates, Updates and Deletes, so that you can update other applications or data sources.

For more information see link:{neo4j-docs-base-uri}/cdc/current[Neo4j DBMS -> Change Data Capture (CDC)].

Log enrichment mode can be set to `OFF`, `DIFF` or `FULL`. 
For more information see link:{neo4j-docs-base-uri}/cdc/current/getting-started/enrichment-mode/[Neo4j DBMS -> CDC -> Enrichment mode].


If an instance is paused or resumed, the log enrichment mode does not change.

== Modifying log enrichment mode from within the Aura Console

View an instance’s current log enrichment mode by clicking on an instance in the Aura Console. 

Note that default log enrichment mode is `OFF` and change data capture is disabled until it is set as `DIFF` or `FULL`.

Only Admins can change the log enrichment mode. 
If an Admin changes log enrichment mode from `DIFF` or `FULL` to `OFF` applications dependent on CDC will stop working. For more info see link:https://neo4j.com/docs/cdc/current/getting-started/enrichment-mode/#_disabling_log_enrichment[Neo4j DBMS -> CDC -> Disabling Log Enrichment].

== Performing a restore in Aura with log enrichment mode enabled

If you want to take a snapshot and restore it to the same DBMS, or create a new instance from that snapshot, by default log enrichment mode is `OFF`. 
If the original status of that instance had log enrichment mode set to `DIFF` or `FULL`, the status would change. 
You need to proactively enable it.

CDC assumes that changes can be represented as a continuous stream of changes, each new change building on top of the state of the previous changes. 
Restoring your Neo4j database breaks this continuous stream. 
Ensure that you have read and understood the implications documented in link:{neo4j-docs-base-uri}/cdc/current[Neo4j DBMS -> CDC -> Backup and Restore Operations] before proceeding with restoring your backup.
