[[aura-api-authentication]]
= Authentication
:description: This page describes how to authenticate requests to the Aura API.

label:AuraDB-Enterprise[]
label:AuraDS-Enterprise[]

[TIP]
====
The Aura API is currently in Public Beta for Aura Enterprise customers only. If you wish to participate in the Public Beta, please contact your Customer Success Manager.
====

The Aura API uses OAuth 2.0 for API authentication.

== Creating credentials

. Navigate to the https://console.neo4j.io/[Neo4j Aura Console Account Details page] in your browser.
. Select the *Create* button in the *OAuth 2.0 Clients* section.
. Enter a *Client name*, and select *Create*.
. Securely save the *Client ID* and *Client Secret* you are given in the resulting modal; you will need these for the next step.

[CAUTION]
====
You cannot retrieve your secret after you close the modal, so save it securely.
====

== Authenticating API requests

To authenticate API requests to the link:{neo4j-docs-base-uri}/aura/api/specification/[Aura API], you must provide a Bearer Token in the `Authorization` header of your request as shown below:

`Authorization: Bearer <access_token>`

[TIP]
====
You can use the *Authorize* button on the link:{neo4j-docs-base-uri}/aura/api/specification/[Aura API] page to authenticate and test endpoints directly using your client ID and client secret.
====

=== Token endpoint

You can use the following `/oauth/token` endpoint to obtain a Bearer Token for authenticating API requests.

Authentication to the token endpoint uses HTTP Basic Auth using your client ID as the username and client secret as the password.
footnote:[If you wish to manually log in...]

[CAUTION]
====
Both the request and response contain sensitive information and must be kept secure. 

You are responsible for keeping the client credentials and access tokens confidential, whether in transit (by specifying HTTPS), if stored at rest, in log files, etc.
====

==== Request parameters

* Method: `POST`
* Token URL: `https://api.neo4j.io/oauth/token`

==== Request header

[cols="1,1"]
|===
|Parameter |Value

|Content-Type
|`application/x-www-form-urlencoded`
|===

==== Request body

[cols="1,1"]
|===
|Parameter |Value

|grant_type
|`client_credentials`
|===

==== cURL example

[source, shell]
----
curl --request POST 'https://api.neo4j.io/oauth/token' \
     --user '<client_id>:<client_secret>' \
     --header 'Content-Type: application/x-www-form-urlencoded' \
     --data-urlencode 'grant_type=client_credentials'
----

==== Response body example

[source, json, role=nocopy]
----
{
  "access_token": "<token>", <1>
  "expires_in": 3600,
  "token_type": "bearer"
}
----

<1> The `access_token` returned here is what you will provide as the Bearer Token used in the `Authorization` header of Aura API requests.

==== HTTP response codes

[cols="1,1,1"]
|===
|Code |Message |Description

|200
|Success
|Access token requested successfully.

|400
|Bad Request
|Request is invalid.

|401
|Unauthorized
|The provided credentials are invalid, expired, or revoked.
|===

=== Token expiration

If you attempt to send a request to the Aura API, authenticated using an expired access token, you will receive a 403 Forbidden response. 
You will need to obtain a new token to continue using the API.