[[aura-api-overview]]
= Overview
:description: This page introduces the Aura API.

The Aura API allows you to programmatically perform actions on your Aura instances without the need to login to the Console.

A full list of the available endpoints can be seen and tested in the link:{neo4j-docs-base-uri}/aura/api/specification/[API Specification].

== API URL

=== Base URL

The base URL for the Aura API is `\https://api.neo4j.io`.

=== Versioning

There are currently two versions of the Aura API available:

* `link:{neo4j-docs-base-uri}/aura/api/specification/?urls.primaryName=Aura%20v1beta2[V1beta2]` - This is the latest version of the API.
* `link:{neo4j-docs-base-uri}/aura/api/specification/?urls.primaryName=Aura%20v1beta1[V1beta1]` - This was the initial release of the API and is only available for backward compatibility.

[NOTE]
====
`V1beta2` indicates that this is the second beta release of V1 of the Public API. 
Once the API becomes generally available, the version will be updated to `V1`.
====

As and when we need to introduce breaking changes to the API, we will release a new version to ensure we do not break existing integrations.

In the future, as we deprecate legacy API versions, we will provide notice. 
Once the expiry date for a deprecated version has passed, that version will no longer be available.

=== Example request

The following example shows how to use the base URL and versioning to make a request to the API:

`GET \https://api.neo4j.io/v1beta2/instances`

== Retries

In the event of `5xx` server error responses, you may consider retrying the request after a delay if it is safe to do so. The response may include a `Retry-After` header with a suggestion of a suitable minimum delay before attempting to retry.

Rate limiting is set to 125 requests per minute.

You should consider your use of the Rate Limit before attempting to retry, and we recommend using an exponential backoff delay with a limited number of retries before giving up.

A request is only guaranteed to be safe to retry if it uses an idempotent HTTP method, such as `GET`. If for example, you attempt to retry a request for creating an instance, you may end up with duplicate instances and end up being charged extra as a result.

In the case of `429 Too Many Requests`, we would recommend slowing down the rate of all requests sent from your client application and consider retrying with a suitable minimum delay and backoff strategy.

For other `4xx` client error responses, you should not resend such requests without first correcting them.


