[[connecting-arrow]]
= Loading and streaming data with Apache Arrow
:description: This page describes how to use Apache Arrow on AuraDS.
:notebook-name: Arrow_examples.ipynb

include::partial$aurads/colab.adoc[]

The Enterprise Edition of GDS installed on AuraDS includes an link:https://neo4j.com/docs/graph-data-science/current/installation/configure-apache-arrow-server/[Arrow Flight server], configured and running by default.
The Arrow Flight server speeds up data-intensive processes such as:

* Creating a graph directly from in-memory data.
* Streaming node and relationship properties.
* Streaming the relationship topology of a graph.

There are two ways to use the Arrow Flight server with GDS:

. By implementing a custom Arrow Flight client as explained in the link:https://neo4j.com/docs/graph-data-science/current/graph-catalog-apache-arrow-ops/[GDS manual].
. By using the GDS Python client, which includes an Arrow Flight client.

In the following examples we use the GDS client as it is the most convenient option.

== Setup

[source, python]
----
%pip install 'graphdatascience>=1.7'

from graphdatascience import GraphDataScience

# Replace with the actual connection URI and credentials
NEO4J_CONNECTION_URI = "neo4j+s://xxxxxxxx.databases.neo4j.io"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = ""

# When initialized, the client tries to use Arrow if it is available on the server.
# This behaviour is controlled by the `arrow` parameter, which is set to `True` by default.
gds = GraphDataScience(NEO4J_CONNECTION_URI, auth=(NEO4J_USERNAME, NEO4J_PASSWORD), aura_ds=True)

# Necessary if Arrow is enabled (as is by default on Aura)
gds.set_database("neo4j")
----

You can call the `gds.debug.arrow()` procedure to verify that Arrow is enabled and running.

== Loading data

You can load data directly into a graph using the link:https://neo4j.com/docs/graph-data-science-client/current/graph-object/#construct[`gds.graph.construct`] client method.

The data must be a Pandas `DataFrame`, so we need to install and import the link:https://pandas.pydata.org/[`pandas`] library.

[source, python]
----
%pip install pandas

import pandas as pd
----

We can then create a graph as in the following example.
The format of each `DataFrame` with the required columns is specified in the link:https://neo4j.com/docs/graph-data-science-client/current/graph-object/#construct[GDS manual].

[source, python, role=nocollapse]
----
nodes = pd.DataFrame(
    {
        "nodeId": [0, 1, 2],
        "labels":  ["Article", "Article", "Article"],
        "pages": [3, 7, 12],
    }
)

relationships = pd.DataFrame(
    {
        "sourceNodeId": [0, 1],
        "targetNodeId": [1, 2],
        "relationshipType": ["CITES", "CITES"],
        "times": [2, 1]
    }
)

article_graph = gds.graph.construct(
    "article-graph",
    nodes,
    relationships
)
----

Now we can check that the graph has been created:

[source, python]
----
gds.graph.list()
----

== Streaming node and relationship properties

After creating the graph, you can read the node and relationship properties link:https://neo4j.com/docs/graph-data-science-client/current/graph-object/#graph-object-streaming-properties[as streams].
These procedures do not require Arrow, but are more efficient if Arrow is available.

[source, python]
----
# Read all the values for the node property `pages`
gds.graph.nodeProperties.stream(article_graph, "pages")
----

[source, python]
----
# Read all the values for the relationship property `times`
gds.graph.relationshipProperties.stream(article_graph, "times")
----

== Performance

To see the difference in performance when Arrow is available, we can measure the time needed to load a dataset into a graph.
In this example we use a built-in link:https://neo4j.com/docs/graph-data-science-client/current/common-datasets/#_ogbn_graphs[OGBN dataset], so we need to install the `ogb` extra.

[source, python]
----
%pip install 'graphdatascience[ogb]>=1.7'
----

First, we load and immediately drop the dataset in order to download the data.

[source, python]
----
ogbn_arxiv = gds.graph.ogbn.load("ogbn-arxiv")
ogbn_arxiv.drop()
----

We can now time the actual loading process by running the loader again.
On an 8 GB AuraDS instance, this should take less than 30 s.

[source, python]
----
%%timeit -n 1 -r 1

gds.graph.ogbn.load("ogbn-arxiv")
----

With Arrow disabled by adding `arrow=False` to the `GraphDataScience` constructor, the same loading process would take more than 1 minute.
Therefore, with this dataset, Arrow provides at least a 2x speedup.

== Cleanup

[source, python]
----
article_graph.drop()
ogbn_arxiv.drop()

gds.close()
----