[[connecting-python]]
= Connecting with Python
:description: This page describes how to connect to AuraDS using Python.

TIP: Follow along with a notebook in https://colab.research.google.com/drive/10XK5_fyNURb1u_gvD_lkt7qQvIxzAhnJ?usp=sharing[image:colab.svg[Colab,24] Google Colab^]

This tutorial introduces some best practices for connecting and interacting with Neo4j and the Graph Data Science Library.

== Connection details

The connection to an instance requires three inputs:

* Instance connection URI
* Instance username
* Instance password

The username (default `neo4j`) and password are generated when the instance is created. Copy and paste them as values of the `AURA_USERNAME` and `AURA_PASSWORD` variables respectively.

The instance connection URI can be found on the instance main page. Copy and paste it as value of the `AURA_CONNECTION_URI` variable.

[source, python]
----
# Connection details
AURA_CONNECTION_URI = "neo4j+s://xxxxxxxx.databases.neo4j.io"
AURA_USERNAME = "neo4j"
AURA_PASSWORD = ""
----

== Using the GDS client

WARNING: The link is to the 2.0 preview. Should it be replaced by a non-preview link?

[NOTE]
For more information about the client, head over to the Graph Data Science https://neo4j.com/docs/graph-data-science/2.0-preview/python-client/[Python client manual].

=== Installing the client

To install the latest stable version of the GDS client:

[source, shell]
----
pip install graphdatascience
----

Visit https://pypi.org/project/graphdatascience to find the latest stable version of the client.

=== Importing the client

The client is imported as the `GraphDataScience` class:

[source, python]
----
# Driver import
from graphdatascience import GraphDataScience
----

=== Client object

Constructing a client instance requires the connection URI (`AURA_CONNECTION_URI`) and authentication information (`AURA_USERNAME` and `AURA_PASSWORD`) as defined above.

We'll use the client object to run queries. The `aura_ds=True` constructor argument should be used to have the recommended non-default configuration settings of the Python Driver applied automatically.

[source, python]
----
# Client instantiation
gds = GraphDataScience(
  AURA_CONNECTION_URI,
  auth=(AURA_USERNAME, AURA_PASSWORD),
  aura_ds=True
)
----

=== Running a query

Below we'll run an example query.

[source, python]
----
# Call a GDS method directly

print(gds.version())
----

== Using the Python driver

[NOTE]
For more information about the https://neo4j.com/docs/driver-manual/current/get-started[Python Driver], head over to the Neo4j Driver Manual.

=== Installing the driver

To install the latest stable version of the Python Driver:

[source, shell]
----
pip install neo4j
----

To find the latest stable version of the Python Driver, visit https://pypi.org/project/neo4j/

=== Importing the driver

The main import you'll need is the `GraphDatabase` import. This will allow you to create a driver which we will use to connect to and run queries against the instance.

[source, python]
----
# Driver import
from neo4j import GraphDatabase
----

=== Driver object

Constructing a driver instance requires the connection URI (`AURA_CONNECTION_URI`) and authentication information (`AURA_USERNAME` & `AURA_PASSWORD`).

We'll use the Driver object to create Sessions with the instance, this will allow you to run Queries.

[source, python]
----
# Driver Instantiation
driver = GraphDatabase.driver(AURA_CONNECTION_URI, auth=(AURA_USERNAME, AURA_PASSWORD))
----

=== Running a query

Below we'll run two example queries. The first will get the version of GDS running on the instance. The second will ask GDS to list all the procedures available within the library and return the first 5.

[source, python]
----
# Cypher query
list_in_memory_graph_query = """
RETURN gds.version() AS version
"""

# Create a driver session
with driver.session() as session:
  # use .data() to access the results array
  results = session.run(list_in_memory_graph_query).data()
  print(results)
----

=== Closing the driver

When you're finished interacting with your instance, you should close your driver connection.

[source, python]
----
# Close the Driver connection
driver.close()
----

== References

=== Documentation
* https://neo4j.com/docs/graph-data-science[Neo4j GDSL documentation^]
* https://neo4j.com/docs/driver-manual/current/get-started/[Neo4j driver documentation^]
* https://neo4j.com/developer[Neo4j developer documentation^]

=== Cypher

* Learn more about the https://neo4j.com/docs/cypher-manual/current/[Cypher^] syntax
* The https://neo4j.com/docs/cypher-manual/current/[Cypher reference card^] is also a great resource for understanding how to use Cypher keywords

=== Modelling

* https://neo4j.com/developer/guide-data-modeling/[Data modelling guidelines^]
* https://neo4j.com/developer/modeling-designs/[Data modelling design^]
* https://neo4j.com/developer/graph-model-refactoring/[Refactoring a data model^]
