[[graph-catalog]]
= Projecting graphs and using the Graph Catalog
:description: This page describes the graph catalog and in-memory graphs.
:generated-graph-size: 100

TIP: Follow along with a notebook in https://colab.research.google.com/drive/1Y8O4RR7vUOePQrHviTSN6cNCbZfxXRUg?usp=sharing[image:colab.svg[Colab,24] Google Colab^]

This tutorial shows how to manage, interact with and use the graph catalog in order to run algorithms on in-memory graphs.

The graph catalog is described into more detail in the https://neo4j.com/docs/graph-data-science/current/management-ops/graph-catalog-ops/[Graph Data Science Library manual^].

include::partial$aurads/setup.adoc[]

include::partial$aurads/generated-graph.adoc[]

== Listing in-memory graphs

We can inspect what is in memory graphs we have in the graph catalog by asking the Graph Catalog using the `gds.graph.list()` procedure.

If you want to check for the existence of an in-memory graph, try replacing `graph.graph.list` with `gds.graph.exists` along with the name of an in-memory graph

[.tabbed-example]
====
[.include-with-GDS-client]
=====
[source, python, subs=attributes+]
----
# List all in-memory graphs
all_graphs = gds.graph.list()

# Prettify the results
print(json.dumps(all_graphs, indent=2, sort_keys=True, default=default))
----

[source, python, subs=attributes+]
----
# Check whether the "example-graph" graph exists in memory
gds.graph.exists("example-graph")
----
=====

[.include-with-Cypher]
=====
[source, cypher, subs=attributes+]
----
CALL gds.graph.list()
----
=====

[.include-with-Python-driver]
=====
[source, python, subs=attributes+]
----
show_in_memory_graphs_query = """
CALL gds.graph.list()
"""

# Create driver session
with driver.session() as session:
  # Run query
  results = session.run(show_in_memory_graphs_query).data()
  # Prettify the results
  print(json.dumps(results, indent=2, sort_keys=True, default=default))
----

[source, python, subs=attributes+]
----
check_graph_exists_query = """
CALL gds.graph.exists('example-graph')
"""

# Create driver session
with driver.session() as session:
  # Run query and print result
  print(session.run(check_graph_exists_query).data())
----
=====
====

== Drop the example graph

To drop the example in-memory graph we created previously, you can use the `gds.graph.drop` procedure and specify the name of the graph we created (https://neo4j.com/docs/graph-data-science/current/management-ops/graph-catalog-ops/#graph-catalog-ops[example-graph]).

[.tabbed-example]
====
[.include-with-GDS-client]
=====
[source, python, subs=attributes+]
----
result = gds.graph.drop(g)

# Prettify the result
print(json.dumps(result, indent=2, sort_keys=True, default=default))
----
=====

[.include-with-Cypher]
=====
[source, cypher, subs=attributes+]
----
CALL gds.graph.drop('example-graph')
----
=====

[.include-with-Python-driver]
=====
[source, python, subs=attributes+]
----
drop_graph_query = """
CALL gds.graph.drop('example-graph')
"""

# Create driver session
with driver.session() as session:
  # Run query
  result = session.run(drop_graph_query).data()
  # Prettify the result
  print(json.dumps(result, indent=2, sort_keys=True, default=default))
----
=====
====

== Loading data from Neo4j - Native projections

Native projections allow us to take a graph stored on disk and project it into an in-memory graph. You specify which node labels, relationship types and properties you wish to be brought into a new in-memory graph using `CALL gds.graph.project` (https://neo4j.com/docs/graph-data-science/current/management-ops/native-projection/#native-projection-syntax[])

In the following we will use this graph as an example.

[.tabbed-example]
====
[.include-with-GDS-client]
=====
[source, python, subs=attributes+]
----
# Cypher query to create example graph to disk
write_example_graph_query = """
MERGE (a:EngineeringManagement {name: 'Alistair'})
MERGE (j:EngineeringManagement {name: 'Jennifer'})
MERGE (d:Developer {name: 'Leila'})
MERGE (a)-[:MANAGES {start_date: 987654321}]->(d)
MERGE (j)-[:MANAGES {start_date: 123456789, end_date: 987654321}]->(d)
"""

gds.run_cypher(write_example_graph_query)
----
=====

[.include-with-Cypher]
=====
[source, cypher, subs=attributes+]
----
MERGE (a:EngineeringManagement {name: 'Alistair'})
MERGE (j:EngineeringManagement {name: 'Jennifer'})
MERGE (d:Developer {name: 'Leila'})
MERGE (a)-[:MANAGES {start_date: 987654321}]->(d)
MERGE (j)-[:MANAGES {start_date: 123456789, end_date: 987654321}]->(d)
----
=====

[.include-with-Python-driver]
=====
[source, python, subs=attributes+]
----
# Cypher query to create example graph to disk
write_example_graph_query = """
MERGE (a:EngineeringManagement {name: 'Alistair'})
MERGE (j:EngineeringManagement {name: 'Jennifer'})
MERGE (d:Developer {name: 'Leila'})
MERGE (a)-[:MANAGES {start_date: 987654321}]->(d)
MERGE (j)-[:MANAGES {start_date: 123456789, end_date: 987654321}]->(d)
"""

# Create driver session
with driver.session() as session:
  session.run(write_example_graph_query)
----
=====
====

=== Shorthand graph creation

We can use the following shorthand example in order to create our in-memory graph:

[.tabbed-example]
====
[.include-with-GDS-client]
=====
[source, python, subs=attributes+]
----
# Shorthand GDS create in-memory graph with native projection
shorthand_graph, result = gds.graph.project(
  "shorthand-example-graph",
  ["EngineeringManagement", "Developer"],
  ["MANAGES"]
)

# Prettify the first result
print(json.dumps(result, indent=2, sort_keys=True))
----
=====

[.include-with-Cypher]
=====
[source, cypher, subs=attributes+]
----
CALL gds.graph.project(
  'shorthand-example-graph',
  ['EngineeringManagement', 'Developer'],
  ['MANAGES']
) 
YIELD graphName, nodeCount, relationshipCount
RETURN *
----
=====

[.include-with-Python-driver]
=====
[source, python, subs=attributes+]
----
# Shorthand GDS create in-memory graph with Native Projection
shorthand_graph_create_query = """
CALL gds.graph.project(
  'shorthand-example-graph',
  ['EngineeringManagement', 'Developer'],
  ['MANAGES']
) 
YIELD graphName, nodeCount, relationshipCount
RETURN *
"""

# Create driver session
with driver.session() as session:
  # Run query
  result = session.run(shorthand_graph_create_query).data()
  # Prettify the first result
  print(json.dumps(result[0], indent=2, sort_keys=True))
----
=====
====

Using the short hand is great if we're only interested in the structure of the graph in which our algorithms run on.

You may want to transform the data, unify the structure or include properties as part of your analysis - this is where using the longform `gds.graph.project` can be useful.

=== Longform graph creation

Using the following example graph: 

```
(:EngineeringManagement {name: 'Alistair'})-
  [:MANAGES {start_date: 987654321}]->
  (:Developer {name: 'Leila'})<-
  [:MANAGES {start_date: 123456789, end_date: 987654321}]-
  (:EngineeringManagement {name: 'Jennifer'})
```

We can transform our example into the following structure: 

```
(:Person {first_name: 'Alistair'})-
  [:KNOWS {start_date: 987654321, end_date: 999999999}]-
  (:Person {first_name: 'Leila'})-
  [:KNOWS {start_date: 123456789, end_date: 987654321}]-
  (:Person {first_name: 'Jennifer'})
```

Below we'll transform the `:EngineeringManagement` & `:Developer` labels to be `:PersonEM` & `PersonM` respectively when projected into our in-memory graph.

The `MANAGES` relationship will also be switched to undirected so that each relationship is projected in both natural and reverse orientations.

We'll rename the `start_date` and `end_date` relationships properties to `start_date` & `end_date` to the in-memory graph. If however, there isn't anend_date available on the relationship, we'll default the value to be `999999999`.

There are lots of configuration options available as part of Node & Relationship projections: https://neo4j.com/docs/graph-data-science/current/management-ops/native-projection/#native-projection-syntax-relationship-projections[]

[.tabbed-example]
====
[.include-with-GDS-client]
=====
[source, python, subs=attributes+]
----
# Longform GDS create query
longform_graph, result = gds.graph.project(
  "longform-example-graph",
  {
    "PersonEM": {
      "label": "EngineeringManagement"
    },
    "PersonD": {
      "label": "Developer"
    }
  },
  {
    "KNOWS": {
      "type": "MANAGES",
      "orientation": "UNDIRECTED",
      "properties": {
        "start_date": {
          "property": "start_date"
        },
        "end_date": {
          "property": "end_date",
          "defaultValue": 999999999
        }
      }
    }
  }
)

# Prettify the result
print(json.dumps(result, indent=2, sort_keys=True))
----
=====

[.include-with-Cypher]
=====
[source, cypher, subs=attributes+]
----
CALL gds.graph.project(
  'longform-example-graph',
  {
    PersonEM: {
      label: 'EngineeringManagement'
    },
    PersonD: {
      label: 'Developer'
    }
  },
  {
    KNOWS: {
      type: 'MANAGES',
      orientation: 'UNDIRECTED',
      properties: {
        start_date: {
          property: 'start_date'
        },
        end_date: {
          property: 'end_date',
          defaultValue: 999999999
        }
      }
    }
  }
) 
YIELD graphName, nodeCount, relationshipCount
RETURN *
----
=====

[.include-with-Python-driver]
=====
[source, python, subs=attributes+]
----
# Longform GDS create query
longform_graph_create_query = """
CALL gds.graph.project(
  'longform-example-graph',
  {
    PersonEM: {
      label: 'EngineeringManagement'
    },
    PersonD: {
      label: 'Developer'
    }
  },
  {
    KNOWS: {
      type: 'MANAGES',
      orientation: 'UNDIRECTED',
      properties: {
        start_date: {
          property: 'start_date'
        },
        end_date: {
          property: 'end_date',
          defaultValue: 999999999
        }
      }
    }
  }
) 
YIELD graphName, nodeCount, relationshipCount
RETURN *
"""

# Create driver session
with driver.session() as session:
  # Run query
  result = session.run(longform_graph_create_query).data()
  # Prettify the first result
  print(json.dumps(result[0], indent=2, sort_keys=True))
----
=====
====

=== Cleanup

Run the following block of code to clean up the last example's data and in-memory graphs.

[.tabbed-example]
====
[.include-with-GDS-client]
=====
[source, python, subs=attributes+]
----
delete_example_graph_query = """
MATCH (example)
WHERE example:EngineeringManagement OR example:Developer
DETACH DELETE example
"""

gds.run_cypher(delete_example_graph_query)

gds.graph.drop(shorthand_graph)

gds.graph.drop(longform_graph)
----
=====

[.include-with-Cypher]
=====
[source, cypher, subs=attributes+]
----
MATCH (example)
WHERE example:EngineeringManagement OR example:Developer
DETACH DELETE example;

CALL gds.graph.drop('shorthand-example-graph');

CALL gds.graph.drop('longform-example-graph');
----
=====

[.include-with-Python-driver]
=====
[source, python, subs=attributes+]
----
delete_example_graph_query = """
MATCH (example)
WHERE example:EngineeringManagement OR example:Developer
DETACH DELETE example
"""

delete_shorthand_graph_query = """
CALL gds.graph.drop('shorthand-example-graph')
"""

delete_longform_graph_query = """
CALL gds.graph.drop('longform-example-graph')
"""

# Create driver session
with driver.session() as session:
  # Run query
  print(session.run(delete_example_graph_query).data())
  print(session.run(delete_shorthand_graph_query).data())
  print(session.run(delete_longform_graph_query).data())
----
=====
====

== References

=== Documentation
* https://neo4j.com/docs/graph-data-science/current/management-ops/graph-catalog-ops/#graph-catalog-ops[Graph catalog^]
* https://neo4j.com/docs/graph-data-science/current/management-ops/native-projection/#native-projection[Native projections^]
* https://neo4j.com/docs/graph-data-science/current/alpha-algorithms/graph-generation/#graph-generation[Graph generation^]
* https://neo4j.com/docs/graph-data-science[Neo4j GDSL documentation^]
* https://neo4j.com/docs/driver-manual/current/get-started/[Neo4j driver documentation^]
* https://neo4j.com/developer[Neo4j developer documentation^]

=== Cypher

* Learn more about the https://neo4j.com/docs/cypher-manual/current/[Cypher^] syntax
* The https://neo4j.com/docs/cypher-manual/current/[Cypher reference card^] is also a great resource for understanding how to use Cypher keywords

=== Modelling

* https://neo4j.com/developer/guide-data-modeling/[Data modelling guidelines^]
* https://neo4j.com/developer/modeling-designs/[Data modelling design^]
* https://neo4j.com/developer/graph-model-refactoring/[Refactoring a data model^]
