[[model-catalog]]
= Persisting and sharing machine learning models
:description: This page describes how to use the model catalog.

TIP: Follow along with a notebook in https://colab.research.google.com/drive/1EfICJ1T9Ey6jIQP4YlEcLRxGtpJVXx5E?usp=sharing[image:colab.svg[Colab,24] Google Colab^]

This tutorial shows how to train, save, publish and drop a machine learning model using the https://neo4j.com/docs/graph-data-science/2.0-preview/model-catalog/[Model Catalog].

include::partial$aurads/setup.adoc[]

== Create an example graph

We start by creating some basic graph data first.

[.tabbed-example]
====
[.include-with-GDS-client]
=====
[source, python, subs=attributes+]
----
gds.run_cypher("""
  MERGE ( dan:Person:ExampleData   {name: 'Dan',   age: 20, heightAndWeight: [185, 75]})
  MERGE ( annie:Person:ExampleData {name: 'Annie', age: 12, heightAndWeight: [124, 42]})
  MERGE ( matt:Person:ExampleData  {name: 'Matt',  age: 67, heightAndWeight: [170, 80]})
  MERGE ( jeff:Person:ExampleData  {name: 'Jeff',  age: 45, heightAndWeight: [192, 85]})
  MERGE ( brie:Person:ExampleData  {name: 'Brie',  age: 27, heightAndWeight: [176, 57]})
  MERGE ( elsa:Person:ExampleData  {name: 'Elsa',  age: 32, heightAndWeight: [158, 55]})
  MERGE ( john:Person:ExampleData  {name: 'John',  age: 35, heightAndWeight: [172, 76]})

  MERGE (dan)-[:KNOWS {relWeight: 1.0}]->(annie)
  MERGE (dan)-[:KNOWS {relWeight: 1.6}]->(matt)
  MERGE (annie)-[:KNOWS {relWeight: 0.1}]->(matt)
  MERGE (annie)-[:KNOWS {relWeight: 3.0}]->(jeff)
  MERGE (annie)-[:KNOWS {relWeight: 1.2}]->(brie)
  MERGE (matt)-[:KNOWS {relWeight: 10.0}]->(brie)
  MERGE (brie)-[:KNOWS {relWeight: 1.0}]->(elsa)
  MERGE (brie)-[:KNOWS {relWeight: 2.2}]->(jeff)
  MERGE (john)-[:KNOWS {relWeight: 5.0}]->(jeff)

  RETURN True AS exampleDataCreated
""")
----
=====

[.include-with-Cypher]
=====
[source, cypher, subs=attributes+]
----
MERGE ( dan:Person:ExampleData   {name: 'Dan',   age: 20, heightAndWeight: [185, 75]})
MERGE ( annie:Person:ExampleData {name: 'Annie', age: 12, heightAndWeight: [124, 42]})
MERGE ( matt:Person:ExampleData  {name: 'Matt',  age: 67, heightAndWeight: [170, 80]})
MERGE ( jeff:Person:ExampleData  {name: 'Jeff',  age: 45, heightAndWeight: [192, 85]})
MERGE ( brie:Person:ExampleData  {name: 'Brie',  age: 27, heightAndWeight: [176, 57]})
MERGE ( elsa:Person:ExampleData  {name: 'Elsa',  age: 32, heightAndWeight: [158, 55]})
MERGE ( john:Person:ExampleData  {name: 'John',  age: 35, heightAndWeight: [172, 76]})

MERGE (dan)-[:KNOWS {relWeight: 1.0}]->(annie)
MERGE (dan)-[:KNOWS {relWeight: 1.6}]->(matt)
MERGE (annie)-[:KNOWS {relWeight: 0.1}]->(matt)
MERGE (annie)-[:KNOWS {relWeight: 3.0}]->(jeff)
MERGE (annie)-[:KNOWS {relWeight: 1.2}]->(brie)
MERGE (matt)-[:KNOWS {relWeight: 10.0}]->(brie)
MERGE (brie)-[:KNOWS {relWeight: 1.0}]->(elsa)
MERGE (brie)-[:KNOWS {relWeight: 2.2}]->(jeff)
MERGE (john)-[:KNOWS {relWeight: 5.0}]->(jeff)

RETURN True AS exampleDataCreated
----
=====

[.include-with-Python-driver]
=====
[source, python, subs=attributes+]
----
# Cypher query
create_example_graph_on_disk_query = """
  MERGE ( dan:Person:ExampleData   {name: 'Dan',   age: 20, heightAndWeight: [185, 75]})
  MERGE ( annie:Person:ExampleData {name: 'Annie', age: 12, heightAndWeight: [124, 42]})
  MERGE ( matt:Person:ExampleData  {name: 'Matt',  age: 67, heightAndWeight: [170, 80]})
  MERGE ( jeff:Person:ExampleData  {name: 'Jeff',  age: 45, heightAndWeight: [192, 85]})
  MERGE ( brie:Person:ExampleData  {name: 'Brie',  age: 27, heightAndWeight: [176, 57]})
  MERGE ( elsa:Person:ExampleData  {name: 'Elsa',  age: 32, heightAndWeight: [158, 55]})
  MERGE ( john:Person:ExampleData  {name: 'John',  age: 35, heightAndWeight: [172, 76]})

  MERGE (dan)-[:KNOWS {relWeight: 1.0}]->(annie)
  MERGE (dan)-[:KNOWS {relWeight: 1.6}]->(matt)
  MERGE (annie)-[:KNOWS {relWeight: 0.1}]->(matt)
  MERGE (annie)-[:KNOWS {relWeight: 3.0}]->(jeff)
  MERGE (annie)-[:KNOWS {relWeight: 1.2}]->(brie)
  MERGE (matt)-[:KNOWS {relWeight: 10.0}]->(brie)
  MERGE (brie)-[:KNOWS {relWeight: 1.0}]->(elsa)
  MERGE (brie)-[:KNOWS {relWeight: 2.2}]->(jeff)
  MERGE (john)-[:KNOWS {relWeight: 5.0}]->(jeff)

  RETURN True AS exampleDataCreated
"""

# Create the driver session
with driver.session() as session:
  # Run query
  result = session.run(create_example_graph_on_disk_query).data()

  # Prettify the result
  print(json.dumps(result, indent=2, sort_keys=True))
----
=====
====

We then project an in-memory graph from the data just created.

[.tabbed-example]
====
[.include-with-GDS-client]
=====
[source, python, subs=attributes+]
----
g, result = gds.graph.project(
  "example_graph_for_graphsage",
  {
    "Person": {
      "label": "ExampleData",
      "properties": ["age", "heightAndWeight"]
    }
  }, 
  {
    "KNOWS": {
      "type": "KNOWS",
      "orientation": "UNDIRECTED",
      "properties": ["relWeight"]
    }
  }
)

print(json.dumps(result, indent=2, sort_keys=True))
----
=====

[.include-with-Cypher]
=====
[source, cypher, subs=attributes+]
----
CALL gds.graph.project(
  'example_graph_for_graphsage',
  {
    Person: {
      label: 'ExampleData',
      properties: ['age', 'heightAndWeight']
    }
  }, 
  {
    KNOWS: {
      type: 'KNOWS',
      orientation: 'UNDIRECTED',
      properties: ['relWeight']
    }
  }
)
----
=====

[.include-with-Python-driver]
=====
[source, python, subs=attributes+]
----
# Cypher query
create_example_graph_in_memory_query = """
  CALL gds.graph.project(
    'example_graph_for_graphsage',
    {
      Person: {
        label: 'ExampleData',
        properties: ['age', 'heightAndWeight']
      }
    }, 
    {
      KNOWS: {
        type: 'KNOWS',
        orientation: 'UNDIRECTED',
        properties: ['relWeight']
      }
    }
  )
"""

# Create the driver session
with driver.session() as session:
  # Run query
  result = session.run(create_example_graph_in_memory_query).data()
  
  # Prettify the result
  print(json.dumps(result, indent=2, sort_keys=True))
----
=====
====

== Training a model

Machine learning algorithms which support the `train` mode produce trained models which are stored in the Model Catalog. Similarly, `predict` procedures can use such trained models to produce predictions. In this example we train a model for the https://neo4j.com/docs/graph-data-science/2.0-preview/machine-learning/node-embeddings/graph-sage/[GraphSAGE algorithm^] using the `train` mode.

[.tabbed-example]
====
[.include-with-GDS-client]
=====
[source, python, subs=attributes+]
----
model, result = gds.beta.graphSage.train(
  g,
  modelName="example_graph_model_for_graphsage",
  featureProperties=["age", "heightAndWeight"],
  aggregator="mean",
  activationFunction="sigmoid",
  sampleSizes=[25, 10]
)
----
=====

[.include-with-Cypher]
=====
[source, cypher, subs=attributes+]
----
CALL gds.beta.graphSage.train(
 'example_graph_for_graphsage',
 {
   modelName: 'example_graph_model_for_graphsage',
   featureProperties: ['age', 'heightAndWeight'],
   aggregator: 'mean',
   activationFunction: 'sigmoid',
   sampleSizes: [25, 10]
 }
) YIELD modelInfo as info
RETURN
 info.name as modelName,
 info.metrics.didConverge as didConverge,
 info.metrics.ranEpochs as ranEpochs,
 info.metrics.epochLosses as epochLosses
----
=====

[.include-with-Python-driver]
=====
[source, python, subs=attributes+]
----
# Cypher query
train_graph_sage_on_in_memory_graph_query  = """
  CALL gds.beta.graphSage.train(
  'example_graph_for_graphsage',
  {
    modelName: 'example_graph_model_for_graphsage',
    featureProperties: ['age', 'heightAndWeight'],
    aggregator: 'mean',
    activationFunction: 'sigmoid',
    sampleSizes: [25, 10]
  }
  ) YIELD modelInfo as info
  RETURN
  info.name as modelName,
  info.metrics.didConverge as didConverge,
  info.metrics.ranEpochs as ranEpochs,
  info.metrics.epochLosses as epochLosses
"""

# Create the driver session
with driver.session() as session:
  # Run query
  result = session.run(train_graph_sage_on_in_memory_graph_query).data()

  # Prettify the result
  print(json.dumps(result, indent=2, sort_keys=True))
----
=====
====

== Viewing the model catalog

We can use the https://neo4j.com/docs/graph-data-science/2.0-preview/model-catalog/list/[`gds.beta.model.list`^] procedure to get information on all the models currently available in the catalog. Along with information on the graph schema, the model name, and the training configuration, the result of the call contains the following fields:

* `loaded`: flag denoting if the model is in memory (`true`) or available on disk (`false`)
* `stored`: flag denoting whether the model has been persisted to disk
* `shared`: flag denoting whether the model has been published, making it accessible to all users

[.tabbed-example]
====
[.include-with-GDS-client]
=====
[source, python, subs=attributes+]
----
results = gds.beta.model.list()

# Prettify the results
print(json.dumps(results, indent=2, sort_keys=True, default=default))
----
=====

[.include-with-Cypher]
=====
[source, cypher, subs=attributes+]
----
CALL gds.beta.model.list()
----
=====

[.include-with-Python-driver]
=====
[source, python, subs=attributes+]
----
# Cypher query
list_model_catalog_query  = """
  CALL gds.beta.model.list()
"""

# Create the driver session
with driver.session() as session:
  # Run query
  results = session.run(list_model_catalog_query).data()
  
  # Prettify the results
  print(json.dumps(results, indent=2, sort_keys=True, default=default))
----
=====
====

== Saving a model to disk

The https://neo4j.com/docs/graph-data-science/2.0-preview/model-catalog/store/[`gds.alpha.model.store`^] procedure can be used to persist a model to disk. This is useful both to keep models for later reuse and to free up memory.

[.tabbed-example]
====
[.include-with-GDS-client]
=====
[source, python, subs=attributes+]
----
result = gds.alpha.model.store(model)

print(json.dumps(result, indent=2, sort_keys=True))
----
=====

[.include-with-Cypher]
=====
[source, cypher, subs=attributes+]
----
CALL gds.alpha.model.store("example_graph_model_for_graphsage")
----
=====

[.include-with-Python-driver]
=====
[source, python, subs=attributes+]
----
# Cypher query
save_graph_sage_model_to_disk_query = """
  CALL gds.alpha.model.store("example_graph_model_for_graphsage")
"""

# Create the driver session
with driver.session() as session:
  # Run query
  result = session.run(save_graph_sage_model_to_disk_query).data()
  
  # Prettify the result
  print(json.dumps(result, indent=2, sort_keys=True))
----
=====
====

If we list the model catalog after persisting a model, we can see that the stored flag for that model has been set to `true`.

[.tabbed-example]
====
[.include-with-GDS-client]
=====
[source, python, subs=attributes+]
----
results = gds.beta.model.list()

print(json.dumps(results, indent=2, sort_keys=True, default=default))
----
=====

[.include-with-Cypher]
=====
[source, cypher, subs=attributes+]
----
CALL gds.beta.model.list()
----
=====

[.include-with-Python-driver]
=====
[source, python, subs=attributes+]
----
# Cypher query
list_model_catalog_query  = """
  CALL gds.beta.model.list()
"""

# Create the driver session
with driver.session() as session:
  # Run query
  results = session.run(list_model_catalog_query).data()

  # Prettify the results
  print(json.dumps(results, indent=2, sort_keys=True, default=default))
----
=====
====

== Sharing the model

WARNING: SECTION UNDER REVIEW

Allowing multiple users access to analyse and execute either on the same datasets or with the same models is handy.

IMPORTANT: A model can only be shared with other users of the same AuraDS instance.

To do this we need to create another user, more information about the cypher syntax can be found https://neo4j.com/docs/cypher-manual/current/administration/security/users-and-roles/[here]

=== Creating another instance user

Within an instance we can https://neo4j.com/docs/cypher-manual/current/administration/security/users-and-roles/#administration-security-users-create[create another user] to simulate a colleague that we might want to share the model with.

[.tabbed-example]
====
[.include-with-GDS-client]
=====
[source, python, subs=attributes+]
----
gds.set_database("system")

gds.run_cypher("""
  CREATE USER testUser IF NOT EXISTS
  SET PASSWORD 'test'
  SET PASSWORD CHANGE NOT REQUIRED
""")
----
=====

[.include-with-Cypher]
=====
[source, cypher, subs=attributes+]
----
:connect system

CREATE USER testUser IF NOT EXISTS
SET PASSWORD 'test'
SET PASSWORD CHANGE NOT REQUIRED
----
=====

[.include-with-Python-driver]
=====
[source, python, subs=attributes+]
----
# Cypher query
create_a_new_user_query = """
  CREATE USER testUser IF NOT EXISTS
  SET PASSWORD 'test'
  SET PASSWORD CHANGE NOT REQUIRED
"""

# Create the driver session using the 'system' database
with driver.session(database='system') as session:
  # Run query
  result = session.run(create_a_new_user_query).data()

  # Prettify the result
  print(json.dumps(result, indent=2, sort_keys=True))
----
=====
====

=== Publishing the model

To publish the model we need to use https://neo4j.com/docs/graph-data-science/current/model-catalog/model-catalog/#model-catalog-publish-ops[gds.alpha.model.publish] to enable other users to view the model we've created.

When we publish a model, the model's name is appended with `\_public` at the end.

[.tabbed-example]
====
[.include-with-GDS-client]
=====
[source, python, subs=attributes+]
----
gds.set_database("neo4j")
model_public = gds.alpha.model.publish(model)

print(json.dumps(result, indent=2, sort_keys=True, default=default))
----
=====

[.include-with-Cypher]
=====
[source, cypher, subs=attributes+]
----
:connect neo4j

CALL gds.alpha.model.publish('example_graph_model_for_graphsage')
----
=====

[.include-with-Python-driver]
=====
[source, python, subs=attributes+]
----
# Cypher query
publish_graph_sage_model_to_disk_query  = """
  CALL gds.alpha.model.publish('example_graph_model_for_graphsage')
"""

# Create the driver session
with driver.session() as session:
  # Run query
  result = session.run(publish_graph_sage_model_to_disk_query).data()

  # Prettify the result
  print(json.dumps(result, indent=2, sort_keys=True, default=default))
----
=====
====

=== Viewing the model as another user

Below we'll create a new driver session using the test user credentials.

We'll then list the model catalog and see that we have access to the model that we published with the other user.

[.tabbed-example]
====
[.include-with-GDS-client]
=====
[source, python, subs=attributes+]
----
test_user_gds = GraphDataScience(
  AURA_CONNECTION_URI,
  auth=("testUser", "test"),
  aura_ds=True
)

results = test_user_gds.beta.model.list()

print(json.dumps(results, indent=2, sort_keys=True, default=default))
----
=====

[.include-with-Cypher]
=====
[source, cypher, subs=attributes+]
----
// First, open a new Cypher shell with the following command:
//
// ./cypher-shell -a $AURA_CONNECTION_URI -u testUser -p test

CALL gds.beta.model.list()
----
=====

[.include-with-Python-driver]
=====
[source, python, subs=attributes+]
----
test_user_driver = GraphDatabase.driver(AURA_CONNECTION_URI, auth=("testUser", "test"))

# Create the driver session
with test_user_driver.session() as session:
  # Run query
  results = session.run(list_model_catalog_query).data()

  # Prettify the results
  print(json.dumps(results, indent=2, sort_keys=True, default=default))
----
=====
====

== Cleanup

After going through the tutorial, the in-memory graphs, the data in the Neo4j database, the models, and the test user can all be deleted.

[.tabbed-example]
====
[.include-with-GDS-client]
=====
[source, python, subs=attributes+]
----
# Delete the example dataset
gds.run_cypher("""
  MATCH (example:ExampleData)
  DETACH DELETE example
""")

# Delete the projected graph from memory
gds.graph.drop(g)

# Drop the model from memory
gds.beta.model.drop(model_public)

# Delete the model from disk
gds.alpha.model.delete(model_public)

# Switch to the system database and delete the example user
gds.set_database("system")

gds.run_cypher("""
  DROP USER testUser
""")
----
=====

[.include-with-Cypher]
=====
[source, cypher, subs=attributes+]
----
// Delete the example dataset from the database
MATCH (example:ExampleData)
DETACH DELETE example;

// Delete the projected graph from memory
CALL gds.graph.drop("example_graph_for_graphsage");

// Drop the model from memory
CALL gds.beta.model.drop("example_graph_model_for_graphsage_public");

// Delete the model from disk
CALL gds.alpha.model.delete("example_graph_model_for_graphsage_public");

// Delete the example user
DROP USER testUser;
----
=====

[.include-with-Python-driver]
=====
[source, python, subs=attributes+]
----
# Delete the example dataset from the database
delete_example_graph_query = """
  MATCH (example:ExampleData)
  DETACH DELETE example
"""

# Delete the projected graph from memory
drop_in_memory_graph_query = """
  CALL gds.graph.drop("example_graph_for_graphsage")
"""

# Drop the model from memory
drop_example_models_query = """
  CALL gds.beta.model.drop("example_graph_model_for_graphsage_public")
"""

# Delete the model from disk
delete_example_models_query = """
  CALL gds.alpha.model.delete("example_graph_model_for_graphsage_public")
"""

# Delete the example user
drop_example_user_query = """
  DROP USER testUser
"""

# Create the driver session
with driver.session() as session:
  # Run queries
  print(session.run(delete_example_graph_query).data())
  print(session.run(drop_in_memory_graph_query).data())
  print(session.run(drop_example_models_query).data())
  print(session.run(delete_example_models_query).data())

# Create another driver session on the system database
# to drop the test user
with driver.session(database='system') as session:
  print(session.run(drop_example_user_query).data())

driver.close()
test_user_driver.close()
----
=====
====

== References

=== Documentation
* https://neo4j.com/docs/graph-data-science/current/management-ops/graph-catalog-ops/#graph-catalog-ops[Graph catalog^]
* https://neo4j.com/docs/graph-data-science/current/management-ops/native-projection/#native-projection[Native projections^]
* https://neo4j.com/docs/graph-data-science/current/alpha-algorithms/graph-generation/#graph-generation[Graph generation^]
* https://neo4j.com/docs/graph-data-science[Neo4j GDSL documentation^]
* https://neo4j.com/docs/driver-manual/current/get-started/[Neo4j driver documentation^]
* https://neo4j.com/developer[Neo4j developer documentation^]

=== Cypher

* Learn more about the https://neo4j.com/docs/cypher-manual/current/[Cypher^] syntax
* The https://neo4j.com/docs/cypher-manual/current/[Cypher reference card^] is also a great resource for understanding how to use Cypher keywords

=== Modelling

* https://neo4j.com/developer/guide-data-modeling/[Data modelling guidelines^]
* https://neo4j.com/developer/modeling-designs/[Data modelling design^]
* https://neo4j.com/developer/graph-model-refactoring/[Refactoring a data model^]
