[[aurads-importing-data]]
= Importing data
:description: This page describes how to get data into a Neo4j AuraDS database.

This page describes the various ways you can get data into a Neo4j AuraDS instance.

[NOTE]
====
*Note:* The process of importing or loading data requires you to xref:aurads/getting-started/create-database.adoc[create an AuraDS instance] beforehand.
====

If you have data in an existing Neo4j database, you can follow the instructions in <<_importing_an_existing_neo4j_database>>.

If your data exists outside of Neo4j as a *_.csv_* file, you can follow the instructions in <<_loading_csv_data>>.

== Importing an existing Neo4j database

There are two ways you can import data from an existing Neo4j database into an AuraDS instance.

The easiest way is to export a Neo4j database as a *_.dump_* file and use the <<_import_database>> process.
This process, however, only works for *_.dump_* files under 4GB. 

If the size of the *_.dump_* file exported from a database is greater than 4GB, you must use the <<_push_to_cloud>> method.

=== Import database

To import a *_.dump_* file under 4GB:

. Navigate to the https://console.neo4j.io/[Neo4j Aura Console] in your browser.
. Select the name of the database you want to import the data.
. Select the *IMPORT DATABASE* tab.
. Drag and drop your *_.dump_* file into the provided window or select *Select a .dump file* and select your file.
. Select *Upload*.

When the upload is complete, the database goes into a 'Loading' state as the dump is applied. 
Once this has finished, the database returns to its 'Running' state; and the data is ready.

=== Push-to-cloud

`Push-to-cloud` is a Neo4j Admin command that you can run to upload the contents of a Neo4j database into an AuraDS instance, regardless of the database's size.

Instructions on running the command, which differ depending on how you have administered your database, can be found by selecting the *Import* section from the sidebar menu of the Aura Console or navigating directly to the https://console.neo4j.io/#import-instructions[Import page].

When prompted that the process is complete, the data is ready.

== Loading CSV data

You can load data from a *_.csv_* file into an AuraDS instance with the https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/[`LOAD CSV`] Cypher statement within Neo4j Browser.
For instructions on how to open an AuraDS instance with Neo4j Browser, see xref:aurads/getting-started/access-database.adoc[].

There are some limitations to consider when loading a *_.csv_* file into an AuraDS instance:

* For security reasons, you must host your *_.csv_* file on a publicly accessible HTTP or HTTPS server. Examples of such servers include GitHub, Google Drive, and Dropbox.

* The `LOAD CSV` command is built to handle small to medium-sized data sets, such as anything up to 10 million nodes and relationships. You should avoid using this command for any data sets exceeding this limit.
