[[connecting-python]]
= Connecting with Python
:description: This page describes how to connect to AuraDS using Python.

TIP: Follow along with a notebook in https://colab.research.google.com/drive/10XK5_fyNURb1u_gvD_lkt7qQvIxzAhnJ?usp=sharing[image:colab.svg[Colab,24] Google Colab^]

This tutorial shows how to interact with AuraDS using the https://neo4j.com/docs/graph-data-science/2.0-preview/python-client/[Graph Data Science client] or the https://neo4j.com/docs/driver-manual/current/get-started[Python Driver].

NOTE: You can switch between the client and the driver in each example using the appropriate tab.

== Connection details

The connection to an instance requires three inputs:

* Instance connection URI
* Instance username
* Instance password

The username (default `neo4j`) and password are generated when the instance is created, while the instance connection URI can be found on the created instance main page. Copy and paste them as values of the relevant variables (`AURA_USERNAME`, `AURA_PASSWORD`, and `AURA_CONNECTION_URI` respectively) in the <<_import_and_setup>> section.

== Installation

[.tabbed-example]
====
[.include-with-GDS-client]
=====
To install the Graph Data Science client:

[source, shell]
----
pip install graphdatascience
----

Visit https://pypi.org/project/graphdatascience to find the latest stable version of the client.
=====

[.include-with-Python-driver]
=====
To install the Python driver:

[source, shell]
----
pip install neo4j
----

Visit https://pypi.org/project/neo4j to find the latest stable version of the driver.
=====
====

== Import and setup

[.tabbed-example]
====
[.include-with-GDS-client]
=====
The client is imported as the `GraphDataScience` class:

[source, python]
----
# Driver import
from graphdatascience import GraphDataScience
----

Constructing the client instance requires the connection URI (`AURA_CONNECTION_URI`) and the authentication information (`AURA_USERNAME` and `AURA_PASSWORD`) as defined in the <<_connection_details>> section above.

The `aura_ds=True` constructor argument should be used to have the recommended non-default configuration settings of the Python Driver applied automatically.

[source, python]
----
# Connection details
AURA_CONNECTION_URI = "neo4j+s://xxxxxxxx.databases.neo4j.io"
AURA_USERNAME = "neo4j"
AURA_PASSWORD = ""

# Client instantiation
gds = GraphDataScience(
  AURA_CONNECTION_URI,
  auth=(AURA_USERNAME, AURA_PASSWORD),
  aura_ds=True
)
----
=====

[.include-with-Python-driver]
=====
The driver is imported as the `GraphDatabase` class:

[source, python]
----
# Driver import
from neo4j import GraphDatabase
----

Constructing a driver instance requires the connection URI (`AURA_CONNECTION_URI`) and the authentication information (`AURA_USERNAME` and `AURA_PASSWORD`) as defined in the <<_connection_details>> section above.

[source, python]
----
# Connection details
AURA_CONNECTION_URI = "neo4j+s://xxxxxxxx.databases.neo4j.io"
AURA_USERNAME = "neo4j"
AURA_PASSWORD = ""

# Driver instantiation
driver = GraphDatabase.driver(
  AURA_CONNECTION_URI, 
  auth=(AURA_USERNAME, AURA_PASSWORD)
)
----
=====
====

== Running a query

[.tabbed-example]
====
[.include-with-GDS-client]
=====
Once created, the client can be used to run two example queries.

The first query returns the version of GDS running on the database:

[source, python]
----
# Call a GDS method directly
print(gds.version())
----

The second query gets the procedures available in the library and lists five of them:

[source, python]
----
# Call a GDS method directly
print(gds.list())
----
=====

[.include-with-Python-driver]
=====
Once created, the driver can be used to run two example queries.

The first query returns the version of GDS running on the database:

[source, python]
----
# Cypher query
gds_version_query = """
RETURN gds.version() AS version
"""

# Create a driver session
with driver.session() as session:
  # Use .data() to access the results array
  results = session.run(gds_version_query).data()
  print(results)
----

The second query gets the procedures available in the library and lists five of them:

[source, python]
----
import json

list_all_gds_procedures_query = """
CALL gds.list()
"""

# Create a driver session
with driver.session() as session:
  # Use .data() to access the results array
  results = session.run(list_all_gds_procedures_query).data()
  print(json.dumps(results[:5], indent=2))
----
=====
====

== Closing the connection

[.tabbed-example]
====
[.include-with-GDS-client]
=====
The GDS client releases the connection when the object is deleted.
=====

[.include-with-Python-driver]
=====
The driver connection should be closed when no longer needed.

[source, python]
----
# Close the driver connection
driver.close()
----
=====
====

== References

=== Documentation
* https://neo4j.com/docs/graph-data-science[Neo4j GDSL documentation^]
* https://neo4j.com/docs/driver-manual/current/get-started/[Neo4j driver documentation^]
* https://neo4j.com/developer[Neo4j developer documentation^]

=== Cypher

* Learn more about the https://neo4j.com/docs/cypher-manual/current/[Cypher^] syntax
* The https://neo4j.com/docs/cypher-manual/current/[Cypher reference card^] is also a great resource for understanding how to use Cypher keywords

=== Modelling

* https://neo4j.com/developer/guide-data-modeling/[Data modelling guidelines^]
* https://neo4j.com/developer/modeling-designs/[Data modelling design^]
* https://neo4j.com/developer/graph-model-refactoring/[Refactoring a data model^]
