[[connecting-python]]
= Connecting with Python
:description: This page describes how to connect to AuraDS using Python.

TIP: Follow along with a notebook in https://colab.research.google.com/drive/1o_71IwikMvZcg5_B69pTK6rrMLpi-hl_?usp=sharing[image:colab.svg[Colab,24] Google Colab^]
(driver: https://colab.research.google.com/drive/10XK5_fyNURb1u_gvD_lkt7qQvIxzAhnJ?usp=sharing[image:colab.svg[Colab,24] Google Colab^])

This tutorial shows how to interact with AuraDS using the https://neo4j.com/docs/graph-data-science/2.0-preview/python-client/[Graph Data Science client] or the https://neo4j.com/docs/driver-manual/current/get-started[Python Driver]. 

A running AuraDS instance must be available along with access credentials (generated in the xref:aurads/create-instance.adoc[] section) and its connection URI (found in the instance detail pageg starting with `neo4j+s://`).

NOTE: You can switch between the client and the driver in each example using the appropriate tab.

== Installation

[.tabbed-example]
====
[.include-with-GDS-client]
=====
The Graph Data Science client can be installed with `pip`:

[source, shell]
----
pip install graphdatascience
----

The latest stable version of the client can be found on https://pypi.org/project/graphdatascience[PyPI].
=====

[.include-with-Python-driver]
=====
The Python driver can be installed with `pip`:

[source, shell]
----
pip install neo4j
----

The latest stable version of the driver can be found on https://pypi.org/project/neo4j[PyPI].
=====
====

== Import and setup

[.tabbed-example]
====
[.include-with-GDS-client]
=====
The client is imported as the `GraphDataScience` class:

[source, python]
----
# Driver import
from graphdatascience import GraphDataScience
----

The `aura_ds=True` constructor argument should be used to have the recommended non-default configuration settings of the Python Driver applied automatically.

[source, python]
----
# Connection details
AURA_CONNECTION_URI = "neo4j+s://xxxxxxxx.databases.neo4j.io"
AURA_USERNAME = "neo4j"
AURA_PASSWORD = ""

# Client instantiation
gds = GraphDataScience(
  AURA_CONNECTION_URI,
  auth=(AURA_USERNAME, AURA_PASSWORD),
  aura_ds=True
)
----
=====

[.include-with-Python-driver]
=====
The driver is imported as the `GraphDatabase` class:

[source, python]
----
# Driver import
from neo4j import GraphDatabase
----

Constructing a driver instance requires the connection URI (`AURA_CONNECTION_URI`) and the authentication information (`AURA_USERNAME` and `AURA_PASSWORD`) as defined in the <<_connection_details>> section above.

[source, python]
----
# Connection details
AURA_CONNECTION_URI = "neo4j+s://xxxxxxxx.databases.neo4j.io"
AURA_USERNAME = "neo4j"
AURA_PASSWORD = ""

# Driver instantiation
driver = GraphDatabase.driver(
  AURA_CONNECTION_URI, 
  auth=(AURA_USERNAME, AURA_PASSWORD)
)
----
=====
====

== Running a query

Once created, the client can be used to run two example queries.

The first query returns the version of GDS running on the database:

[.tabbed-example]
====
[.include-with-GDS-client]
=====
[source, python]
----
# Call a GDS method directly
print(gds.version())
----
=====

[.include-with-Python-driver]
=====
The first query returns the version of GDS running on the database:

[source, python]
----
# Cypher query
gds_version_query = """
RETURN gds.version() AS version
"""

# Create a driver session
with driver.session() as session:
  # Use .data() to access the results array
  results = session.run(gds_version_query).data()
  print(results)
----
=====
====

The second query retrieves the procedures available in the library and lists five of them:

[.tabbed-example]
====
[.include-with-GDS-client]
=====
[source, python]
----
# Import the json module for prettier visualization
import json

# Assign the result of the client call to a variable
results = gds.list()

# Print the prettified result
print(json.dumps(results[:5], indent=2))
----
=====

[.include-with-Python-driver]
=====
[source, python]
----
# Import the json module for prettier visualization
import json

# Cypher query
list_all_gds_procedures_query = """
CALL gds.list()
"""

# Create a driver session
with driver.session() as session:
  # Use .data() to access the results array
  results = session.run(list_all_gds_procedures_query).data()
  
  # Print the prettified result
  print(json.dumps(results[:5], indent=2))
----
=====
====

== Closing the connection

[.tabbed-example]
====
[.include-with-GDS-client]
=====
The GDS client automatically closes the connection when the object is deleted.
=====

[.include-with-Python-driver]
=====
The driver connection should be closed when no longer needed.

[source, python]
----
# Close the driver connection
driver.close()
----
=====
====

== References

=== Documentation
* https://neo4j.com/docs/graph-data-science[Neo4j GDSL documentation^]
* https://neo4j.com/docs/driver-manual/current/get-started/[Neo4j driver documentation^]
* https://neo4j.com/developer[Neo4j developer documentation^]

=== Cypher

* Learn more about the https://neo4j.com/docs/cypher-manual/current/[Cypher^] syntax
* The https://neo4j.com/docs/cypher-manual/current/[Cypher reference card^] is also a great resource for understanding how to use Cypher keywords

=== Modelling

* https://neo4j.com/developer/guide-data-modeling/[Data modelling guidelines^]
* https://neo4j.com/developer/modeling-designs/[Data modelling design^]
* https://neo4j.com/developer/graph-model-refactoring/[Refactoring a data model^]
