[[aura-db-actions]]
= Database actions
:description: This page describes how to resize, clone, pause, resume, delete and rename an AuraDB database.

You can perform several database actions from an AuraDB database card on the https://console.neo4j.io/[Neo4j Aura Console] homepage.

== Renaming a database

You can change the name of an existing database by using the *Rename* action.

To rename a database:

. Select the ellipsis (...) on the database you want to rename.
. Select *Rename* from the resulting menu.
. Enter a new name for the database.
. Select *Rename*.

== Resizing a database

label:Enterprise[]
label:Professional[]

You can change the size of an existing database by using the *Resize* action.

To resize a database:

. Select the ellipsis (...) on the database you want to resize.
. Select *Resize* from the resulting menu.
. Select the new size you want your database to be.
. Tick the *I understand* checkbox and select *Submit*.

A database remains available during the resize operation.

== Pausing a database

You can pause a database during periods where you don't need it and resume at any time.

To pause a database:

. Select the pause icon on the database you want to pause.
. Tick the *I understand* checkbox and select *Pause* to confirm.

[NOTE]
====
Paused databases run at a discounted rate compared to standard consumption, as outlined in the confirmation window.
You can pause a database for up to 30 days, after which point AuraDB automatically resumes the database.
====

=== Resuming a paused database

Once a database is paused, you can select the play icon to resume the database. 

[WARNING]
====
AuraDB Free databases are paused automatically after 72 hours of inactivity. footnote:[Inactivity is when you perform no queries on the database.]

If an AuraDB Free database remains paused for more than 90 days, AuraDB will delete the database, and all information will be lost.
====

== Cloning a database

You can clone a database into a new or existing one.

To clone to a new database:

. Select the ellipsis (...) on the database you want to clone.
. Select *Clone To New* from the resulting menu.
. Set your desired settings for the new database.
For more information on database settings, see xref:getting-started/create-database.adoc[].
. Tick the *I understand* checkbox and select *Clone Database*.

To clone to an existing database:

. Select the ellipsis (...) on the database you want to clone.
. Select *Clone To Existing* from the resulting menu.
. Set a *Name* for the new database and select the existing database you want to clone to from the dropdown.
. Tick the *I understand* checkbox and select *Clone Database*.

[WARNING]
====
You can only clone to an existing database if it is equal or greater in size than the database you are cloning.

You cannot clone to a free database, and cloning from a free database requires you to clone into a paid, professional database.
====

== Deleting a database

You can delete a database if you no longer want to be billed for it.

To delete a database:

. Select the red trashcan icon on the database you want to delete.
. Type the exact name of the database (as instructed) to confirm your decision, and select *Destroy*.

[WARNING]
====
*Warning:*
There is no way to recover data from a deleted AuraDB database.
====
