[[aura-db-settings]]
= Database settings

The *SETTINGS* tab within an Aura database shows a list of administrative database options.

To access the *SETTINGS* tab:

. Navigate to the https://console.neo4j.io/[Neo4j Aura Console] in your browser.
. Select the name of the database you want to access.
. Select the *SETTINGS* tab.

== Resizing a database

You can change the size of an existing database by using the *Resize* option.

To resize a database:

. Navigate to the *SETTINGS* tab of the database you want to resize.
. Select *Resize* below *Database Capacity*.
. Select the new size you want your database to be.
. Tick the *I understand* checkbox and select *Submit*.

A database remains available during the resize operation.

== Cloning a database label:Enterprise-only[]

You can clone an existing database into a new one using the *Clone* option. The advantage this has over the xref:managing-databases/backup-restore-export.adoc#_backup_and_export[Create database from snapshot action] is the ability to select a new region.

To clone a database:

. Navigate to the *SETTINGS* tab of the database you want to clone.
. Select *Clone*.
. Set your desired settings for the new database.
For more information on database settings, see xref:getting-started/index.adoc#_creating_a_database[Creating a database].
. Tick the *I understand* checkbox and select *Clone Database*.

== Deleting a database

You can delete a database if you no longer want to be billed for it. 

To delete a database:

. Navigate to the *SETTINGS* tab of the database you want to resize.
. Select *Delete* below *Delete Database*.
. Type DESTROY to confirm your decision and select *Destroy*.

[WARNING]
====
*Warning:*
There is no way to recover data from a deleted Aura database. 
====