[[aura-db-settings]]
= Database settings
:description: This page describes how to resize, clone, and delete an Aura database.

The *SETTINGS* tab within an AuraDB database shows a list of administrative database options.

To access the *SETTINGS* tab:

. Navigate to the https://console.neo4j.io/[Neo4j Aura Console] in your browser.
. Select the name of the database you want to access.
. Select the *SETTINGS* tab.

== Resizing a database

You can change the size of an existing database by using the *Resize* option.

To resize a database:

. Navigate to the *SETTINGS* tab of the database you want to resize.
. Select *Resize* below *Database Capacity*.
. Select the new size you want your database to be.
. Tick the *I understand* checkbox and select *Submit*.

A database remains available during the resize operation.

== Pausing a database
label:Professional[]
label:Enterprise[]

You can pause a database during periods where you don’t need it and resume at any time.

To pause a database:

. Navigate to the *SETTINGS* tab of the database you want to pause.
. Select *Pause* below *Pause Database*.
. Tick the *I understand* checkbox and select *Pause* to confirm.

The database begins pausing, and a *Resume* button replaces the *Pause* button.

[NOTE]
====
Paused databases run at a discounted rate compared to standard consumption as outlined in the confirmation window.
You can pause a database for up to 30 days, after which point AuraDB automatically resumes the database.
====

== Resuming a database

[.tabbed-example]
====
[.include-with-free]
=====

[NOTE]
======
AuraDB Free databases become paused automatically after 72 hours of inactivity. 
footnote:[Inactivity is when you perform no queries on the database.]
======

To resume a database:

. Navigate to the https://console.neo4j.io/[Neo4j Aura Console] in your browser.
. Select the *Resume* button on the database you want to resume.

[WARNING]
======
AuraDB deletes paused AuraDB Free databases after 90 days.
======

=====

[.include-with-professional]
=====

To resume a database: 

. Navigate to the *SETTINGS* tab of the database you want to resume.
. Select *Resume* below *Pause Database*.
. Tick the *I understand* checkbox and select *Resume* to confirm.

The database begins resuming, which may take a few minutes.

Alternatively, you can select the *Resume* button on the database you want to resume directly from the https://console.neo4j.io/[Neo4j Aura Console].

=====

[.include-with-enterprise]
=====

To resume a database: 

. Navigate to the *SETTINGS* tab of the database you want to resume.
. Select *Resume* below *Pause Database*.
. Tick the *I understand* checkbox and select *Resume* to confirm.

The database begins resuming, which may take a few minutes.

Alternatively, you can select the *Resume* button on the database you want to resume directly from the https://console.neo4j.io/[Neo4j Aura Console].

=====
====

== Cloning a database 
label:Enterprise-only[]

You can clone an existing database into a new one using the *Clone* option. 
The advantage this has over the xref:managing-databases/backup-restore-export.adoc#_backup_and_export[Create database from snapshot action] is the ability to select a new region.

To clone a database:

. Navigate to the *SETTINGS* tab of the database you want to clone.
. Select *Clone*.
. Set your desired settings for the new database.
For more information on database settings, see xref:getting-started/create-database.adoc[].
. Tick the *I understand* checkbox and select *Clone Database*.

== Deleting a database

You can delete a database if you no longer want to be billed for it. 

To delete a database:

. Navigate to the *SETTINGS* tab of the database you want to resize.
. Select *Delete* below *Delete Database*.
. Type DESTROY to confirm your decision and select *Destroy*.

[WARNING]
====
*Warning:*
There is no way to recover data from a deleted AuraDB database. 
====
