[[aurads-monitoring]]
= Monitoring

You can monitor the following metrics of an AuraDB database from the *METRICS* tab:

* *CPU Usage (%)* - The amount of CPU used by the database as a percentage.
* *Storage Used (%)* - The amount of disk storage space used by the database as a percentage.
* *Heap Usage (%)* - The amount of Java Virtual Machine (JVM) memory used by the database as a percentage.
* *Out of Memory Errors* - The number of Out of Memory (OOM) errors encountered by the database.
* *Garbage Collection Time (%)* - The amount of time the database spends reclaiming heap space as a percentage.

[NOTE]
====
More information on each metric, as well as suggestions for managing them, can be found within the *METRICS* tab itself.
====

When viewing metrics, you can select from the following timeframes:

* 6 hours
* 24 hours
* 3 days
* 7 days
* 30 days

To access the *METRICS* tab:

. Navigate to the https://console.neo4j.io/[Neo4j Aura Console] in your browser.
. Select the name of the database you want to access.
. Select the *METRICS* tab.