:description: This section gives a short introduction to the Explore tool.
[[explore-introduction]]
= Explore

The Explore tool, powered by Neo4j Bloom, is a graph exploration tool for visually interacting with graph data.

A graph puts information into context.
People, places, and things.
Products, services, and accounts.
Transactions, identities, and events.
Explore shows the patterns you intuitively know are there in your data, and reveals new patterns you may not have expected.

[[explore-features]]

The core set of Explore features are:

* *Perspective* - the lens through which you view graph data, can be customized for different business purposes.
See xref:explore/explore-perspectives/perspectives.adoc[] for more information.
* *Visualization* - high performance, GPU-powered physics and rendering.
* *Exploration* - directly interacts with the data to explore connections and details.
* *Inspection* - see all the record details and browse to connected records.
* *Editing* - create records, connect data, update information.
* *Search* - find information, using advanced near-natural language Search phrases.

Explore exists as a standalone tool as well, _Neo4j Bloom_.
Most features are identical, but some differences exist.
See the full documentation link:{neo4j-docs-base-uri}/bloom-user-guide/current[Neo4j Bloom] for more information.