// Read a json file containing Aura tier information and output an asciidoc table.
    
const fs = require('fs')
const path = require('path')

// module.exports.register = function ({ config }) {

//     const {defaultLogLevel = 'info' } = config

//     const logger = this.getLogger('aura-regions', defaultLogLevel)



//     this.on('content-aggregated', ({ config }) => {

//     })

// }

// local file for now - use remote file in production
const regionsJSON = require('./regions.json')

const output = {}

const newLine = '\n'
const tabbedHeader = `[.tabbed-example]${newLine}${newLine}====${newLine}${newLine}`
const tabbedEnd = `====${newLine}`
const listDelimiter = '======'
const listItemSymbol = '** '

// collect the region.csp values
const cspSet = new Set()
for (const region of regionsJSON.regions) {
  cspSet.add(region.csp)
}

// collect the tiers
const tierSet = new Set()
for (const region of regionsJSON.regions) {
    for (const [key, value] of Object.entries(region.tiers)) {
        tierSet.add(key)
    }
}

for (const csp of cspSet) {
    output[csp] = {
        header: `== ${csp} Regions by Aura tier${newLine}${newLine}`,
        tiers: {}
    }
    for (const tier of tierSet) {
        // split the tier string at the underscore
        const tierParts = tier.split('_')
        // in the second part, insert a dash between any lowercase letter followed by an uppercase letter
        const formattedTier = tierParts[0] + '-' + tierParts[1].replace(/([a-z])([A-Z])/g, '$1-$2')

        output[csp].tiers[tier] = {
            displayName: tier.replaceAll('_', ' '),
            regions: [],
            asciidocRole: `[.include-with-${formattedTier}]${newLine}`,
            asciidocContent: ''
        }
    }
}

for (const region of regionsJSON.regions) {

    if (region.status !== 'GA') continue

    // for every tier in region.tiers, if the value is true, add the region.id to output[csp][tier]
    for (const [key, value] of Object.entries(region.tiers)) {
        if (value === true) {
            output[region.csp].tiers[key].regions.push(region.display_name)
            output[region.csp].tiers[key].asciidocContent += `${listItemSymbol}${region.display_name}${newLine}`
        }
    }

}

let adoc = ''

cspSet.forEach(csp => {
    adoc += (output[csp].header)
    adoc += tabbedHeader
    for (const tier of tierSet) {
        adoc += output[csp].tiers[tier].asciidocRole + listDelimiter + newLine + output[csp].tiers[tier].asciidocContent + listDelimiter + newLine + newLine
    }
    adoc += tabbedEnd
})

const dir = path.join(__dirname, '..', 'modules', 'root', 'partials', 'scp-tiers.adoc')

fs.writeFileSync(dir,`// This file is auto-generated by scripts/regions.js
// Do not edit!
${adoc}`)
