[[aura-access-database]]
= Accessing a database
:description: This page describes how to access a database using Neo4j Aura.

With a database created, the next step is to access it.

There are a few different methods of accessing a database in Neo4j Aura:

* <<_neo4j_browser>> - A browser-based interface for querying and viewing data in a database with rudimentary visualization.
* <<_neo4j_bloom>> - A graph exploration application for visually interacting with graph data.
* <<_neo4j_desktop>> - An installable desktop application used to manage local and cloud databases.

[TIP]
====
*Tip:* For first-time users, we recommend using Neo4j Browser.
====

== Neo4j Browser

To open a database with Neo4j Browser:

. Navigate to the https://console.neo4j.io/[Neo4j Aura Console] in your browser.
. Select the *Open with* dropdown menu on the database you want to open.
. Select *Neo4j Browser* from the dropdown menu.
. Enter the *Username* and *Password* credentials in the Neo4j Browser window that opens. 
These are the same credentials you stored when xref:getting-started/create-database.adoc[creating the database].
. Select *Connect*.

Once you have successfully connected, there are built-in guides you can complete to familiarize yourself with Neo4j Browser.

For more information on using Neo4j Browser, please see the https://neo4j.com/docs/browser-manual/current/[Browser manual].

== Neo4j Bloom

To open a database with Neo4j Bloom:

. Navigate to the https://console.neo4j.io/[Neo4j Aura Console] in your browser.
. Select the *Open with* dropdown menu on the database you want to open.
. Select *Neo4j Bloom* from the dropdown menu.
. Enter the *Username* and *Password* credentials in the Neo4j Browser window that opens. 
These are the same credentials you stored when xref:getting-started/create-database.adoc[creating the database].
. Select *Connect*.

For more details on using Neo4j Bloom, please see the https://neo4j.com/docs/bloom-user-guide/current/[Neo4j Bloom documentation].

[NOTE]
====
*Note: Perspectives in Aura*

Due to the nature of Aura's infrastructure, it is not currently possible to share Perspectives in Bloom, as the data for a given Perspective is stored in a cookie in the user's web browser.

An alternative is to export your Perspective as a JSON file and import it into another Bloom session.

To export a Perspective:

. Open the Bloom interface for your Neo4j Aura database.
. Navigate to the _Perspectives Gallery_.
. Click on the vertical ellipsis (*...*) and select *Export*.
. Save the file to your local disk.

You can import perspectives by clicking the blue "Import Perspective" button in the Perspective gallery.
Please note that the Perspective exposes details about your graph's schema but not the actual data within.

For more information, see https://neo4j.com/docs/bloom-user-guide/1.5/bloom-perspectives/[Bloom Perspectives].
====

== Neo4j Desktop

You can connect Aura databases to the Neo4j Desktop application, allowing the ability to have a single portal for interacting with all instances of Neo4j, whether local or located in the cloud.

To connect to a database using Neo4j Desktop:

. Navigate to the https://console.neo4j.io/[Neo4j Aura Console] in your browser.
. Copy the connection URL of the database you want to connect to.
. In Neo4j Desktop, select the *Projects* tab and select an existing project or create a new one.
. Select the *Add* dropdown and choose *Remote connection*.
. Enter a name for the database and enter the URL from the Neo4j Aura console from the second step.
Once complete, select *Next*.
. With *Username/Password* selected, enter your credentials and select *Next*.
These are the same credentials you stored when xref:getting-started/create-database.adoc[creating the database].
. When available, activate the connection by clicking the *Connect* button.

[NOTE]
====
*Notes:*

* Neo4j Desktop only allows 1 connection at a time to a database (local or remote).
* Deactivating an instance in Neo4j Desktop won't shut it down or stop a remote instance - it will only temporarily close the connection to it in Neo4j Desktop.
====

As with other databases in Neo4j Desktop, you can install https://install.graphapp.io/[Graph Apps] for monitoring and other functionality.

To do this, follow the same process to install the graph application that you need, and open it from Neo4j Desktop or a web browser with the running and activated Neo4j Aura instance.
