[[aura-create-database]]
= Creating a database
:description: This page describes how to create a Neo4j Aura database.

With an account created, you now have access to the Aura Console and are ready to create your first database. 

To create a database in Neo4j Aura:

. Navigate to the https://console.neo4j.io/[Neo4j Aura Console] in your browser.
. Select *Create a database*.
. Set your desired settings for the database:
* *Database Name* - The name to give the database. This name can be whatever you like.
* *Neo4j Version* - The version of the Neo4j database. By default, this is the latest major release.
* *GCP Region* - The physical location of the database. Set this as close to your location as possible. The closer the region to your location, the faster the response time for any network interactions with the database.
* *Database size* - The memory, CPU, and storage allocated to the database. The larger the database size, the more it costs to run. Once selected, you can see the running cost at the bottom of the page.
. Tick the *I understand* checkbox next to the running cost confirmation.
. Select *Create Database*.
. Copy and store the *Username* and *Generated password* credentials for the database.
. Tick the *I have stored these credentials safely to use later* checkbox, and select *Continue*.

[TIP]
====
*Tip:* If you instead want to provision and manage your database through one of the supported cloud marketplace providers, please see xref:cloud-providers/index.adoc[].
====
