[[aura-create-database]]
= Creating a database
:description: This page describes how to create a Neo4j AuraDB database.

With an account created, you now have access to the Aura Console and are ready to create your first database.

The process of creating a database differs depending on your subscription plan.

You can select from the options below to display the relevant process.

[.tabbed-example]
====
[.include-with-free]
=====

To create an *AuraDB Free* database in Neo4j AuraDB:

. Navigate to the https://console.neo4j.io/[Neo4j Aura Console] in your browser.
. Select *Create a database* to open the *Create a database* page.
. Select *AuraDB Free* as your *Database type*.
. Set your *Database details*:
* *Database Name* - The name to give the database. This name can be whatever you like.
* *Region* - The physical location of the database. Set this as close to your location as possible. The closer the region to your location, the faster the response time for any network interactions with the database.
. (Optional) Select a *Starting dataset*. Selecting a starting dataset pre-populates your database with data from the selected dataset. 
. Select *Create Free DB* when you are happy with your database details.
. Copy and store the *Username* and *Generated password* credentials for the database.
. Tick the *I have stored these credentials safely to use later* checkbox, and select *Continue*.

[NOTE]
======
*NOTE:* You can only create one AuraDB Free database per account.
======

=====
[.include-with-professional]
=====

To create an *AuraDB Professional* database in Neo4j AuraDB:

. Navigate to the https://console.neo4j.io/[Neo4j Aura Console] in your browser.
. Select *Create a database* to open the *Create a database* page.
. Select *AuraDB Professional* as your *Database type*.
. Set your *Database size*, the memory, CPU, and storage allocated to the database. The larger the database size, the more it costs to run. Once selected, you can see the running cost at the bottom of the page.
. Set your *Database details*:
* *Database Name* - The name to give the database. This name can be whatever you like.
* *Neo4j Version* - The version of the Neo4j database. By default, this is the latest major release.
* *Region* - The physical location of the database. Set this as close to your location as possible. The closer the region to your location, the faster the response time for any network interactions with the database.
. Tick the *I understand* checkbox next to the running cost confirmation.
. Select *Create Database* when you are happy with your database details and size.
. Copy and store the *Username* and *Generated password* credentials for the database.
. Tick the *I have stored these credentials safely to use later* checkbox, and select *Continue*.

[TIP]
======
*TIP:* If you instead want to provision and manage your database through one of the supported cloud marketplace providers, please see xref:cloud-providers/index.adoc[].
======

=====
[.include-with-enterprise]
=====

To create an *AuraDB Enterprise* database in Neo4j AuraDB:

. Navigate to the https://console.neo4j.io/[Neo4j Aura Console] in your browser.
. Select *Create a database* to open the *Create a database* page.
. Set your *Database size*, the memory, CPU, and storage allocated to the database. The larger the database size, the more it costs to run. Please refer to your enterprise contract for pricing.
. Set your *Database details*:
* *Database Name* - The name to give the database. This name can be whatever you like.
* *Neo4j Version* - The version of the Neo4j database. By default, this is the latest major release.
* *Region* - The physical location of the database. Set this as close to your location as possible. The closer the region to your location, the faster the response time for any network interactions with the database.
. Tick the *I understand* checkbox.
. Select *Create Database* when you are happy with your database details and size.
. Copy and store the *Username* and *Generated password* credentials for the database.
. Tick the *I have stored these credentials safely to use later* checkbox, and select *Continue*.

[TIP]
======
*TIP:* If you instead want to provision and manage your database through one of the supported cloud marketplace providers, please see xref:cloud-providers/index.adoc[].
======

=====
====

[NOTE]
====
Multi-database is not currently supported within Neo4j AuraDB.
====





