[[aura-create-account]]
= Create an account
:description: This page describes how to create a Neo4j Aura account.
:page-aliases: platform/create-account.adoc

To access Neo4j Aura, you need to have an Aura account.
Navigate to link:https://console.neo4j.io[Neo4j Aura console] and follow the instructions for registration.
Once you have accepted the terms and conditions and verified your email address, an account is created for you.

With the account, an *Organization* is provisioned for you, and within the organization, a *Project* is created, and within the Project, your first instance.

You can then create new projects and instances, see xref:getting-started/create-project.adoc[Create a project] and xref:getting-started/create-instance.adoc[Create an instance] for more information.



// The console exists in two versions,the new console, and the classic experience, as mentioned in xref:index.adoc[About Neo4j Aura console].
// You can toggle between the different versions, via the account dropdown in the top right corner.