[[aura-query-database]]
= Querying a database
:description: This page describes how to query data using Cypher.

You can query data in an Aura database using Cypher.

Cypher is the declarative graph query language created by Neo4j and can be used to query, update, and administer your Aura database.

You can run Cypher statements through Neo4j Browser.
For more information on how to open an Aura database in Neo4j Browser, see xref:getting-started/access-database.adoc[].

For more information on Cypher, see https://neo4j.com/docs/cypher-manual/current[the Neo4j Cypher Manual].

[NOTE]
====
*Note:* As with xref:getting-started/importing-data.adoc#_loading_csv_data[LOAD CSV], Aura does not support Cypher statements that access local files. 
====

== APOC

APOC (Awesome Procedures on Cypher) is a Neo4j library that provides access to additional procedures and functions, extending the use of the Cypher query language.

A subset of the APOC Core functions and procedures are available in Aura.

You can run the following Cypher statements on your Aura database to return the available procedures and functions:

[source,cypher,role=noplay]
----
CALL dbms.procedures() YIELD name, signature WHERE name CONTAINS 'apoc' RETURN *
CALL dbms.functions() YIELD name, signature WHERE name CONTAINS 'apoc' RETURN *
----

For more information on APOC, see https://neo4j.com/labs/apoc/[the APOC documentation].