[[aura-query-instance]]
= Query an instance
:description: This page describes how to query data using Cypher.

The Query UI in Neo4j Aura is your interface for running and managing Cypher queries against your graph database.
It’s For: Developers and data folks who need to dig into graph data.

* Cypher Editor: Write and execute your queries.
* Results Pane: See your data, either in graph form, tables, or raw text.
* History: Look back at what you’ve done.

* Know Cypher? Good. If not, start with simple patterns.
* Choose from Graph, Table, or Text to see your results.
* Graph View: Zoom, pan, and click on nodes to get details.
* Export: Save your results as CSV or JSON.
* Accessing History: Quickly find and re-run past queries.
* Managing: Save your favorites, or clear out the old ones.

== Cypher

You can query data in an instance using Cypher.

Cypher is the declarative graph query language created by Neo4j and can be used to query, update, and administer your instance.

You can run Cypher statements through Neo4j Browser and Neo4j Cypher Shell.
For more information on how to open an instance in Browser and Cypher Shell, see xref:auradb/getting-started/connect-database.adoc[].

For more information on Cypher and Aura, see link:{neo4j-docs-base-uri}/cypher-manual/current/introduction/cypher_aura/[the Neo4j Cypher Manual].

