= Alternative deployment options

[[aura-gds-plugin]]
[role=label--aura-db-professional]
== Graph Analytics plugin

The Graph Analytics plugin allows you to use the link:https://neo4j.com/docs/graph-data-science/current/introduction/[Graph Data Science library] in any AuraDB Professional instance with the following requirements:

* Neo4j version 5 or later
* 4 GB of memory or more
* All supported cloud providers and regions

You can enable or disable Graph Analytics when necessary, both during xref:getting-started/create-instance.adoc[instance creation] and on an xref:managing-instances/instance-details.adoc[existing instance].
It can also be changed with the link:https://neo4j.com/docs/aura/platform/api/specification/#/instances/patch-instance-id[Aura API].

The plugin shares compute and memory resources with the AuraDB server, so you do not incur any additional costs when you enable it.
This also means that using the plugin can disrupt transactional queries and can impact the instance.


[[get-started-plugin]]
=== Getting started

With the Graph Analytics plugin enabled:

* If you use the Neo4j Browser or run Cypher queries through a Neo4j driver, start with the tutorials at link:{neo4j-docs-base-uri}/graph-data-science/current/getting-started/[Graph Data Science -> Getting started].
* If you use Python, start with the tutorials at link:{neo4j-docs-base-uri}/graph-data-science-client/current/tutorials/tutorials/[Graph Data Science client -> Tutorials].

[[aura-ds]]
[role=label--aura-ds-professional label--aura-ds-enterprise]
== AuraDS

AuraDS is the fully managed version of the Graph Data Science library, where the <<aura-gds-plugin>> is deployed by default and optimized for analytical use cases.

In an AuraDS instance, Graph Analytics is always on.
The plugin shares compute and memory resources with the AuraDS server.

AuraDS instances have the following features:

* Upgrades and patches automatically applied
* Can be seamlessly scaled up or down
* Can be paused to reduce costs

=== Plans

AuraDS offers the AuraDS Professional and AuraDS Enterprise subscription plans.
The full list of features for each plan is available on the link:https://neo4j.com/pricing/#graph-analytics[Neo4j Pricing page].

=== Updates and upgrades

AuraDS updates and upgrades are handled by the platform, and as such do not require user intervention.
Security patches and new versions of GDS and Neo4j are installed within short time windows during which the affected instances are unavailable.

The operations are non-destructive, so graph projections, models, and data present on an instance are not affected.
No operation is applied until all the running GDS algorithms have completed.

[IMPORTANT]
====
Graphs and models created or updated _after_ the instance update/upgrade process has started are *not guaranteed* to be restored upon restart.
====