[[graph-analytics-aura]]
= Graph analytics in Aura
:description: This page describes how to run graph analytics in Aura.
:page-aliases: aurads/index.adoc
:gds-sessions-page: {neo4j-docs-base-uri}/graph-data-science/current/installation/aura-graph-analytics-serverless/

If your data is in Aura or you plan to move it to Aura, you have several options to run graph analytics:

* Enable the <<aura-gds-plugin,Graph Analytics plugin>> on an existing AuraDB instance (Professional).
* Use <<aura-gds-serverless,Aura Graph Analytics>> from an existing AuraDB instance (Business Critical, Virtual Dedicated Cloud).
* Create an <<aura-ds,AuraDS instance>> (Professional, Enterprise).

If your data is in a self-managed Neo4j DBMS or a non-Neo4j data source, you can still use <<aura-gds-serverless, Aura Graph Analytics>>.

[[aura-gds-plugin]]
== Graph Analytics plugin

label:AuraDB-Professional[]

The Graph Analytics plugin allows you to use the link:https://neo4j.com/docs/graph-data-science/current/introduction/[Graph Data Science library] in any AuraDB Professional instance with the following requirements:

* Neo4j version 5 or later
* 4 GB of memory or more
* All supported cloud providers and regions

You can enable or disable Graph Analytics when necessary, both during xref:getting-started/create-instance.adoc[instance creation] and on an xref:managing-instances/instance-details.adoc[existing instance].
It can also be changed with the link:https://neo4j.com/docs/aura/platform/api/specification/#/instances/patch-instance-id[Aura API].

The plugin shares compute and memory resources with the AuraDB server, so you do not incur any additional costs when you enable it.

[[get-started-plugin]]
=== Getting started

With the Graph Analytics plugin enabled:

* If you use the Neo4j Browser or run Cypher queries through a Neo4j driver, start with the link:{neo4j-docs-base-uri}/graph-data-science/current/getting-started/[Graph Data Science] tutorials.
* If you use Python, start with the link:{neo4j-docs-base-uri}/graph-data-science-client/current/tutorials/tutorials/[Python client tutorials].

[[aura-gds-serverless]]
== Aura Graph Analytics

Aura Graph Analytics allows you to use the Graph Data Science library regardless of where your source data is stored.
It runs in Aura as a link:{gds-sessions-page}[dedicated service] optimised for analytics workloads, with no memory or compute resources shared with your data store.

You can enable, disable, and configure Aura Graph Analytics on the organization level in the xref:visual-tour/index.adoc#_settings_for_graph_analytics_serverless[organization settings].
The details on any running sessions are available in the xref:visual-tour/index.adoc#_graph_analytics[Graph Analytics] page.

=== From an AuraDB instance

label:AuraDB-Business-Critical[] label:AuraDB-Virtual-Dedicated-Cloud[]

[IMPORTANT]
====
Aura Graph Analytics is currently unavailable via any of the xref:cloud-providers.adoc[cloud provider marketplaces].
====

You can use Aura Graph Analytics from any AuraDB Business Critical or AuraDB Virtual Dedicated Cloud instance with the following requirements:

* Neo4j version 5 or later
* All supported cloud providers and regions

[[get-started-serverless]]
=== Getting started

With Aura Graph Analytics enabled in your organization, you only need to create xref:api/authentication.adoc#_creating_credentials[Aura API credentials] before you can get started.

With the Aura API credentials available:

* If you use the Neo4j Browser or run Cypher queries through a Neo4j driver, start with the link:{neo4j-docs-base-uri}/graph-data-science/current/installation/aura-graph-analytics-serverless/#_examples_2[example] in the Graph Data Science documentation.
* If you use Python, start with one of the Python client tutorials depending on whether your data is in
link:{neo4j-docs-base-uri}/graph-data-science-client/current/tutorials/graph-analytics-serverless/[AuraDB], in a link:{neo4j-docs-base-uri}//graph-data-science-client/current/tutorials/graph-analytics-serverless-self-managed/[self-managed Neo4j database], or a link:{neo4j-docs-base-uri}//graph-data-science-client/current/tutorials/graph-analytics-serverless-standalone/[non-Neo4j data source].

[[aura-ds]]
== AuraDS

label:AuraDS-Professional[] label:AuraDS-Enterprise[]

AuraDS is the fully managed version of the Graph Data Science library where the <<aura-gds-plugin>> is deployed by default.

In an AuraDS instance, Graph Analytics is always on.
The plugin shares compute and memory resources with the AuraDS server.

AuraDS instances have the following features:

* Upgrades and patches are automatically applied.
* Can be seamlessly scaled up or down.
* Can be paused to reduce costs.

=== Plans

AuraDS offers the AuraDS Professional and AuraDS Enterprise subscription plans.
The full list of features for each plan is available on the link:https://neo4j.com/pricing/#graph-data-science[Neo4j Pricing page].

=== Updates and upgrades

AuraDS updates and upgrades are handled by the platform, and as such do not require user intervention.
Security patches and new versions of GDS and Neo4j are installed within short time windows during which the affected instances are unavailable.

The operations are non-destructive, so graph projections, models, and data present on an instance are not affected.
No operation is applied until all the running GDS algorithms have completed.

[IMPORTANT]
====
Graphs and models created or updated _after_ the instance update/upgrade process has started are *not guaranteed* to be restored upon restart.
====

== Comparison

[opts="header", cols="1s,1,1,1,1"]
|===
|
|Graph Analytics plugin +
(AuraDB Pro)
|Aura Graph Analytics +
(AuraDB BC)
|Aura Graph Analytics +
(AuraDB VDC)
|AuraDS

|Maximum memory
|Up to 128 GB
|Up to 128 GB
|Up to 512 GB
|Up to 384 GB

|Resources for analytics
|Shared with DB (optimized for DB)
|Dedicated
|Dedicated
|Shared with DB (optimized for analytics)

|Number of concurrent sessions
|-
|Up to 10
|Up to 100
|-

|Data sources
|Same server
|AuraDB BC; self-managed Neo4j DBMS; custom
|AuraDB VDC; self-managed Neo4j DBMS; custom
|Same server; custom

|DBMS restart behavior
|No downtime; projected graphs and trained models are not retained
|No downtime; projected graphs and trained models are unaffected
|No downtime; projected graphs and trained models are unaffected
|Short downtime; projected graphs and trained models are restoredfootnote:[Graphs and models created or updated _after_ the instance update/upgrade process has started are *not guaranteed* to be restored upon restart.]
|===
