[[graph-analytics-aura]]
= Graph analytics on Aura
:description: This page describes how to run graph analytics on Aura.
:page-aliases: aurads/index.adoc
:gds-no-db-name: Graph Analytics [STANDALONE]

There are multiple ways to run graph analytics in Aura:

* <<aura-gds-plugin,Enable Graph Analytics>> on an existing AuraDB Professional instance.
* <<aura-gds-serverless,Use Graph Analytics Serverless>> sourced from an existing AuraDB Business Critical or AuraDB Virtual Dedicated Cloud instance.
* Create an <<aura-ds, AuraDS instance>>.
* <<aura-gds-serverless,Use Graph Analytics Serverless>> sourced from a self-managed Neo4j DBMS deployment.
* <<aura-gds-serverless,Use Graph Analytics Serverless>> sourced from a non-Neo4j data source.

== Graph analytics on AuraDB

[[aura-gds-plugin]]
=== Graph Analytics plugin

label:AuraDB-Professional[]

The Graph Analytics plugin allows you to use the link:https://neo4j.com/docs/graph-data-science/current/introduction/[Graph Data Science library] in any AuraDB Professional instance with the following requirements:

* Neo4j version 5 or later
* 4 GB of memory or more
* Any supported cloud providers and regions

You can enable or disable Graph Analytics when necessary.
Graph Analytics will share compute and memory resources with the AuraDB server, and you will not incur additional costs.

[[aura-gds-serverless]]
=== Graph Analytics Serverless

label:AuraDB-Business-Critical[] label:AuraDB-Virtual-Dedicated-Cloud[]

include::partial$EAP.adoc[]

Graph Analytics Serverless allows you to use the link:https://neo4j.com/docs/graph-data-science/current/introduction/[Graph Data Science library] with data sourced from any AuraDB Business Critical or Virtual Dedicated Cloud instance with the following requirements:

* Neo4j version 5 or later
* Any supported cloud providers and regions

Graph Analytics Serverless is a dedicated service optimised for analytics workloads, which will not share any memory or compute resources with the AuraDB instance.
You can control the size and the number of the Serverless sessions, and will only be billed for what you consume.

[[aura-ds]]
== AuraDS

label:AuraDS-Professional[] label:AuraDS-Enterprise[]

AuraDS is the fully managed version of the link:https://neo4j.com/docs/graph-data-science/current/introduction/[Graph Data Science library].

AuraDS instances have the following features:

* Upgrades and patches are automatically applied.
* Can be seamlessly scaled up or down.
* Can be paused to reduce costs.

Graph Analytics TBD share compute and memory resources with the AuraDS server, and it is always available.

=== Plans

AuraDS offers the AuraDS Professional and AuraDS Enterprise subscription plans.
The full list of features for each plan is available on the link:https://neo4j.com/pricing/#graph-data-science[Neo4j Pricing page].

=== Updates and upgrades

AuraDS updates and upgrades are handled by the platform, and as such do not require user intervention.
Security patches and new versions of GDS and Neo4j are installed within short time windows during which the affected instances are unavailable.

The operations are non-destructive, so graph projections, models, and data present on an instance are not affected.
No operation is applied until all the running GDS algorithms have completed.

[[aura-gds-no-db]]
== {gds-no-db-name}

{gds-no-db-name} allows you to use the link:https://neo4j.com/docs/graph-data-science/current/introduction/[Graph Data Science library] on Aura without AuraDB or AuraDS, on any supported cloud providers and regions.

Graph Analytics Serverless is a dedicated service optimised for analytics workloads.
You can import your data [...]
You can control the size and the number of the Serverless sessions, and will only be billed for what you consume.

== Comparison

[opts="header", cols="1,1,1,1"]
|===
|AuraDB Pro with Graph Analytics plugin
|Graph Analytics Serverless in Virtual Dedicated Cloud
|Graph Analytics Serverless in AuraDB Business Critical
|AuraDS

|Up to 64 GB memory
|Up to 512 GB memory
|Up to 128 GB memory
|Up to 384 GB memory

|Shared resources
|Dedicated resources
|Dedicated resources
|Shared resources

|Single instance
|Up to 100 concurrent sessions
|Up to 10 concurrent sessions
|Single instance

|AuraDB source
|AuraDB Virtual Dedicated Cloud, self-managed Neo4j DBMS, or custom data source
|AuraDB Business Critical, self-managed Neo4j DBMS, or custom data source
|AuraDS source

|===