[aura-cmi-reference]
= Reference
:table-caption!:

label:AuraDB-Virtual-Dedicated-Cloud[]
label:AuraDS-Enterprise[]
label:AuraDB-Business-Critical[]

[aura-cmi-metric_definitions]
== Metric definitions

[caption=]
.Out of Memory Errors
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| `neo4j_aura_out_of_memory_errors_total`
| Description
| The total number of Out of Memory errors for the instance.
Consider increasing the size of the instance if any OOM errors.
| Metric type
| _Counter_
| Default aggregation
m| SUM
|===

.CPU Available
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_aura_cpu_limit
| Description
| The total CPU cores assigned to the instance nodes.
| Metric type
| _Gauge_
| Default aggregation
m| MAX
|===

.CPU Usage
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_aura_cpu_usage
| Description
| CPU usage (cores).
CPU is used for planning and serving queries.
If this metric is constantly spiking or at its limits, consider increasing the size of your instance.
| Metric type
| _Gauge_
| Default aggregation
m| MAX
|===

.Storage Total
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_aura_storage_limit
| Description
| The total disk storage assigned to the instance.
| Metric type
| _Gauge_
| Default aggregation
m| MAX
|===

.Heap Used
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_dbms_vm_heap_used_ratio
| Description
| The percentage of configured heap memory in use.
The heap space is used for query execution, transaction state, management of the graph etc.
The size needed for the heap is very dependent on the nature of the usage of Neo4j.
For example, long-running queries, or very complicated queries, are likely to require a larger heap than simpler queries.
To improve performance, the heap should be large enough to sustain concurrent operations.
This value should not exceed 80% for long periods, short spikes can be normal.
In case of performance issues, you may have to tune your queries and monitor their memory usage, to determine whether the heap needs to be increased.
If the workload of Neo4j and performance of queries indicates that more heap space is required, consider increasing the size of your instance.
This helps avoid unwanted pauses for garbage collection.
| Metric type
| _Gauge_
| Default aggregation
m| MAX
|===

.Page Cache Hit Ratio (per minute)
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_dbms_page_cache_hit_ratio_per_minute
| Description
| The percentage of times data required during query execution was found in memory vs needing to be read from disk.
Ideally the whole graph should fit into memory, and this should consistently be between 98% and 100%.
If this value is consistently or significantly under 100%, check the page cache usage ratio to see if the graph is too large to fit into memory.
A high amount of insert or update activity on a graph can also cause this value to change.
| Metric type
| _Gauge_
| Default aggregation
m| AVG
|===

.Page Cache Usage Ratio
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_dbms_page_cache_usage_ratio
| Description
| The percentage of the allocated page cache in use.
If this is close to or at 100%, then it is likely that the hit ratio will start dropping, and you should consider increasing the size of your instance so that more memory is available for the page cache.
| Metric type
| _Gauge_
| Default aggregation
m| MIN
|===

.Bolt Connections Running
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_dbms_bolt_connections_running
| Description
| The total number of Bolt connections that are currently executing Cypher transactions and returning results.
This is a set of snapshots over time and may appear to spike if workloads are all completed quickly.
| Metric type
| _Gauge_
| Default aggregation
m| MAX
|===

.Bolt Connections Idle
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_dbms_bolt_connections_idle
| Description
| The total number of Bolt connections that are connected to the Aura database but not currently executing Cypher or returning results.
| Metric type
| _Gauge_
| Default aggregation
m| MAX
|===

.Bolt Connections Closed
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_dbms_bolt_connections_closed_total
| Description
| The total number of Bolt connections closed since startup.
This includes both properly and abnormally ended connections.
This value may drop if background maintenance is performed by Aura.
| Metric type
| _Counter_
| Default aggregation
m| MAX
|===

.Bolt Connections Opened
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_dbms_bolt_connections_opened_total
| Description
| The total number of Bolt connections opened since startup.
This includes both successful and failed connections.
This value may drop if background maintenance is performed by Aura.
| Metric type
| _Counter_
| Default aggregation
m| MAX
|===

.Garbage Collection Young Generation
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_dbms_vm_gc_time_g1_young_generation_total
| Description
| Shows the total time since startup spent clearing up heap space for short lived objects.
Young garbage collections typically complete quickly, and the Aura instance waits while the garbage collector is run.
High values indicate that the instance is running low on memory for the workload and you should consider increasing the size of your instance.
| Metric type
| _Counter_
| Default aggregation
m| MAX
|===

.Garbage Collection Old Generation
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_dbms_vm_gc_time_g1_old_generation_total
| Description
| Shows the total time since startup spent clearing up heap space for long-lived objects.
Old garbage collections can take time to complete, and the Aura instance waits while the garbage collector is run.
High values indicate that there are long-running processes or queries that could be optimized, or that your instance is running low on CPU or memory for the workload and you should consider reviewing these metrics and possibly increasing the size of your instance.
| Metric type
| _Counter_
| Default aggregation
m| MAX
|===

.Replan Events
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_database_cypher_replan_events_total
| Description
| The total number of times Cypher has replanned a query since the server started.
If this spikes or is increasing, check that the queries executed are using parameters correctly.
This value may drop if background maintenance is performed by Aura.
| Metric type
| _Counter_
| Default aggregation
m| MAX
|===

.Active Read Transactions
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_database_transaction_active_read
| Description
| The number of currently active read transactions.
| Metric type
| _Gauge_
| Default aggregation
m| MAX
|===

.Active Write Transactions
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_database_transaction_active_write
| Description
| The number of active write transactions.
| Metric type
| _Gauge_
| Default aggregation
m| MAX
|===

.Committed Transactions
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_database_transaction_committed_total
| Description
| The total number of committed transactions since the server was started.
This value may drop if background maintenance is performed by Aura.
| Metric type
| _Counter_
| Default aggregation
m| MAX
|===

.Peak Concurrent Transactions
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_database_transaction_peak_concurrent_total
| Description
| The highest number of concurrent transactions detected since the server started.
This value may drop if background maintenance is performed by Aura.
| Metric type
| _Counter_
| Default aggregation
m| MAX
|===

.Transaction Rollbacks
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_database_transaction_rollbacks_total
| Description
| The total number of rolled-back transactions.
This value may drop if background maintenance is performed by Aura.
| Metric type
| _Counter_
| Default aggregation
m| MAX
|===

.Checkpoint Events
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_database_check_point_events_total
| Description
| The total number of checkpoint events executed since the server started.
This value may drop if background maintenance is performed by Aura.
| Metric type
| _Counter_
| Default aggregation
m| MAX
|===

.Checkpoint Events Cumulative Time
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_database_check_point_total_time_total
| Description
| The total time in milliseconds spent in checkpointing since the server started.
This value may drop if background maintenance is performed by Aura.
| Metric type
| _Counter_
| Default aggregation
m| MAX
|===

.Last Checkpoint Duration
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_database_check_point_duration
| Description
|The duration of the last checkpoint event.
Checkpoints should typically take several seconds to several minutes.
Values over 30 minutes warrant investigation.
| Metric type
| _Gauge_
| Default aggregation
m| MAX
|===

.Relationships
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_database_count_relationship
| Description
| The total number of relationships in the database.
| Metric type
| _Gauge_
| Default aggregation
m| MAX
|===

.Nodes
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_database_count_node
| Description
| The total number of nodes in the database.
| Metric type
| _Gauge_
| Default aggregation
m| MAX
|===

.Store Size Database
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_database_store_size_database
| Description
| Amount of disk space reserved to store user database data, in bytes.
Ideally, the database should all fit into memory (page cache) for the best performance.
Keep an eye on this metric to make sure you have enough storage for today and for future growth.
Check this metric with page cache usage to see if the data is too large for the memory and consider increasing the size of your instance in this case.
| Metric type
| _Gauge_
| Default aggregation
m| MAX
|===

.Page Cache Evictions
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_dbms_page_cache_evictions_total
| Description
| The number of times data in memory is being replaced in total.
A spike can mean your workload is exceeding the instance's available memory, and you may notice a degradation in performance or query execution errors.
Consider increasing the size of your instance to improve performance if this metric remains high.
| Metric type
| _Counter_
| Default aggregation
m| MAX
|===

.Successful Query Executions
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_db_query_execution_success_total
| Description
| The total number of successful queries executed on this database.
| Metric type
| _Counter_
| Default aggregation
m| SUM
|===

.Query Execution Failures
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_db_query_execution_failure_total
| Description
| The total number of failed queries executed on this database.
| Metric type
| _Counter_
| Default aggregation
m| SUM
|===

.Query Latency 99th Percentile
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_db_query_execution_internal_latency_q99
| Description
| The query execution time in milliseconds where 99% of queries executed faster than the reported time.
| Metric type
| _Gauge_
| Default aggregation
m| MAX
|===

.Query Latency 75th Percentile
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_db_query_execution_internal_latency_q75
| Description
| The query execution time in milliseconds where 75% of queries executed faster than the reported time.
| Metric type
| _Gauge_
| Default aggregation
m| MAX
|===

.Query Latency 50th Percentile
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_db_query_execution_internal_latency_q50
| Description
| The query execution time in milliseconds where 50% of queries executed faster than the reported time.
This also corresponds to the median of the query execution time.
| Metric type
| _Gauge_
| Default aggregation
m| MAX
|===

.Last Committed Transaction ID
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
m| neo4j_database_transaction_last_committed_tx_id_total
| Description
| The id of the last committed transaction. 
Track this for primary cluster members of your Aura instance. 
It should show overlapping, ever-increasing lines and if one of the lines levels off or falls behind, it is clear that this cluster member is no longer replicating data, and action is needed to rectify the situation.
| Metric type
| _Counter_
| Default aggregation
m| MAX
|===

.Cluster Leader (only included if <<_metrics_granularity,high granularity>> is turned on)
[frame="topbot", stripes=odd, grid="cols", cols="<1,<4"]
|===
| Metric name
| neo4j_cluster_raft_is_leader
| Description
| Is this server the leader? Track this for each rafted member in the cluster. 
It reports 0 if it is not the leader and 1 if it is the leader. 
The sum of all of these should always be 1. 
However, there are transient periods in which the sum can be more than 1 because more than one member thinks it is the leader. 
Action may be needed if the metric shows 0 for more than 30 seconds.
| Metric type
| _Gauge_
| Default aggregation
m| MAX
|===
