[[aura-api-overview]]
= Overview
:description: This page introduces the Aura API.

label:AuraDB-Virtual-Dedicated-Cloud[]
label:AuraDS-Enterprise[]

The Aura API allows you to programmatically perform actions on your Aura instances without the need to log in to the Console.

A complete list of the available endpoints can be seen and tested in the link:{neo4j-docs-base-uri}/aura/platform/api/specification/[API Specification].

[TIP]
====
Before using the API, you must follow the steps outlined in xref:api/authentication.adoc[] to create your credentials and authenticate your requests.
====

== API URL

=== Base URL

The base URL for the Aura API is `\https://api.neo4j.io`.

=== Versioning

The current version of the Aura API is `link:{neo4j-docs-base-uri}/aura/platform/api/specification/[v1]`

If and when there is a need to introduce breaking changes to the API, a new version will be released to ensure no existing integrations are broken.

In the future, legacy API versions are deprectaed, notice will be issued.
Once the expiry date for a deprecated version has passed, that version will no longer be available.

=== Example request

The following example shows how to use the base URL and versioning to make a request to the API:

`GET \https://api.neo4j.io/v1/instances`

== Retries

In the event of `5xx` server error responses, you may consider retrying the request after a delay if it is safe to do so.
The response may include a `Retry-After` header with a suggestion of a suitable minimum delay before attempting to retry.

The global rate limit for all requests is 125 requests per minute.

You should consider your use of the rate limit before attempting to retry, and it is recommended that you use an exponential backoff delay with a limited number of retries before giving up.

A request is only guaranteed to be safe to retry if it uses an idempotent HTTP method, such as `GET`.
If, for example, you retry a request for creating an instance, you may end up with duplicate instances and end up being charged extra as a result.

In the case of `429 Too Many Requests`, we would recommend slowing down the rate of all requests sent from your client application and consider retrying with a suitable minimum delay and backoff strategy.

For other `4xx` client error responses, you should not resend such requests without first correcting them.

== Request tracing and troubleshooting

An `X-Request-Id` response header is returned with each request and can be used for troubleshooting.

The value of this header contains a unique ID that can be used to track the journey of a request.

If you run into any issues with a particular request, you can https://support.neo4j.com/[raise a support ticket] and provide the `X-Request-Id`.

== Query API

The Query API allows you to interact with an Aura database using Cypher over HTTPS. 
Unlike the deprecated HTTP API, the Query API is now exposed for Aura, making it a viable alternative to Bolt for running queries programmatically. 
For more information, see the link:https://neo4j.com/docs/query-api/current/[Query API documentation]

To send Cypher queries to an Aura instance, make a POST request to the following endpoint:

https://<databaseID>.databases.neo4j.io/db/<databaseName>/query/v2

`<databaseID>` The unique ID of your Aura database (e.g., e011c23c).

`<databaseName>` The target database (e.g., neo4j for the default database).

Aura only supports HTTPS (port 443). There’s no need to specify a port explicitly, as it defaults to 443.

Here's how to create a node in Aura using `curl`:

[source, shell]
----
curl -vvv -X POST
     -H "Authorization: Basic bmVvNGo6Zd9vdGJhbGg="
     -H "Content-Type: application/json"
     -d "{   \"statement\": \"create (n:Person) RETURN n;\" } }"
      https://e011c22f.databases.neo4j.io:443/db/neo4j/query/v2
----

Note the last line above and inclusion of `:443` is not required as its the default.


