= Create a dashboard with AI
:description: Create dashboards quickly based on your knowledge graph with the help of AI. Write prompts to generate a dashboard so you can get them looking the way you want, or let the LLM do the imaginative work for you. Make sure you have enabled Generative AI assistance at the org level to use this feature.

Work with AI on prompt suggestions to create a dashboard. Then work with AI on the dashboard plan, *a wireframe of the layout*, to refine the charts and stats you can share with your team. 

If you have an idea of how you want your dashboard to look, use AI to save time creating a dashboard by describing the charts that you're creating. 

Or use the AI dashboard tool to open up new, innovative ways of thinking about your data by following AI generated suggestions to visualize innovative charts.

== Prerequisites

For AI features to be accessible, an xref:user-management.adoc#_organization_level_roles[organization admin] must enable Generative AI assistance under xref:visual-tour/index.adoc#org-settings[organization settings].

To create a dashboard, you need a database and data.
The examples on this page use the xref::/dashboards/index.adoc#_sample_dataset[Northwind sample dataset] which you can also use.

== How-to create with AI 

=== 1. Describe your dashboard

* Write about what kind of dashboard you want to create.
* Select the *Generate* button to generate suggestions for prompts to make a dashboard layout.
* Pick a suggestion then select Continue.

The more information you include, the better the result.
This holds for information about the database itself as well as entities in the data model. 

=== 2. Review your dashboard plan 

* The dashboard plan gives you an idea of the layout of your dashboard. 
** Tabs across the top are clickable and open different dashboard pages.
** Important numbers are displayed as single values across the top 
** Charts are generated and the type of visualization (e.g. bar chart, line chart) is indicated by an icon. 
* *Refine layouts and content:* Write in the text box to change the plan, and select the *Generate* button to reload the plan, based on your suggestions.
* When things look the way you like, select *Create dashboard*.

The more information you include, the better the result. This holds for information about the database itself as well as entities in the data model.

[NOTE]
====
When creating a dashboard with AI, the AI analyzes your link:https://neo4j.com/docs/operations-manual/current/procedures/#procedure_db_schema_visualization[database schema], that is, the node labels and relationship types of your database.
It cannot read the actual data in your database. 
This keeps your data private.
====

== AI as a starting point
You can always edit an AI-generated dashboard. 
Use AI as a starting point, and then build on it by editing the output - and refining Cypher queries, visualizations, colors, and layouts to match your needs.

== Example

Note that the following examples might differ when you reproduce them.
This is due to the nature of how LLM processing works.

Copy the following prompt or create your own and use it to create a dashboard:

.Prompt
[source]
----
Focus on the French market, giving me an overview over recent top customers, top selling products, currently available stock, a category overview and sales volume per quarter.
----

Then, use the second screen to further work on the layout and types of charts.

For example:

.Prompt
[source]
----
Move the bar chart on the top of the first page to the bottom of the second page and add a pie chart over the distribution of beverage types.
----

