= Getting started with dashboards
:description: Follow these steps for a working example of Neo4j Aura dashboards.

Set up a working example of Neo4j Aura dashboards.

== Prerequisites

You need:

. A Neo4j Aura account
. A Neo4j Aura database instance

See the Aura xref::/getting-started/quick-start-guide.adoc[Quick start guide] for details.

== Add a sample data set

Download the Neo4j link:https://github.com/neo4j-graph-examples/recommendations/raw/refs/heads/main/data/recommendations-50.dump[movie recommendations sample data set dump file].
See link:https://neo4j.com/docs/getting-started/appendix/example-data/#_available_datasets[Available datasets] for alternative datasets.
However, the rest of this page refers to the movie recommendations dataset.

To add the sample data set in Aura:

. Click *Instances* under *Data services* in the left-side navigation.
. Locate the instance where you want to upload the sample data set and click the three dots icon at the top right, then click *Inspect*.
. In the dialog, select the *Restore from backup file* tab.
. Drag and drop or browse for the file you downloaded.
. Confirm the *Upload*.

== Create a dashboard

Create a new dashboard:

. In the *Dashboards* page, click *New Dashboard* at the top right.
. Click the dashboard tile that appears.
. In the *Dashboards app* page, you can find the dashboard configuration menu for your new dashboard appears  below *All dashboards*.
. Optionally assign a dashboard title and a role to share the dashboard with.
. Create a new page by entering a page title in the *Add page* input.

=== Add a card with a line chart

Create a line chart which displays the number of movies released for each year.

In the dashboard page tab:

. Click *Add card* at the bottom right of the page.
. in the new card, click the three dots icon at the top right, then select *Line chart* as the *Chart type*.
. Click *Edit* to edit the Cypher query of the card.
. Paste the following Cypher query to the input field:
+
[source,cypher]
----
MATCH (m:Movie)
RETURN m.year as Year, count(m.title) as Number
ORDER BY Year DESC
----
+
. Click **Done**.

The line chart should have selected *Year* as the *Dimension* and *Number* as the Value to display.

// Add screenshot

=== Add a card with a bar chart

Create a bar chart which displays the number of movies for each genre.

In the dashboard page tab:

. Click *Add card* at the bottom right of the page.
. in the new card, click the three dots icon at the top right, then select *Bar chart* as the *Chart type*.
. Click *Edit* to edit the Cypher query of the card.
. Paste the following Cypher query to the input field:
+
[source,cypher]
----
MATCH (g:Genre)<-[:IN_GENRE]-(m:Movie)
RETURN g.name as Genre, count(m) as Number
ORDER BY Number DESC
----
+
. Click **Done**.

The bar chart should have selected *Genre* as the *Category* and *Number* as the Value to display.

// Add screenshot


== Next steps

[IMPORTANT]
====
Save your dashboard by clicking the cloud icon next to the dashboard title in the dashboard configuration menu.
====

Optionally edit the title of the charts you created.

See xref::/dashboards/working-with-dashboards/index.adoc[Working with dashboards] for more dashboard options.

See xref::/dashboards/visualizations/index[Visualizations] to learn about the different charts and visualizations of Neo4j Aura dashboards.