= Integrations
:description: How to integrate Neo4j Aura dashboards with Neo4j Bloom and Neo4j Broswser.

Coming soon.


////
== Aura dashboards vs Bloom

link:https://neo4j.com/docs/bloom-user-guide[Neo4j Bloom] is a graph exploration application for visually interacting with graph data.
It is also a part of the Aura console experience.
By contrast, Neo4j Aura dashboards offers visualization beyond the graph layer such as charts and diagrams, maps and more.


== Aura dashboards vs BI connector

There are many data visualization and dashboard applications on the market.
With the link:https://neo4j.com/bi-connector/[Neo4j Connector for Business Intelligence] (BI connector), Neo4j databases can be connected to tools like link:https://www.tableau.com/visualization[Tableau] or link:https://www.microsoft.com/en-us/power-platform/products/power-bi[Power BI].

While connecting graph data to existing business intelligence and visualization application landscapes is an important use case, Aura dashboards offer native support for graph data.
Aura dashboards operate directly on your Neo4j database instance via the native Cypher query language and generate visualizations seemlessly in Aura.
////