= Managing dashboards
:description: Create and modify Neo4j dashboards.

Use **Dashboards** under **Tools** in the left-side navigation to access the dashboard page.

== Editing a dashboard

. Select a dashboard tile from the **Dashboards** page.
. To change the title, select the title text and edit it, then confirm.


=== Dashboard pages

Select a dashboard tile from the **Dashboards** page.
Dashboard pages are organized as tabs.
A new dashboard contains a single page "Main page".
You can edit or duplicate the page via hovering the page name and using the more menu *[...]*.
Add more pages via **+** next to the existing pages' names.
Additional pages can also be deleted from the more menu *[...]*.


=== Dashboard cards

A dashboard page can hold any number of cards.
Each card can hold a xref::/dashboards/visualizations/index.adoc[visualization], also referred to as the **Chart type**.
To add a card, use **Add card** at the bottom right.
Use the more menu *[...]* at the top right of a card to edit the card.
Use the six dots at the top left of a card to drag and drop it within the grid of the page.


== Deleting a dashboard

In the dashboards tile page, use the more menu *[...]* of a dashboard tile and select **Delete**, then confirm.


== Exporting the dashboard JSON as a file

In the dashboards tile page, use the more menu *[...]* of a dashboard tile and select **Export file...**.
Neo4j Aura creates a dashboard JSON file with the following format: `[dashboard title]_[current date as YYYY-MM-DD].json`.


== Copying the dashboard JSON to clipboard

In the dashboards tile page, use the more menu *[...]* of a dashboard tile and select **Copy to clipboard**.
