[[sm-deployment-details]]
= Deployment details
:description: This page describes deployment details

From the deployment card or deployment table, select the more menu *(…​)*.
In the graph view, the same menu can be accessed by right-clicking the DBMS node. Then select *Show details* from the menu options.

On the right side of the header, the view selector allows you to choose between two views: *table* view or *graph* view (see xref:fleet-management/graph-view.adoc[Graph view]).

== Table view

The table view shows topology data in a tabular format. Three different tables are selectable using the dropdown in the table header.

* Servers
* Databases
* Database instances

=== Servers

The *Servers* table shows all servers in the deployment.

For more information, see the link:https://neo4j.com/docs/operations-manual/current/clustering/monitoring/show-servers-monitoring/[documentation] for instructions on how to install plugins. for the `SHOW SERVERS` procedure, which is called by the plugin to obtain the data.

=== Databases and Database instances

The *Databases* table shows all databases in the deployment.

A *Database instance* in this context refers to an instance of a logical database running on a specific server.

For more information, see the link:https://neo4j.com/docs/operations-manual/current/database-administration/standard-databases/listing-databases/[documentation] for instructions on how to install plugins. for the `SHOW DATABASES` procedure, which is called by the plugin to obtain the data.