[[sm-deployment-details]]
= Deployment details
:description: This page describes how to access deployment details

To access deployment details, use the more menu *(…​)* from the deployment card or deployment table.
In the graph view, the same menu can be accessed by right-clicking the DBMS node. 

On the right side of the header, the view selector allows you to choose between two views: *table* view or *graph* view (see xref:fleet-management/graph-view.adoc[Graph view]).

== Table view

The table view shows topology data in a tabular format. 
Three different tables are selectable using the dropdown in the table header.

* Servers
* Databases
* Database instances

=== Servers

The *Servers* table shows all servers in the deployment.

For more information, refer to the link:https://neo4j.com/docs/operations-manual/current/clustering/monitoring/show-servers-monitoring/[Operations Manual -> Monitor servers]  for the `SHOW SERVERS` procedure, which is called by the plugin to obtain the data shown in the *Servers* table.

=== Databases and Database instances

The *Databases* table shows all databases in the deployment.

A *Database instance* in this context refers to an instance of a logical database running on a specific server.

For more information, refer to the link:https://neo4j.com/docs/operations-manual/current/database-administration/standard-databases/listing-databases/[Operations Manual -> List databases] for the `SHOW DATABASES` procedure, which is called by the plugin to obtain the data shown in the *Databases* and *Database instances* tables.