= Overview
:description: This page provides an overview of Fleet Manager.

Fleet Manager allows you to monitor *all* of your Neo4j instances, both Aura and self-managed, directly from the Aura console.
It collects the following information from your self-managed deployment and securely transmits it to Aura:

* Metrics
* Topology information (graph and tabular format)
* Server configuration
* Database metadata
* License status

You can also use the Fleet Manager procedures to manage and monitor the connection to Aura.
See xref:fleet-management/procedures.adoc[Fleet Manager procedures] for more information.

In addition to these features, the user tools Query, Explore, and Dashboards (available in the Aura console) are also available for self-managed deployments.
See xref:managing-instances/self-managed.adoc[Self-managed instances] for more information.

[NOTE]
====
Connecting to self-managed instances with user tools works independently of the Fleet Manager and is therefore available for unmonitored deployments as well.
====

== Compatibility

In versions 2026.03 and later, Fleet Manager is enabled by default and can be used without any additional setup.

In earlier versions, it is available as a plugin that you can install in your self-managed deployment.
These includes versions Neo4j 4.4.45+, 5.26.12+, and versions between 2025.08.0 and 2026.02.2 inclusive.
For details on how to enable the Fleet management plugin in those versions, see link:https://neo4j.com/docs/operations-manual/current/plugins/#install-and-configure-plugins[Operations Manual -> Install and configure plugins].

All operating systems and deployment modalities supported by Neo4j are also supported by Fleet Manager.

[NOTE]
====
Use Fleet management plugin 1.1.1 or later for proper support of Neo4j 4.4 clusters.
====

Neo4j Community Edition deployments are subject to some limitations due to the limited set of features, such as no metrics being available.

[NOTE]
====
Community Edition compatibility is offered on a best-effort basis. Neo4j does not offer any technical support for it.
====

== Security

Fleet Manager is designed to be secure, no inbound connections to your self-managed deployment are allowed.
Further, there is no capability for performing any write operations or other mutations remotely.

No data is read from your databases.
See xref:fleet-management/data.adoc[Data transparency] for a complete list of the data sent to Aura from your self-managed deployment.

== Access permissions

Aura project users have the following capabilities related to Fleet Manager and self-managed deployments, depending on their project role.

:check-mark: icon:check[]

.Aura project roles and Fleet Manager capabilities
[opts="header",cols="3,1,1,1,1"]
|===
| Capability
| Project Viewer
| Metrics Reader
| Member
| Admin

| View deployments
| {check-mark}
|
| {check-mark}
| {check-mark}

| Create deployments
|
|
|
| {check-mark}

| Rename deployments
|
|
|
| {check-mark}

| Delete deployments
|
|
|
| {check-mark}

| View connection URL
| {check-mark}
|
| {check-mark}
| {check-mark}

| Add connection URL
|
|
|
| {check-mark}

| Edit connection URL
|
|
|
| {check-mark}

| View token info (existence, active)
| {check-mark}
|
| {check-mark}
| {check-mark}

| Create token
|
|
|
| {check-mark}

| Regenerate token
|
|
|
| {check-mark}

| Delete token
|
|
|
| {check-mark}
|===
