= Overview
:description: This page provides an overview of fleet management.

Get an enterprise-wide view of all your Neo4j instances, both Aura instances and/or self-managed.

For users operating in hybrid environments, it’s common to have a mix of Aura instances and self-managed Neo4j deployments. 
Integrating self-managed deployment into the Aura console allows for a more centralized management.

== Architecture

Fleet management uses a plugin that you install on your self-managed Neo4j deployments.

See xref:fleet-management/setup.adoc[Add a deployment] for instructions on how to set up the plugin.

The plugin collects information from your deployment and securely transmits this data to Aura.

== Security 

Fleet management is designed to be secure, no inbound connections to your self-managed deployment are allowed.
Further, there is no capability for performing any write operations or other mutations remotely.

No data is read from your databases.
See xref:fleet-management/data.adoc[Data transparency] for a complete list of the data sent to Aura from your self-managed deployment.

== Features

Fleet management offers various features to manage and monitor your self-managed Neo4j deployments:

* Metrics
* Topology views (graph and tabular format)
* Server configuration viewer
* Database metadata
* License status viewer

In addition to these features, the user tools Query, Explore, and Dashboards (available in the Aura console) are also available for self-managed deployments.

[NOTE]
====
User tools connect to your deployment using their own bolt connection, independent of the fleet management plugin.
====