The Neo4j Connector for Business Intelligence (BI) delivers access to Neo4j graph data from BI tools such as Tableau, Power BI, Looker, TIBCO, Spotfire Server, Microstrategy, and more. It can be used to run SQL queries on a Neo4j graph and retrieve data in tabular format.

== Prepare example data

First of all, we need to create some graph data on the {product} instance. We can do this by running the following Cypher query in the Neo4j Browser:

[source, cypher, subs=attributes+]
----
CREATE
  (john:Person {name: "John", surname: "Doe", age: 42}),
  (jane:Person {name: "Jane", surname: "Doe", age: 40}),
  (john)-[:KNOWS]->(jane)
----

Then, we download the JDBC Neo4j Connector for BI from the https://neo4j.com/download-center/#integrations[Download Center].

== Configure command-line SQL clients

=== sqlline

In order to run SQL queries, we need a SQL client that can use a custom driver. We will clone and build https://github.com/julianhyde/sqlline[`sqlline`], a command line SQL client, but any SQL client or business intelligence platform can be used instead.

[source, shell, subs=attributes+]
----
$ git clone https://github.com/julianhyde/sqlline
$ cd sqlline
$ ./mvnw package
----

We need to make the BI connector driver available to `sqllite`. The easiest way to do this is to just extract the BI connector `Neo4jJDBC42.jar` file into the `sqlline/target` folder.

The `sqlline` client can then be run as follows:

[source, shell, subs=attributes+]
----
./bin/sqlline -d com.simba.neo4j.neo4j.jdbc42.Driver
----

From the client prompt, we can connect to the {product} instance by replacing the Neo4j URL with the appropriate one, and supplying the username and password when prompted to do so.

[NOTE]
====
The correct protocol to use for connection is `neo4j` (not `neo4j+s`). Make sure to add the `SSL=true` parameter to the URL.
====

[source, shell, subs=attributes+]
----
!connect jdbc:neo4j://xxxxxxxx.databases.neo4j.io?SSL=true
----

When the connection is established, it is possible to obtain a list of tables with the `!tables` command:

[source, shell, subs=attributes+]
----
jdbc:neo4j://xxxxxxxx.databases.neo4j.io> !tables
----

----
+-----------+--------------+---------------------+------------+---------+----------+------------+-----------+--------+
| TABLE_CAT | TABLE_SCHEM  |     TABLE_NAME      | TABLE_TYPE | REMARKS | TYPE_CAT | TYPE_SCHEM | TYPE_NAME | SELF_R |
+-----------+--------------+---------------------+------------+---------+----------+------------+-----------+--------+
| neo4j     | Node         | Person              | TABLE      |         |          |            |           |        |
| neo4j     | Relationship | Person_KNOWS_Person | TABLE      |         |          |            |           |        |
+-----------+--------------+---------------------+------------+---------+----------+------------+-----------+--------+
----

=== jdbcsql

Download `jdbcsql-1.0.zip` from https://sourceforge.net/projects/jdbcsql/files/

Unzip to `jdbcsql` and copy Neo4j connector into folder

Make the following changes (see http://jdbcsql.sourceforge.net/ for further details):

1. Add the following lines to `JDBCConfig.properties`
+
----
# neo4j settings
neo4j_driver = com.simba.neo4j.neo4j.jdbc42.Driver
neo4j_url = jdbc:neo4j://host?SSL=true
----

2. Add `Neo4jJDBC42.jar` to `Rsrc-Class-Path` line in `META-INF/MANIFEST.MF`
3. Run
+
----
java org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader -m neo4j -h xxxxxxxx.databases.neo4j.io -d neo4j -U neo4j -P yyyyyyyy 'SELECT * FROM Person'
----

(replace `xxxxxxxx` with the proper URL and `yyyyyyyy` with the actual password)

Result:

----
"_NodeId_"	age	name	surname
0	42	John	Doe
1	40	Jane	Doe
----

== Configure BI tools

=== Tableau (JDBC driver)

This example focuses on Tableau Desktop.

- Close any running instance of Tableau Desktop
- Copy the Neo4j driver to the appropriate Tableau drivers folder (e.g. `C:\Program Files\Tableau\Drivers` on Windows or `~/Library/Tableau/Drivers` on Mac)
- Start Tableau
- Click on `Other Databases (JDBC)`
- Insert the Aura URL as `jdbc:neo4j://xxxxxxxx.databases.neo4j.io?SSL=true`, leave dialect as `SQL92` and fill up the credentials
- Click on "Sign In"
- Select the `neo4j` database and the `Node` schema
- Click on the `Person` table to see the data

For more information on how to add a JDBC database to Tableau, check the https://help.tableau.com/current/pro/desktop/en-us/examples_otherdatabases_jdbc.htm[Tableau documentation^].

=== Power BI (ODBC driver)

[NOTE]
====
This example requires Microsoft Windows.
====

First of all, download and install the ODBC driver from the https://neo4j.com/download-center/#integrations[Download Center]. Then, open Power BI and:

- Click on "Get data from another source"
- Search for "ODBC" and click on it
- Select "Simba Neo4j" in the DSN dropdown menu
- Click on "Advanced options" and insert as connection string `Host=xxxxxxxx.databases.neo4j.io;SSL=1`
- Click "Ok"
- In the Navigator window, open `ODBC` -> `neo4j` -> `Node` -> `Person` to see a preview of the table

For more information on how to add an ODBC database to Power BI, check the https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-using-generic-interfaces[Power BI documentation^].

== Run queries

When the connection is established, it is also possible to run SQL queries:

[source, sql, subs=attributes+]
----
SELECT * FROM Person;
----

----
+----------+-----+------+---------+
| _NodeId_ | age | name | surname |
+----------+-----+------+---------+
| 0        | 42  | John | Doe     |
| 1        | 40  | Jane | Doe     |
+----------+-----+------+---------+
----