There are two ways you can import data from an existing Neo4j database into an Aura instance.

Use the *import database* process in the Aura console UI to import a _.backup_, _.dump_ or _.tar_ file as long as it’s less than 4GB. 

Use the <<_neo4j_admin_database_upload>> command if the size of the  _.backup_, _.dump_ or _.tar_ file exported from a database larger than 4GB.

It is highly recommended that the _.backup_,  _.dump_ , or _.tar_ file, is of version 4.4 or higher.

For more information about backups, see xref:auradb/managing-databases/backup-restore-export.adoc[].

== Import database

To import a _.backup_, _.dump_ or _.tar_ file under 4GB:

. Navigate to the link:https://console.neo4j.io/[Neo4j Aura Console] in your browser.
. Select the instance you want to import the data to.
. Select the *Import Database* tab.
. Drag and drop your file into the provided window or browse for your file.
. Select *Upload*.

When the upload is complete, the instance goes into a `Loading` state as the backup is applied.
Once this has finished, the instance returns to its `Running` state; and the data is ready.

== Neo4j Admin `database upload`

[CAUTION]
====
This command does not work if you have a network access configuration setup that prevents public traffic to the region your instance is hosted in.
See <<_public_traffic>> below for more information.
====

`database upload` is a `neo4j-admin` command that you can run to upload the contents of a Neo4j database into an Aura instance, regardless of the database's size.
Keep in mind that the database you want to upload may run a different version of Neo4j than your Aura instance.
Additionally, your Neo4j Aura instance must be accessible from the machine running `neo4j-admin`.
Otherwise, the upload will fail with SSL errors.

For details on how to use the `neo4j-admin database upload` command, along with a full list of options and version compatibility, see link:{neo4j-docs-base-uri}/operations-manual/current/tools/neo4j-admin/upload-to-aura/[Operations Manual -> Upload to Neo4j Aura].

[NOTE]
====
The `database upload` command, introduced in Neo4j 5, replaces the `push-to-cloud` command in Neo4j 4.4 and 4.3.
If the database you want to upload is running an earlier version of Neo4j, please see the link:{neo4j-docs-base-uri}/operations-manual/4.4/tools/neo4j-admin/push-to-cloud/[Neo4j Admin push-to-cloud documentation].
====

[CAUTION]
====
The `neo4j-admin push-to-cloud` command in Neo4j 4.4 and earlier is not compatible with instances encrypted with xref:platform/security/encryption.adoc#_customer_managed_keys[Customer Managed Keys].
Use `neo4j-admin database upload` in Neo4j 5 to upload data to instances encrypted with Customer Managed Keys.

For Neo4j 4.x instances in Azure encrypted with Customer Managed Keys, use Neo4j Data Importer to load data, as `neo4j-admin database upload` is not supported.
See the https://neo4j.com/docs/data-importer/current/introduction[Data Importer documentation] for more information.
====

=== Public traffic
If you have created a network access configuration from the *Network Access* page, accessed through the sidebar menu of the Console, *Public traffic* must be enabled for the region your instance is hosted in before you can use the `database upload` command on that instance.

To enable *Public traffic* on a network access configuration:

. Select *Configure* next to the region that has *Public traffic* disabled.
. Select *Next* until you reach step 4 of 4 in the resulting *Edit network access configuration* modal.
. Clear the *Disable public traffic* checkbox and select *Save*.

You can now use the `database upload` command on the instances within that region.
Once the command has completed, you can disable *Public traffic* again by following the same steps and re-selecting the *Disable public traffic* checkbox.
