[[aura-getting-started-bloom]]
= Aura with Bloom
:description: This page describes how Neo4j Aura instances can be opened with the data visualization tool, Neo4j Bloom.

Neo4j Aura comes with its own integrated version of Neo4j Bloom for data visualization.
For more details on using Bloom, please see the https://neo4j.com/docs/bloom-user-guide/current/[Neo4j Bloom documentation].


== Using Bloom in Aura

You can open your Aura database with Neo4j Bloom by selecting *Neo4j Bloom* when you use the *Open with* option in the console.


== Bloom Perspectives in Aura

In Neo4j Bloom, a Perspective defines a certain business view or domain that can be found in the target Neo4j graph.
A single Neo4j graph can be viewed through different Perspectives, each tailored for a different business purpose.

Perspectives define:

* Categorization of business entities.
* Property visibility and value type.
* Relationship visibility.
* Styling (color, icon, caption).
* Custom Search phrases (see later section).

For more information, see https://neo4j.com/docs/bloom-user-guide/1.5/bloom-perspectives/[Bloom Perspectives].

Due to the nature of Aura's infrastructure, it is not currently possible to share Perspectives in Bloom, as the data for a given Perspective is stored in a cookie in the user's web browser.

Alternatively, you can export your perspective as a JSON file.
This JSON file can then be imported another Bloom session.

The following steps will export a perspective:

. Open the Bloom interface for your Neo4j Aura database.
. Navigate to the _Perspectives Gallery_.
. Click on the vertical ellipsis (*...*) and select *Export*.
. Save the file to your local disk.

You can import perspectives by clicking the blue "Import Perspective" button in the Perspective gallery.
Please note that the Perspective will expose details about your graph's schema, but not the actual data within.
