= Managing dashboards
:description: Create and modify Neo4j dashboards.

In Neo4j Aura, click **Dashboards** under **Tools** in the left-side navigation to access the dashboard page.


== Creating a dashboard

. In the **Dashboards** page, use **Create Dashboard** at the top right.
. The UI takes you directly to the new dashboard.


== Editing a dashboard

. Select a dashboard tile from the the **Dashboards** page.
. To change the title, select the title text and edit it, then confirm.


=== Dashboard pages

Select a dashboard tile from the the **Dashboards** page.
Dashboard pages are organized as tabs.
A new dashboard contains a single page "Main page".
You can edit or duplicate the page via hovering the page name and using the three dots icon.
Add more pages via **+** next to the existing pages' names.
Additional pages can also be deleted from the three dots menu.


=== Dashboard cards

A dashboard page consists of cards.
Each card can hold a xref::/dashboards/visualizations/index.adoc[visualization], also referred to as the **Chart type**.
To add a card, use **Add card* at the bottom right.
Use the three dots at the top right of a card to edit the card.
Click the six dots at the top left of a card to drag and drop it within the grid of the page.


////
== Loading a dashboard

Lorem ipsum.


== Dashboard settings

Lorem ipsum.

////


== Deleting a dashboard

In the dashboards tile page, use the three dots icon of a dashboard tile and select **Delete**, then confirm.