= Managing dashboards
:description: Create and modify Neo4j dashboards.

In Neo4j Aura, click **Dashboards** under **Tools** in the left-side navigation to access the **Dashboards** page.

== Creating a dashboard

. In the **Dashboards** page, use **New Dashboard** at the top right.
. Enter a title and an optional description in the **New dashboard** dialog, then **Create**.
. A new dashboard tile is added to the dashboards gallery.

== Editing a dashboard

. In the **Dashboards** page, use the three dots of the tile you want to edit.
. Select **Edit name/description**.
. Enter a title and a description and **Save**.

=== Dashboard pages

Select a dashboard tile.
If you are prompted to **Connect to instance**, select the instance with your data set.
Dashboard pages are organized as tabs.
A new dashboard contains a single page "Default page".
You can edit, delete or duplicate the page via the three dots and add more pages via **+** next to the existing pages' names.


=== Dashboard cards

A dashboard page consists of cards.
Each card can hold a xref::/dashboards/visualizations/index.adoc[visualization], also referred to as the **Chart type**.
To add a card, use **Add card* at the bottom right.
Use the three dots at the top right of a card to edit the card.
Click the six dots at the top left of a card to drag and drop it within the grid of the page.


////
== Loading a dashboard

Lorem ipsum.


== Dashboard settings

Lorem ipsum.

////


== Deleting a dashboard

In the dashboards tile page, use the three dots icon of a dashboard tile and select **Delete**, then confirm.