[[connecting-kafka]]
= Neo4j Connector for Apache Kafka
:description: This page describes how to connect to Aura using Kafka.
:page-aliases: platform/connectors/kafka.adoc

Many users and customers want to integrate Kafka and other streaming solutions with Neo4j, either to ingest data into the graph from other sources or to send update events to the event log for later consumption.
Aura supports the use of the https://neo4j.com/docs/kafka/[Kafka Connect Neo4j Connector^], which allows you to ingest data into Neo4j from Kafka topics or send change events from Neo4j into Kafka topics.

Connecting to Aura only requires to make a few changes to the https://neo4j.com/docs/kafka/kafka-connect/source/[source^] and https://neo4j.com/docs/kafka/kafka-connect/sink/[sink^] configuration examples:

* Replace the `bolt` URI in the examples (the value of the `neo4j.server.uri` configuration parameter) with the `neo4j+s://` connection URI from the Aura instance detail page
* Update the username and password configuration parameters as appropriate

For more information check the https://neo4j.com/docs/kafka/[Kafka Connect Neo4j Connector^] user guide.